/- Transpiled from ../theories/Elements/OriginalProofs/proposition_26B.v :: proposition_26B
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_26helper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy1
import GeocoqTranslate.Elements.OriginalProofs.proposition_04
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem proposition_26B :
    ∀ (A B C D E F : Point), Triangle A B C → Triangle D E F → CongA A B C D E F → CongA B C A E F D → Cong A B D E → Cong B C E F ∧ Cong A C D F ∧ CongA B A C E D F := by
  intro A B C D E F h1 h2 h3 h4 h5
  have : ¬ Lt E F B C := by conclude lemma_26helper
  have : CongA D E F A B C := by conclude lemma_equalanglessymmetric
  have : CongA E F D B C A := by conclude lemma_equalanglessymmetric
  have : Cong D E A B := by conclude lemma_congruencesymmetric
  have : ¬ Lt B C E F := by conclude lemma_26helper
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      have : nCol A B C := by conclude_def Triangle
      contradict
  have : ¬ E = F := by
      intro h
      have : Col D E F := by conclude_def Col
      have : nCol D E F := by conclude_def Triangle
      contradict
  have : Cong B C E F := by conclude lemma_trichotomy1
  have : Cong B A E D := by forward_using lemma_congruenceflip
  have : (Cong A C D F ∧ CongA B A C E D F ∧ CongA B C A E F D) := by conclude proposition_04
  close

end GeocoqTranslate.Elements
