/- Transpiled from ../theories/Elements/OriginalProofs/proposition_12.v :: proposition_12
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.proposition_10
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem proposition_12 :
    ∀ (A B C : Point), nCol A B C → ∃ X, Perp_at C X A B X := by
  intro A B C h1
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (BetS C B E ∧ Cong B E C B) := by conclude lemma_extension
  have : C ≠ E := by forward_using lemma_betweennotequal
  have : E ≠ C := by conclude lemma_inequalitysymmetric
  obtain ⟨F, _, _⟩ : ∃ F, (BetS E C F ∧ Cong C F E C) := by conclude lemma_extension
  have : Cong E C C E := by conclude cn_equalityreverse
  have : Cong C E C E := by conclude cn_congruencereflexive
  have : Cong C F C E := by conclude lemma_congruencetransitive
  have : BetS E B C := by conclude axiom_betweennesssymmetry
  have : BetS E B F := by conclude lemma_3_6b
  obtain ⟨K, _⟩ : ∃ K, CI K C C E := by conclude postulate_Euclid3
  have : Cong C E C E := by conclude cn_congruencereflexive
  have : Cong C B C B := by conclude cn_congruencereflexive
  have : InCirc B K := by conclude_def InCirc
  obtain ⟨P, Q, _, _, _, _, _⟩ : ∃ P Q, (Col A B P ∧ BetS A B Q ∧ OnCirc P K ∧ OnCirc Q K ∧ BetS P B Q) := by conclude postulate_line_circle
  have : Col A B Q := by conclude_def Col
  have : Cong C P C E := by conclude axiom_circle_center_radius
  have : Cong C Q C E := by conclude axiom_circle_center_radius
  have : Cong C E C Q := by conclude lemma_congruencesymmetric
  have : Cong C P C Q := by conclude lemma_congruencetransitive
  have : Cong P C Q C := by forward_using lemma_congruenceflip
  have : P ≠ Q := by forward_using lemma_betweennotequal
  obtain ⟨M, _, _⟩ : ∃ M, (BetS P M Q ∧ Cong M P M Q) := by conclude proposition_10
  have : Cong P M Q M := by forward_using lemma_congruenceflip
  have : Col P M Q := by conclude_def Col
  have : Col P B Q := by conclude_def Col
  have : Col P Q B := by forward_using lemma_collinearorder
  have : Col P Q M := by forward_using lemma_collinearorder
  have : Col Q B M := by conclude lemma_collinear4
  have : Col Q B A := by forward_using lemma_collinearorder
  have : B ≠ Q := by forward_using lemma_betweennotequal
  have : Q ≠ B := by conclude lemma_inequalitysymmetric
  have : Col B M A := by conclude lemma_collinear4
  have : Col A B M := by forward_using lemma_collinearorder
  have : ¬ M = C := by
      intro h
      have : Col A B C := by conclude cn_equalitysub
      contradict
  have : Per P M C := by conclude_def Per
  have : M = M := by conclude cn_equalityreflexive
  have : Col C M M := by conclude_def Col
  have : Perp_at C M A B M := by conclude_def Perp_at
  close

end GeocoqTranslate.Elements
