/- Transpiled from ../theories/Elements/OriginalProofs/proposition_36.v :: proposition_36
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crisscross
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

theorem proposition_36 :
    ∀ (A B C D E F G H : Point), PG A B C D → PG E F G H → Col A D E → Col A D H → Col B C F → Col B C G → Cong B C F G → EF A B C D E F G H := by
  intro A B C D E F G H h1 h2 h3 h4 h5 h6 h7
  have : (Par A B C D ∧ Par A D B C) := by conclude_def PG
  have : (Par E F G H ∧ Par E H F G) := by conclude_def PG
  have : nCol E H G := by forward_using lemma_parallelNC
  have : E ≠ H := by forward_using lemma_NCdistinct
  have : nCol A B C := by forward_using lemma_parallelNC
  have : B ≠ C := by forward_using lemma_NCdistinct
  have : Cong E H F G := by forward_using proposition_34
  have : Cong F G E H := by conclude lemma_congruencesymmetric
  have : Cong B C E H := by conclude lemma_congruencetransitive
  have : Par B C A D := by conclude lemma_parallelsymmetric
  have : Par B C E H := by conclude lemma_collinearparallel2
  have : Par E H B C := by conclude lemma_parallelsymmetric
  have : Cong E H B C := by conclude lemma_congruencesymmetric
  have : ¬ ¬ (CR E C B H ∨ CR E B H C) := by
      intro h
      have : CR E C B H := by conclude lemma_crisscross
      contradict
  have : EF A B C D E F G H := by
      rcases (show CR E C B H ∨ CR E B H C by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
      · obtain ⟨M, _, _⟩ : ∃ M, (BetS E M C ∧ BetS B M H) := by conclude_def CR
        have : BetS H M B := by conclude axiom_betweennesssymmetry
        have : (Par E B H C ∧ Cong E B H C) := by conclude proposition_33
        have : Par E B C H := by forward_using lemma_parallelflip
        have : PG E B C H := by conclude_def PG
        have : EF A B C D E B C H := by conclude proposition_35
        have : Col C F G := by conclude lemma_collinear4
        have : Col G F C := by forward_using lemma_collinearorder
        have : Col C B F := by forward_using lemma_collinearorder
        have : Col C B G := by forward_using lemma_collinearorder
        have : C ≠ B := by conclude lemma_inequalitysymmetric
        have : Col B F G := by conclude lemma_collinear4
        have : Col G F B := by forward_using lemma_collinearorder
        have : Par F G E H := by conclude lemma_parallelsymmetric
        have : Par G F H E := by forward_using lemma_parallelflip
        have : Par E F G H := by conclude_def PG
        have : Par G H E F := by conclude lemma_parallelsymmetric
        have : PG G H E F := by conclude_def PG
        have : Par C H E B := by conclude lemma_parallelsymmetric
        have : Par B C E H := by conclude lemma_parallelsymmetric
        have : Par C B H E := by forward_using lemma_parallelflip
        have : PG C H E B := by conclude_def PG
        have : EF G H E F C H E B := by conclude proposition_35
        have : EF G H E F E B C H := by forward_using axiom_EFpermutation
        have : EF E B C H G H E F := by conclude axiom_EFsymmetric
        have : EF A B C D G H E F := by conclude axiom_EFtransitive
        have : EF A B C D E F G H := by forward_using axiom_EFpermutation
        close
      · obtain ⟨M, _, _⟩ : ∃ M, (BetS E M B ∧ BetS H M C) := by conclude_def CR
        have : Par H E B C := by forward_using lemma_parallelflip
        have : Cong H E B C := by forward_using lemma_congruenceflip
        have : (Par H B E C ∧ Cong H B E C) := by conclude proposition_33
        have : Par H B C E := by forward_using lemma_parallelflip
        have : PG H B C E := by conclude_def PG
        have : EF A B C D H B C E := by conclude proposition_35
        have : Col C G F := by conclude lemma_collinear4
        have : Col F G C := by forward_using lemma_collinearorder
        have : Col C B G := by forward_using lemma_collinearorder
        have : Col C B F := by forward_using lemma_collinearorder
        have : C ≠ B := by conclude lemma_inequalitysymmetric
        have : Col B G F := by conclude lemma_collinear4
        have : Col F G B := by forward_using lemma_collinearorder
        have : Par H E F G := by forward_using lemma_parallelflip
        have : Par F G H E := by conclude lemma_parallelsymmetric
        have : Par F G E H := by forward_using lemma_parallelflip
        have : Par F E H G := by forward_using lemma_parallelflip
        have : PG F E H G := by conclude_def PG
        have : Par C E H B := by conclude lemma_parallelsymmetric
        have : Par C B E H := by forward_using lemma_parallelflip
        have : PG C E H B := by conclude_def PG
        have : EF F E H G C E H B := by conclude proposition_35
        have : EF F E H G H B C E := by forward_using axiom_EFpermutation
        have : EF H B C E F E H G := by conclude axiom_EFsymmetric
        have : EF A B C D F E H G := by conclude axiom_EFtransitive
        have : EF A B C D E F G H := by forward_using axiom_EFpermutation
        close
  close

end GeocoqTranslate.Elements
