/- Transpiled from ../theories/Elements/OriginalProofs/proposition_38.v :: proposition_38
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_triangletoparallelogram
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_PGrotate
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

theorem proposition_38 :
    ∀ (A B C D E F P Q : Point), Par P Q B C → Col P Q A → Col P Q D → Cong B C E F → Col B C E → Col B C F → ET A B C D E F := by
  intro A B C D E F P Q h1 h2 h3 h4 h5 h6
  have : Par B C P Q := by conclude lemma_parallelsymmetric
  have : Par C B P Q := by forward_using lemma_parallelflip
  obtain ⟨G, _, _⟩ : ∃ G, (PG A G B C ∧ Col P Q G) := by conclude lemma_triangletoparallelogram
  have : PG G B C A := by conclude lemma_PGrotate
  have : nCol P B C := by forward_using lemma_parallelNC
  have : B ≠ C := by forward_using lemma_NCdistinct
  have : E ≠ F := by conclude axiom_nocollapse
  have : Par P Q E F := by conclude lemma_collinearparallel2
  have : Par E F P Q := by conclude lemma_parallelsymmetric
  obtain ⟨H, _, _⟩ : ∃ H, (PG D H F E ∧ Col P Q H) := by conclude lemma_triangletoparallelogram
  have : PG H F E D := by conclude lemma_PGrotate
  have : Cong B C F E := by forward_using lemma_congruenceflip
  have : nCol P Q B := by forward_using lemma_parallelNC
  have : P ≠ Q := by forward_using lemma_NCdistinct
  have : Col G A H := by conclude lemma_collinear5
  have : Col G A D := by conclude lemma_collinear5
  have : EF G B C A H F E D := by conclude proposition_36
  have : EF G B C A E F H D := by forward_using axiom_EFpermutation
  have : EF E F H D G B C A := by conclude axiom_EFsymmetric
  have : EF E F H D C B G A := by forward_using axiom_EFpermutation
  obtain ⟨M, _, _⟩ : ∃ M, (BetS D M F ∧ BetS H M E) := by conclude lemma_diagonalsmeet
  have : Col D M F := by conclude_def Col
  have : Col F D M := by forward_using lemma_collinearorder
  obtain ⟨m, _, _⟩ : ∃ m, (BetS A m B ∧ BetS G m C) := by conclude lemma_diagonalsmeet
  have : Col A m B := by conclude_def Col
  have : Col B A m := by forward_using lemma_collinearorder
  have : Par A G B C := by conclude_def PG
  have : nCol A G B := by forward_using lemma_parallelNC
  have : nCol B A G := by forward_using lemma_NCorder
  have : Par D H F E := by conclude_def PG
  have : nCol D H F := by forward_using lemma_parallelNC
  have : nCol F D H := by forward_using lemma_NCorder
  have : TS G B A C := by conclude_def TS
  have : TS C B A G := by conclude lemma_oppositesidesymmetric
  have : TS H F D E := by conclude_def TS
  have : TS E F D H := by conclude lemma_oppositesidesymmetric
  have : Cong_3 F H D D E F := by conclude proposition_34
  have : ET F H D D E F := by conclude axiom_congruentequal
  have : ET F H D E F D := by forward_using axiom_ETpermutation
  have : ET E F D F H D := by conclude axiom_ETsymmetric
  have : ET E F D F D H := by forward_using axiom_ETpermutation
  have : PG G B C A := by conclude lemma_PGrotate
  have : Cong_3 B G A A C B := by conclude proposition_34
  have : ET B G A A C B := by conclude axiom_congruentequal
  have : ET B G A C B A := by forward_using axiom_ETpermutation
  have : ET C B A B G A := by conclude axiom_ETsymmetric
  have : ET C B A B A G := by forward_using axiom_ETpermutation
  have : ET E F D C B A := by conclude axiom_halvesofequals
  have : ET E F D A B C := by forward_using axiom_ETpermutation
  have : ET A B C E F D := by conclude axiom_ETsymmetric
  have : ET A B C D E F := by forward_using axiom_ETpermutation
  close

end GeocoqTranslate.Elements
