/- Transpiled from ../theories/Elements/OriginalProofs/proposition_40.v :: proposition_40
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.proposition_31short
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.proposition_38
import GeocoqTranslate.Elements.OriginalProofs.proposition_39
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

set_option maxHeartbeats 800000 in
theorem proposition_40 :
    ∀ (A B C D E H : Point), Cong B C H E → ET A B C D H E → Triangle A B C → Triangle D H E → Col B C H → Col B C E → OS A D B C → A ≠ D → Par A D B C := by
  intro A B C D E H h1 h2 h3 h4 h5 h6 h7 h8
  have : nCol D H E := by conclude_def Triangle
  have : H ≠ E := by forward_using lemma_NCdistinct
  have : E ≠ H := by conclude lemma_inequalitysymmetric
  obtain ⟨R, _, _⟩ : ∃ R, (BetS E H R ∧ Cong H R E H) := by conclude lemma_extension
  have : BetS R H E := by conclude axiom_betweennesssymmetry
  have : nCol H E D := by forward_using lemma_NCorder
  have : Col R H E := by conclude_def Col
  have : Col H E R := by forward_using lemma_collinearorder
  have : E = E := by conclude cn_equalityreflexive
  have : Col H E E := by conclude_def Col
  have : R ≠ E := by forward_using lemma_betweennotequal
  have : nCol R E D := by conclude lemma_NChelper
  obtain ⟨P, Q, M, _, _, _, _, _⟩ : ∃ P Q M, (BetS P D Q ∧ CongA P D H D H E ∧ Par P Q R E ∧ BetS P M E ∧ BetS D M H) := by conclude proposition_31short
  have : Col R E H := by forward_using lemma_collinearorder
  have : Par P Q H E := by conclude lemma_collinearparallel
  have : Col P D Q := by conclude_def Col
  have : Col P Q D := by forward_using lemma_collinearorder
  have : Cong H E B C := by conclude lemma_congruencesymmetric
  have : Col C B H := by forward_using lemma_collinearorder
  have : Col C B E := by forward_using lemma_collinearorder
  have : nCol A B C := by conclude_def Triangle
  have : B ≠ C := by forward_using lemma_NCdistinct
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : Col B H E := by conclude lemma_collinear4
  have : Col H E B := by forward_using lemma_collinearorder
  have : Col B C H := by forward_using lemma_collinearorder
  have : Col B C E := by forward_using lemma_collinearorder
  have : Col C H E := by conclude lemma_collinear4
  have : Col H E C := by forward_using lemma_collinearorder
  have : ET D H E D B C := by conclude proposition_38
  have : ET A B C D B C := by conclude axiom_ETtransitive
  have : nCol H E D := by forward_using lemma_NCorder
  have : nCol B C D := by conclude lemma_NChelper
  have : nCol D B C := by forward_using lemma_NCorder
  have : Triangle D B C := by (try (have : nCol D B C := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Par A D B C := by conclude proposition_39
  close

end GeocoqTranslate.Elements
