/- Transpiled from ../theories/Elements/OriginalProofs/proposition_31.v :: proposition_31
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_pointreflectionisometry
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennesspreserved
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_31 :
    ∀ (A B C D : Point), BetS B D C → nCol B C A → ∃ X Y Z, BetS X A Y ∧ CongA Y A D A D B ∧ CongA Y A D B D A ∧ CongA D A Y B D A ∧ CongA X A D A D C ∧ CongA X A D C D A ∧ CongA D A X C D A ∧ Par X Y B C ∧ Cong X A D C ∧ Cong A Y B D ∧ Cong A Z Z D ∧ Cong X Z Z C ∧ Cong B Z Z Y ∧ BetS X Z C ∧ BetS B Z Y ∧ BetS A Z D := by
  intro A B C D h1 h2
  have : Col B D C := by conclude_def Col
  have : ¬ A = D := by
      intro h
      have : Col B A C := by conclude cn_equalitysub
      have : Col B C A := by forward_using lemma_collinearorder
      contradict
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M D ∧ Cong M A M D) := by conclude proposition_10
  have : Cong A M M D := by forward_using lemma_congruenceflip
  have : Col C B D := by forward_using lemma_collinearorder
  have : B = B := by conclude cn_equalityreflexive
  have : Col C B B := by conclude_def Col
  have : nCol C B A := by forward_using lemma_NCorder
  have : B ≠ D := by forward_using lemma_betweennotequal
  have : nCol B D A := by conclude lemma_NChelper
  have : Col B D C := by conclude_def Col
  have : D = D := by conclude cn_equalityreflexive
  have : Col B D D := by conclude_def Col
  have : D ≠ C := by forward_using lemma_betweennotequal
  have : C ≠ D := by conclude lemma_inequalitysymmetric
  have : nCol C D A := by conclude lemma_NChelper
  have : nCol A D C := by forward_using lemma_NCorder
  have : Col A M D := by conclude_def Col
  have : Col A D M := by forward_using lemma_collinearorder
  have : A = A := by conclude cn_equalityreflexive
  have : Col A D A := by conclude_def Col
  have : A ≠ M := by forward_using lemma_betweennotequal
  have : nCol A M C := by conclude lemma_NChelper
  have : ¬ C = M := by
      intro h
      have : Col A C M := by conclude_def Col
      have : Col A M C := by forward_using lemma_collinearorder
      contradict
  have : M ≠ C := by conclude lemma_inequalitysymmetric
  obtain ⟨E, _, _⟩ : ∃ E, (BetS C M E ∧ Cong M E M C) := by conclude lemma_extension
  have : Cong M C M E := by conclude lemma_congruencesymmetric
  have : Cong C M M E := by forward_using lemma_congruenceflip
  have : Midpoint C M E := by conclude_def Midpoint
  have : A ≠ M := by forward_using lemma_betweennotequal
  have : nCol A D B := by forward_using lemma_NCorder
  have : nCol A M B := by conclude lemma_NChelper
  have : ¬ B = M := by
      intro h
      have : Col A B M := by conclude_def Col
      have : Col A M B := by forward_using lemma_collinearorder
      contradict
  have : M ≠ B := by conclude lemma_inequalitysymmetric
  obtain ⟨F, _, _⟩ : ∃ F, (BetS B M F ∧ Cong M F M B) := by conclude lemma_extension
  have : Cong M F B M := by forward_using lemma_congruenceflip
  have : Cong B M M F := by conclude lemma_congruencesymmetric
  have : Midpoint B M F := by conclude_def Midpoint
  have : Cong M D M A := by conclude lemma_congruencesymmetric
  have : BetS D M A := by conclude axiom_betweennesssymmetry
  have : Cong D M M A := by forward_using lemma_congruenceflip
  have : Midpoint D M A := by conclude_def Midpoint
  have : B ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ C := by forward_using lemma_betweennotequal
  have : B ≠ C := by forward_using lemma_NCdistinct
  have : Cong B D F A := by conclude lemma_pointreflectionisometry
  have : Cong D C A E := by conclude lemma_pointreflectionisometry
  have : Cong B C F E := by conclude lemma_pointreflectionisometry
  have : BetS F A E := by conclude lemma_betweennesspreserved
  have : BetS E A F := by conclude axiom_betweennesssymmetry
  have : F = F := by conclude cn_equalityreflexive
  have : A ≠ F := by forward_using lemma_betweennotequal
  have : Out A F F := by conclude lemma_ray4
  have : B = B := by conclude cn_equalityreflexive
  have : B ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ B := by conclude lemma_inequalitysymmetric
  have : Out D B B := by conclude lemma_ray4
  have : A = A := by conclude cn_equalityreflexive
  have : D ≠ A := by forward_using lemma_betweennotequal
  have : Out D A A := by conclude lemma_ray4
  have : D = D := by conclude cn_equalityreflexive
  have : A ≠ D := by conclude lemma_inequalitysymmetric
  have : Out A D D := by conclude lemma_ray4
  have : nCol B M A := by forward_using lemma_NCorder
  have : Col B M F := by conclude_def Col
  have : M = M := by conclude cn_equalityreflexive
  have : Col B M M := by conclude_def Col
  have : M ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ M := by conclude lemma_inequalitysymmetric
  have : nCol F M A := by conclude lemma_NChelper
  have : nCol A M F := by forward_using lemma_NCorder
  have : Col A M A := by conclude_def Col
  have : Col A M D := by conclude_def Col
  have : nCol A D F := by conclude lemma_NChelper
  have : nCol F A D := by forward_using lemma_NCorder
  have : Cong D B A F := by forward_using lemma_congruenceflip
  have : Midpoint A M D := by conclude_def Midpoint
  have : B ≠ A := by forward_using lemma_NCdistinct
  have : Cong B A F D := by conclude lemma_pointreflectionisometry
  have : Cong F D B A := by conclude lemma_congruencesymmetric
  have : Cong A F D B := by conclude lemma_congruencesymmetric
  have : Cong A D D A := by conclude cn_equalityreverse
  have : CongA F A D B D A := by conclude_def CongA
  have : nCol B D A := by conclude lemma_NChelper
  have : CongA B D A A D B := by conclude lemma_ABCequalsCBA
  have : CongA F A D A D B := by conclude lemma_equalanglestransitive
  have : CongA A D B F A D := by conclude lemma_equalanglessymmetric
  have : nCol D A B := by forward_using lemma_NCorder
  have : nCol F A D := by forward_using lemma_NCorder
  have : CongA F A D D A F := by conclude lemma_ABCequalsCBA
  have : CongA A D B D A F := by conclude lemma_equalanglestransitive
  have : CongA D A F A D B := by conclude lemma_equalanglessymmetric
  have : nCol A D B := by forward_using lemma_NCorder
  have : CongA A D B B D A := by conclude lemma_ABCequalsCBA
  have : CongA D A F B D A := by conclude lemma_equalanglestransitive
  have : TS B A D F := by conclude_def TS
  have : TS F A D B := by conclude lemma_oppositesidesymmetric
  have : BetS C D B := by conclude axiom_betweennesssymmetry
  have : Par F E C B := by conclude proposition_27
  have : Par E F B C := by forward_using lemma_parallelflip
  have : Cong D C E A := by forward_using lemma_congruenceflip
  have : Cong E A D C := by conclude lemma_congruencesymmetric
  have : Cong B D A F := by forward_using lemma_congruenceflip
  have : Cong A F B D := by conclude lemma_congruencesymmetric
  have : Cong M C E M := by forward_using lemma_congruenceflip
  have : Cong E M M C := by conclude lemma_congruencesymmetric
  have : E ≠ A := by forward_using lemma_betweennotequal
  have : A ≠ E := by conclude lemma_inequalitysymmetric
  have : E = E := by conclude cn_equalityreflexive
  have : Out A E E := by conclude lemma_ray4
  have : D ≠ C := by forward_using lemma_betweennotequal
  have : C = C := by conclude cn_equalityreflexive
  have : Out D C C := by conclude lemma_ray4
  have : Cong E M M C := by forward_using lemma_congruenceflip
  have : BetS E M C := by conclude axiom_betweennesssymmetry
  have : Midpoint E M C := by conclude_def Midpoint
  have : ¬ E = D := by
      intro h
      have : BetS C M D := by conclude cn_equalitysub
      have : Col C M D := by conclude_def Col
      have : Col M D C := by forward_using lemma_collinearorder
      have : Col A M D := by conclude_def Col
      have : Col M D A := by forward_using lemma_collinearorder
      have : M ≠ D := by forward_using lemma_betweennotequal
      have : Col D C A := by conclude lemma_collinear4
      have : Col D C B := by forward_using lemma_collinearorder
      have : D ≠ C := by forward_using lemma_betweennotequal
      have : Col C A B := by conclude lemma_collinear4
      have : Col B C A := by forward_using lemma_collinearorder
      contradict
  sorry -- TODO: assert (neq E D) by auto.
  have : D ≠ A := by forward_using lemma_betweennotequal
  have : A ≠ D := by conclude lemma_inequalitysymmetric
  have : Cong E D C A := by conclude lemma_pointreflectionisometry
  have : Cong A E D C := by conclude lemma_pointreflectionisometry
  have : Col E A F := by conclude_def Col
  have : Col F A E := by forward_using lemma_collinearorder
  have : Col F A A := by conclude_def Col
  have : nCol E A D := by conclude lemma_NChelper
  have : CongA E A D C D A := by conclude_def CongA
  have : nCol C D A := by forward_using lemma_NCorder
  have : CongA C D A A D C := by conclude lemma_ABCequalsCBA
  have : CongA E A D A D C := by conclude lemma_equalanglestransitive
  have : nCol D A E := by forward_using lemma_NCorder
  have : CongA D A E E A D := by conclude lemma_ABCequalsCBA
  have : CongA D A E C D A := by conclude lemma_equalanglestransitive
  sorry -- TODO: remove_exists;eauto 20.

end GeocoqTranslate.Elements
