/- Transpiled from ../theories/Elements/OriginalProofs/proposition_19.v :: proposition_19
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angletrichotomy
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_19 :
    ∀ (A B C : Point), Triangle A B C → LtA B C A A B C → Lt A B A C := by
  intro A B C h1 h2
  have : nCol A B C := by conclude_def Triangle
  have : nCol B C A := by forward_using lemma_NCorder
  have : nCol A C B := by forward_using lemma_NCorder
  have : ¬ Cong A C A B := by
      intro h
      have : Cong A B A C := by conclude lemma_congruencesymmetric
      have : isosceles A B C := by conclude_def isosceles
      have : CongA A B C A C B := by conclude proposition_05
      have : CongA A C B A B C := by conclude lemma_equalanglessymmetric
      have : CongA B C A A C B := by conclude lemma_ABCequalsCBA
      have : CongA B C A A B C := by conclude lemma_equalanglestransitive
      have : LtA B C A B C A := by conclude lemma_angleorderrespectscongruence
      have : ¬ LtA B C A B C A := by conclude lemma_angletrichotomy
      contradict
  have : ¬ Lt A C A B := by
      intro h
      have : Triangle A C B := by conclude_def Triangle
      have : LtA C B A A C B := by conclude proposition_18
      have : CongA A B C C B A := by conclude lemma_ABCequalsCBA
      have : LtA A B C A C B := by conclude lemma_angleorderrespectscongruence2
      have : CongA B C A A C B := by conclude lemma_ABCequalsCBA
      have : LtA A B C B C A := by conclude lemma_angleorderrespectscongruence
      have : ¬ LtA A B C B C A := by conclude lemma_angletrichotomy
      contradict
  have : CongA A B C A B C := by conclude lemma_equalanglesreflexive
  have : A ≠ B := by forward_using lemma_angledistinct
  have : A ≠ C := by forward_using lemma_angledistinct
  have : ¬ ¬ Lt A B A C := by
      intro h
      have : Cong A B A C := by conclude lemma_trichotomy1
      have : Cong A C A B := by conclude lemma_congruencesymmetric
      contradict
  close

end GeocoqTranslate.Elements
