/- Transpiled from ../theories/Elements/OriginalProofs/proposition_28B.v :: proposition_28B
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplementsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplements
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_planeseparation
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_28B :
    ∀ (A B C D G H : Point), BetS A G B → BetS C H D → RT B G H G H D → OS B D G H → Par A B C D := by
  intro A B C D G H h1 h2 h3 h4
  have : OS D B G H := by forward_using lemma_samesidesymmetric
  obtain ⟨a, b, c, d, e, _, _, _⟩ : ∃ a b c d e, (Supp a b c e d ∧ CongA B G H a b c ∧ CongA G H D e b d) := by conclude_def RT
  have : CongA a b c B G H := by conclude lemma_equalanglessymmetric
  have : G ≠ H := by forward_using lemma_angledistinct
  have : CongA e b d G H D := by conclude lemma_equalanglessymmetric
  have : H = H := by conclude cn_equalityreflexive
  have : Out G H H := by conclude lemma_ray4
  have : Supp A G H H B := by conclude_def Supp
  have : Supp B G H H A := by conclude lemma_supplementsymmetric
  have : CongA e b d H G A := by conclude lemma_supplements
  have : CongA G H D e b d := by conclude lemma_equalanglessymmetric
  have : CongA G H D H G A := by conclude lemma_equalanglestransitive
  have : nCol H G A := by conclude lemma_equalanglesNC
  have : CongA H G A A G H := by conclude lemma_ABCequalsCBA
  have : CongA G H D A G H := by conclude lemma_equalanglestransitive
  have : CongA A G H G H D := by conclude lemma_equalanglessymmetric
  have : G = G := by conclude cn_equalityreflexive
  have : Col G H G := by conclude_def Col
  have : nCol A G H := by conclude lemma_equalanglesNC
  have : ¬ Col G H A := by
      intro h
      have : Col A G H := by forward_using lemma_collinearorder
      contradict
  have : TS A G H B := by conclude_def TS
  have : TS B G H A := by conclude lemma_oppositesidesymmetric
  have : TS D G H A := by conclude lemma_planeseparation
  have : TS A G H D := by conclude lemma_oppositesidesymmetric
  have : Par A B C D := by conclude proposition_27
  close

end GeocoqTranslate.Elements
