/- Transpiled from ../theories/Elements/OriginalProofs/proposition_18.v :: proposition_18
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleordertransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_18 :
    ∀ (A B C : Point), Triangle A B C → Lt A B A C → LtA B C A A B C := by
  intro A B C h1 h2
  have : nCol A B C := by conclude_def Triangle
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : ¬ A = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : C ≠ A := by conclude lemma_inequalitysymmetric
  have : Cong A C A C := by conclude cn_congruencereflexive
  obtain ⟨D, _, _⟩ : ∃ D, (BetS A D C ∧ Cong A D A B) := by conclude proposition_03
  have : ¬ Col B C D := by
      intro h
      have : Col D C B := by forward_using lemma_collinearorder
      have : Col A D C := by conclude_def Col
      have : Col D C A := by forward_using lemma_collinearorder
      have : D ≠ C := by forward_using lemma_betweennotequal
      have : Col C B A := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : Triangle B C D := by conclude_def Triangle
  have : BetS C D A := by conclude axiom_betweennesssymmetry
  have : LtA D C B B D A := by conclude proposition_16
  have : ¬ B = C := by
      intro h
      have : Col B C D := by conclude_def Col
      contradict
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : ¬ Col A D B := by
      intro h
      have : Col A D C := by conclude_def Col
      have : Col D A C := by forward_using lemma_collinearorder
      have : Col D A B := by forward_using lemma_collinearorder
      have : A ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A C B := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : Triangle A D B := by conclude_def Triangle
  have : isosceles A D B := by conclude_def isosceles
  have : CongA A D B A B D := by conclude proposition_05
  have : Out C A D := by conclude lemma_ray4
  have : B = B := by conclude cn_equalityreflexive
  have : Out C B B := by conclude lemma_ray4
  have : ¬ Col A C B := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : CongA A C B A C B := by conclude lemma_equalanglesreflexive
  have : CongA A C B D C B := by conclude lemma_equalangleshelper
  have : LtA A C B B D A := by conclude lemma_angleorderrespectscongruence2
  have : CongA A D B B D A := by conclude lemma_ABCequalsCBA
  have : LtA A C B A D B := by conclude lemma_angleorderrespectscongruence
  have : CongA A B D A D B := by conclude lemma_equalanglessymmetric
  have : LtA A C B A B D := by conclude lemma_angleorderrespectscongruence
  have : ¬ Col B C A := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : CongA B C A A C B := by conclude lemma_ABCequalsCBA
  have : LtA B C A A B D := by conclude lemma_angleorderrespectscongruence2
  have : C = C := by conclude cn_equalityreflexive
  have : A = A := by conclude cn_equalityreflexive
  have : Out B C C := by conclude lemma_ray4
  have : Out B A A := by conclude lemma_ray4
  have : ¬ Col A B D := by
      intro h
      have : Col A D B := by forward_using lemma_collinearorder
      contradict
  have : CongA A B D A B D := by conclude lemma_equalanglesreflexive
  have : LtA A B D A B C := by conclude_def LtA
  have : LtA B C A A B C := by conclude lemma_angleordertransitive
  close

end GeocoqTranslate.Elements
