/- Transpiled from ../theories/Elements/OriginalProofs/proposition_20.v :: proposition_20
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_20 :
    ∀ (A B C : Point), Triangle A B C → TG B A A C B C := by
  intro A B C h1
  have : nCol A B C := by conclude_def Triangle
  have : ¬ B = A := by
      intro h
      have : Col B A C := by conclude_def Col
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : ¬ C = A := by
      intro h
      have : Col B C A := by conclude_def Col
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  obtain ⟨D, _, _⟩ : ∃ D, (BetS B A D ∧ Cong A D C A) := by conclude lemma_extension
  have : A ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ A := by conclude lemma_inequalitysymmetric
  have : B ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ B := by conclude lemma_inequalitysymmetric
  have : Cong A D A C := by forward_using lemma_congruenceflip
  have : ¬ Col A D C := by
      intro h
      have : Col B A D := by conclude_def Col
      have : Col D A B := by forward_using lemma_collinearorder
      have : Col D A C := by forward_using lemma_collinearorder
      have : A ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A B C := by conclude lemma_collinear4
      contradict
  have : ¬ D = C := by
      intro h
      have : Col A D C := by conclude_def Col
      contradict
  have : Triangle A D C := by conclude_def Triangle
  have : isosceles A D C := by conclude_def isosceles
  have : CongA A D C A C D := by conclude proposition_05
  have : ¬ Col A C D := by
      intro h
      have : Col A D C := by forward_using lemma_collinearorder
      contradict
  have : CongA A C D D C A := by conclude lemma_ABCequalsCBA
  have : CongA A D C D C A := by conclude lemma_equalanglestransitive
  have : D = D := by conclude cn_equalityreflexive
  have : B = B := by conclude cn_equalityreflexive
  have : C = C := by conclude cn_equalityreflexive
  have : ¬ C = D := by
      intro h
      have : Col A C D := by conclude_def Col
      contradict
  have : Out C D D := by conclude lemma_ray4
  have : Out C B B := by conclude lemma_ray4
  have : BetS D A B := by conclude axiom_betweennesssymmetry
  have : LtA A D C D C B := by conclude_def LtA
  have : Out D A B := by conclude lemma_ray4
  have : Out D C C := by conclude lemma_ray4
  have : Out D B B := by conclude lemma_ray4
  have : Cong D B D B := by conclude cn_congruencereflexive
  have : Cong D C D C := by conclude cn_congruencereflexive
  have : Cong B C B C := by conclude cn_congruencereflexive
  have : CongA A D C B D C := by conclude_def CongA
  have : CongA B D C A D C := by conclude lemma_equalanglessymmetric
  have : LtA B D C D C B := by conclude lemma_angleorderrespectscongruence2
  have : ¬ Col B C D := by
      intro h
      have : Col B A D := by conclude_def Col
      have : Col D B A := by forward_using lemma_collinearorder
      have : Col D B C := by forward_using lemma_collinearorder
      have : B ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B A C := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : ¬ Col C D B := by
      intro h
      have : Col B C D := by forward_using lemma_collinearorder
      contradict
  have : CongA C D B B D C := by conclude lemma_ABCequalsCBA
  have : CongA B C D D C B := by conclude lemma_ABCequalsCBA
  have : LtA C D B D C B := by conclude lemma_angleorderrespectscongruence2
  have : LtA C D B B C D := by conclude lemma_angleorderrespectscongruence
  have : Triangle B C D := by conclude_def Triangle
  have : Lt B C B D := by conclude proposition_19
  have : TG B A A C B C := by conclude_def TG
  close

end GeocoqTranslate.Elements
