/- Transpiled from ../theories/Elements/OriginalProofs/proposition_05b.v :: proposition_05b
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplements
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_05b :
    ∀ (A B C F G : Point), isosceles A B C → BetS A B F → BetS A C G → CongA C B F B C G := by
  intro A B C F G h1 h2 h3
  have : CongA A B C A C B := by conclude proposition_05
  have : C = C := by conclude cn_equalityreflexive
  have : nCol A C B := by conclude lemma_equalanglesNC
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      have : Col A C B := by forward_using lemma_collinearorder
      contradict
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : Out B C C := by conclude lemma_ray4
  have : Supp A B C C F := by conclude_def Supp
  have : B = B := by conclude cn_equalityreflexive
  have : Out C B B := by conclude lemma_ray4
  have : Supp A C B B G := by conclude_def Supp
  have : CongA C B F B C G := by conclude lemma_supplements
  close

end GeocoqTranslate.Elements
