/- Transpiled from ../theories/Elements/OriginalProofs/proposition_09.v :: proposition_09
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoff
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.proposition_10
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem proposition_09 :
    ∀ (A B C : Point), nCol B A C → ∃ X, CongA B A X X A C ∧ InAngle B A C X := by
  intro A B C h1
  have : ¬ A = B := by
      intro h
      have : B = A := by conclude lemma_equalitysymmetric
      have : Col B A C := by conclude_def Col
      contradict
  have : ¬ A = C := by
      intro h
      have : Col B A C := by conclude_def Col
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (Out A C E ∧ Cong A E A B) := by conclude lemma_layoff
  have : ¬ B = E := by
      intro h
      have : Col A B E := by conclude_def Col
      have : Col A C E := by conclude lemma_rayimpliescollinear
      have : Col E A B := by perm_close
      have : Col E A C := by perm_close
      have : A ≠ E := by conclude lemma_raystrict
      have : E ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A B C := by conclude lemma_collinear4
      have : Col B A C := by perm_close
      contradict
  obtain ⟨F, _, _⟩ : ∃ F, (BetS B F E ∧ Cong F B F E) := by conclude proposition_10
  have : B = B := by conclude cn_equalityreflexive
  have : F = F := by conclude cn_equalityreflexive
  have : Cong A F A F := by conclude cn_congruencereflexive
  have : Cong A B A E := by conclude lemma_congruencesymmetric
  have : Cong E F B F := by forward_using lemma_doublereverse
  have : Cong B F E F := by conclude lemma_congruencesymmetric
  have : ¬ Col B A F := by
      intro h
      have : Col B F E := by conclude_def Col
      have : Col F B E := by perm_close
      have : Col F B A := by perm_close
      have : B ≠ F := by forward_using lemma_betweennotequal
      have : F ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B E A := by conclude lemma_collinear4
      have : Col A C E := by conclude lemma_rayimpliescollinear
      have : Col E A B := by perm_close
      have : Col E A C := by perm_close
      have : A ≠ E := by conclude lemma_raystrict
      have : E ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A B C := by conclude lemma_collinear4
      have : Col B A C := by perm_close
      contradict
  have : Out A B B := by conclude lemma_ray4
  have : ¬ A = F := by
      intro h
      have : Col B A F := by conclude_def Col
      contradict
  have : Out A F F := by conclude lemma_ray4
  have : CongA B A F C A F := by (try (have : nCol B A F := nCol_notCol _ _ _ (by assumption))); conclude_def CongA
  have : CongA C A F B A F := by conclude lemma_equalanglessymmetric
  have : nCol C A F := by conclude_def CongA
  have : CongA C A F F A C := by conclude lemma_ABCequalsCBA
  have : CongA B A F F A C := by conclude lemma_equalanglestransitive
  have : InAngle B A C F := by conclude_def InAngle
  close

end GeocoqTranslate.Elements
