/- Transpiled from ../theories/Elements/OriginalProofs/proposition_39.v :: proposition_39
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesideflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crossbar2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angletrichotomy2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

theorem proposition_39 :
    ∀ (A B C D : Point), Triangle A B C → Triangle D B C → OS A D B C → ET A B C D B C → A ≠ D → Par A D B C := by
  intro A B C D h1 h2 h3 h4 h5
  have : OS D A B C := by forward_using lemma_samesidesymmetric
  have : OS A D C B := by conclude lemma_samesideflip
  have : OS D A C B := by forward_using lemma_samesidesymmetric
  have : nCol A B C := by conclude_def Triangle
  have : nCol D B C := by conclude_def Triangle
  have : A ≠ B := by forward_using lemma_NCdistinct
  have : B ≠ D := by forward_using lemma_NCdistinct
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : B ≠ C := by forward_using lemma_NCdistinct
  have : C ≠ A := by forward_using lemma_NCdistinct
  have : C ≠ B := by forward_using lemma_NCdistinct
  have : C ≠ D := by forward_using lemma_NCdistinct
  have : A = A := by conclude cn_equalityreflexive
  have : C = C := by conclude cn_equalityreflexive
  have : D = D := by conclude cn_equalityreflexive
  have : B = B := by conclude cn_equalityreflexive
  have : Out B C C := by conclude lemma_ray4
  have : Out B A A := by conclude lemma_ray4
  have : Out B D D := by conclude lemma_ray4
  have : Out C B B := by conclude lemma_ray4
  have : Out C A A := by conclude lemma_ray4
  have : Out C D D := by conclude lemma_ray4
  have : ¬ ¬ Par A D B C := by
      intro h
      have : ¬ LtA C B D C B A := by
          intro h
          obtain ⟨M, _, _⟩ : ∃ M, (BetS A M C ∧ Out B D M) := by conclude lemma_crossbar2
          have : Par A D B C := by conclude proposition_39A
          contradict
      have : ¬ LtA C B A C B D := by
          intro h
          obtain ⟨M, _, _⟩ : ∃ M, (BetS D M C ∧ Out B A M) := by conclude lemma_crossbar2
          have : ET D B C A B C := by conclude axiom_ETsymmetric
          have : Par D A B C := by conclude proposition_39A
          have : Par A D B C := by forward_using lemma_parallelflip
          contradict
      have : ¬ ¬ CongA C B D C B A := by
          intro h
          have : nCol C B A := by forward_using lemma_NCorder
          have : nCol C B D := by forward_using lemma_NCorder
          have : LtA C B D C B A := by conclude lemma_angletrichotomy2
          contradict
      have : nCol A C B := by forward_using lemma_NCorder
      have : Triangle A C B := by conclude_def Triangle
      have : nCol D C B := by forward_using lemma_NCorder
      have : Triangle D C B := by conclude_def Triangle
      have : OS A D C B := by conclude lemma_samesideflip
      have : ET A B C D C B := by forward_using axiom_ETpermutation
      have : ET D C B A B C := by conclude axiom_ETsymmetric
      have : ET D C B A C B := by forward_using axiom_ETpermutation
      have : ET A C B D C B := by conclude axiom_ETsymmetric
      have : ¬ LtA B C D B C A := by
          intro h
          obtain ⟨M, _, _⟩ : ∃ M, (BetS A M B ∧ Out C D M) := by conclude lemma_crossbar2
          have : Par A D C B := by conclude proposition_39A
          have : Par A D B C := by forward_using lemma_parallelflip
          contradict
      have : ¬ LtA B C A B C D := by
          intro h
          obtain ⟨M, _, _⟩ : ∃ M, (BetS D M B ∧ Out C A M) := by conclude lemma_crossbar2
          have : ET D C B A C B := by conclude axiom_ETsymmetric
          have : Par D A C B := by conclude proposition_39A
          have : Par A D B C := by forward_using lemma_parallelflip
          contradict
      have : ¬ ¬ CongA B C D B C A := by
          intro h
          have : nCol B C A := by forward_using lemma_NCorder
          have : nCol B C D := by forward_using lemma_NCorder
          have : LtA B C D B C A := by conclude lemma_angletrichotomy2
          contradict
      have : CongA B C A B C D := by conclude lemma_equalanglessymmetric
      have : Cong B C B C := by conclude cn_congruencereflexive
      have : CongA D B C A B C := by conclude lemma_equalanglesflip
      have : CongA A B C D B C := by conclude lemma_equalanglessymmetric
      have : (Cong A B D B ∧ Cong A C D C ∧ CongA B A C B D C) := by conclude proposition_26A
      have : B ≠ C := by forward_using lemma_NCdistinct
      have : A = D := by conclude proposition_07
      contradict
  close

end GeocoqTranslate.Elements
