/- Transpiled from ../theories/Elements/OriginalProofs/proposition_08.v :: proposition_08
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_08 :
    ∀ (A B C D E F : Point), Triangle A B C → Triangle D E F → Cong A B D E → Cong A C D F → Cong B C E F → CongA B A C E D F ∧ CongA C B A F E D ∧ CongA A C B D F E := by
  intro A B C D E F h1 h2 h3 h4 h5
  have : E = E := by conclude cn_equalityreflexive
  have : F = F := by conclude cn_equalityreflexive
  have : B = B := by conclude cn_equalityreflexive
  have : C = C := by conclude cn_equalityreflexive
  have : D = D := by conclude cn_equalityreflexive
  have : A = A := by conclude cn_equalityreflexive
  have : nCol A B C := by conclude_def Triangle
  have : nCol D E F := by conclude_def Triangle
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : ¬ D = E := by
      intro h
      have : Col D E F := by conclude_def Col
      contradict
  have : E ≠ D := by conclude lemma_inequalitysymmetric
  have : ¬ A = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : C ≠ A := by conclude lemma_inequalitysymmetric
  have : ¬ D = F := by
      intro h
      have : Col D E F := by conclude_def Col
      contradict
  have : F ≠ D := by conclude lemma_inequalitysymmetric
  have : ¬ E = F := by
      intro h
      have : Col D E F := by conclude_def Col
      contradict
  have : F ≠ E := by conclude lemma_inequalitysymmetric
  have : Out D E E := by conclude lemma_ray4
  have : Out D F F := by conclude lemma_ray4
  have : Out A B B := by conclude lemma_ray4
  have : Out A C C := by conclude lemma_ray4
  have : ¬ Col B A C := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : CongA B A C E D F := by conclude_def CongA
  have : Cong B A E D := by forward_using lemma_congruenceflip
  have : Cong C A F D := by forward_using lemma_congruenceflip
  have : Out E F F := by conclude lemma_ray4
  have : Out E D D := by conclude lemma_ray4
  have : Out B C C := by conclude lemma_ray4
  have : Out B A A := by conclude lemma_ray4
  have : ¬ Col C B A := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : CongA C B A F E D := by conclude_def CongA
  have : Cong C A F D := by forward_using lemma_congruenceflip
  have : Cong C B F E := by forward_using lemma_congruenceflip
  have : Out F D D := by conclude lemma_ray4
  have : Out F E E := by conclude lemma_ray4
  have : Out C A A := by conclude lemma_ray4
  have : Out C B B := by conclude lemma_ray4
  have : ¬ Col A C B := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : CongA A C B D F E := by conclude_def CongA
  close

end GeocoqTranslate.Elements
