/- Transpiled from ../theories/Elements/OriginalProofs/proposition_10.v :: proposition_10
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_differenceofparts
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_interior5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennesspreserved
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_twolines
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_10 :
    ∀ (A B : Point), A ≠ B → ∃ X, BetS A X B ∧ Cong X A X B := by
  intro A B h1
  obtain ⟨C, _, _⟩ : ∃ C, (equilateral A B C ∧ Triangle A B C) := by conclude proposition_01
  have : nCol A B C := by conclude_def Triangle
  have : (Cong A B B C ∧ Cong B C C A) := by conclude_def equilateral
  have : Cong A C C B := by forward_using lemma_doublereverse
  have : Cong A C B C := by forward_using lemma_congruenceflip
  have : ¬ C = B := by
      intro h
      have : Col A C B := by conclude_def Col
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  obtain ⟨D, _, _⟩ : ∃ D, (BetS C B D ∧ Cong B D A B) := by conclude lemma_extension
  have : ¬ C = A := by
      intro h
      have : Col B C A := by conclude_def Col
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (BetS C A E ∧ Cong A E A B) := by conclude lemma_extension
  have : BetS D B C := by conclude axiom_betweennesssymmetry
  have : BetS E A C := by conclude axiom_betweennesssymmetry
  have : ¬ Col D C E := by
      intro h
      have : Col C A E := by conclude_def Col
      have : Col C B D := by conclude_def Col
      have : Col E C D := by forward_using lemma_collinearorder
      have : Col E C A := by forward_using lemma_collinearorder
      have : C ≠ E := by forward_using lemma_betweennotequal
      have : E ≠ C := by conclude lemma_inequalitysymmetric
      have : Col C D A := by conclude lemma_collinear4
      have : Col D C B := by forward_using lemma_collinearorder
      have : Col D C A := by forward_using lemma_collinearorder
      have : C ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ C := by conclude lemma_inequalitysymmetric
      have : Col C B A := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  obtain ⟨F, _, _⟩ : ∃ F, (BetS D F A ∧ BetS E F B) := by conclude postulate_Pasch_inner
  have : BetS B F E := by conclude axiom_betweennesssymmetry
  have : BetS A F D := by conclude axiom_betweennesssymmetry
  have : C ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ C := by conclude lemma_inequalitysymmetric
  have : ¬ Col A D C := by
      intro h
      have : Col C B D := by conclude_def Col
      have : Col D C A := by forward_using lemma_collinearorder
      have : Col D C B := by forward_using lemma_collinearorder
      have : Col C A B := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M B ∧ BetS C M F) := by conclude postulate_Pasch_inner
  have : Cong C A C B := by forward_using lemma_congruenceflip
  have : Cong A B A E := by conclude lemma_congruencesymmetric
  have : Cong B D A E := by conclude lemma_congruencetransitive
  have : Cong A E B D := by conclude lemma_congruencesymmetric
  have : Cong A B B A := by conclude cn_equalityreverse
  have : Cong C B C A := by conclude lemma_congruencesymmetric
  have : Cong B E A D := by conclude axiom_5_line
  have : Cong B F B F := by conclude cn_congruencereflexive
  have : Lt B F B E := by conclude_def Lt
  have : Cong A D B E := by conclude lemma_congruencesymmetric
  obtain ⟨G, _, _⟩ : ∃ G, (BetS A G D ∧ Cong A G B F) := by conclude proposition_03
  have : Cong G D F E := by conclude lemma_differenceofparts
  have : Cong E F D G := by forward_using lemma_doublereverse
  have : Cong F B G A := by forward_using lemma_doublereverse
  have : Cong E A D B := by forward_using lemma_congruenceflip
  have : Cong B A A B := by conclude cn_equalityreverse
  have : BetS D G A := by conclude axiom_betweennesssymmetry
  have : Cong F A G B := by conclude lemma_interior5
  have : Cong A F B G := by forward_using lemma_congruenceflip
  have : Cong E D D E := by conclude cn_equalityreverse
  have : Cong F D G E := by conclude lemma_interior5
  have : BetS B G E := by conclude lemma_betweennesspreserved
  have : BetS E G B := by conclude axiom_betweennesssymmetry
  have : ¬ Col A D E := by
      intro h
      have : Col C A E := by conclude_def Col
      have : Col A E D := by forward_using lemma_collinearorder
      have : Col A E C := by forward_using lemma_collinearorder
      have : A ≠ E := by forward_using lemma_betweennotequal
      have : Col E D C := by conclude lemma_collinear4
      have : Col E C D := by forward_using lemma_collinearorder
      have : Col E C A := by forward_using lemma_collinearorder
      have : C ≠ E := by forward_using lemma_betweennotequal
      have : E ≠ C := by conclude lemma_inequalitysymmetric
      have : Col C D A := by conclude lemma_collinear4
      have : Col C B D := by conclude_def Col
      have : Col D C A := by forward_using lemma_collinearorder
      have : Col D C B := by forward_using lemma_collinearorder
      have : C ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ C := by conclude lemma_inequalitysymmetric
      have : Col C A B := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : ¬ Col A D B := by
      intro h
      have : Col D B A := by forward_using lemma_collinearorder
      have : Col C B D := by conclude_def Col
      have : Col D B C := by forward_using lemma_collinearorder
      have : B ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B A C := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : Cut A D E B G := by conclude_def Cut
  have : Cut A D E B F := by conclude_def Cut
  have : ¬ Col D E B := by
      intro h
      have : Col C B D := by conclude_def Col
      have : Col D B C := by forward_using lemma_collinearorder
      have : Col D B E := by forward_using lemma_collinearorder
      have : B ≠ D := by forward_using lemma_betweennotequal
      have : D ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B C E := by conclude lemma_collinear4
      have : Col C A E := by conclude_def Col
      have : Col E C A := by forward_using lemma_collinearorder
      have : Col E C B := by forward_using lemma_collinearorder
      have : C ≠ E := by forward_using lemma_betweennotequal
      have : E ≠ C := by conclude lemma_inequalitysymmetric
      have : Col C A B := by conclude lemma_collinear4
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : G = F := by conclude lemma_twolines
  have : Cong A F B F := by conclude cn_equalitysub
  have : Cong F A F B := by forward_using lemma_congruenceflip
  have : Cong C M C M := by conclude cn_congruencereflexive
  have : Cong M F M F := by conclude cn_congruencereflexive
  have : Cong M A M B := by conclude lemma_interior5
  close

end GeocoqTranslate.Elements
