/- Transpiled from ../theories/Elements/OriginalProofs/proposition_29.v :: proposition_29
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crossbar2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplements
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplementinequality
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_planeseparation
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angletrichotomy2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplementsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

theorem proposition_29 :
    ∀ (A B C D E G H : Point), Par A B C D → BetS A G B → BetS C H D → BetS E G H → TS A G H D → CongA A G H G H D ∧ CongA E G B G H D ∧ RT B G H G H D := by
  intro A B C D E G H h1 h2 h3 h4 h5
  have : Col C H D := by conclude_def Col
  have : G ≠ H := by forward_using lemma_betweennotequal
  have : A ≠ B := by forward_using lemma_betweennotequal
  have : C ≠ D := by forward_using lemma_betweennotequal
  obtain ⟨R, _, _, _⟩ : ∃ R, (BetS A R D ∧ Col G H R ∧ nCol G H A) := by conclude_def TS
  have : TS D G H A := by conclude lemma_oppositesidesymmetric
  have : nCol G H D := by conclude_def TS
  have : nCol D H G := by forward_using lemma_NCorder
  have : Col D H C := by forward_using lemma_collinearorder
  have : H = H := by conclude cn_equalityreflexive
  have : Col D H H := by conclude_def Col
  have : C ≠ H := by forward_using lemma_betweennotequal
  have : nCol C H G := by conclude lemma_NChelper
  have : C = C := by conclude cn_equalityreflexive
  have : Col C H C := by conclude_def Col
  have : C ≠ D := by forward_using lemma_betweennotequal
  have : nCol C D G := by conclude lemma_NChelper
  obtain ⟨P, Q, S, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩ : ∃ P Q S, (BetS P G Q ∧ CongA Q G H G H C ∧ CongA Q G H C H G ∧ CongA H G Q C H G ∧ CongA P G H G H D ∧ CongA P G H D H G ∧ CongA H G P D H G ∧ Par P Q C D ∧ Cong P G H D ∧ Cong G Q C H ∧ Cong G S S H ∧ Cong P S S D ∧ Cong C S S Q ∧ BetS P S D ∧ BetS C S Q ∧ BetS G S H) := by conclude proposition_31
  have : ¬ Meet A B C D := by conclude_def Par
  have : P = P := by conclude cn_equalityreflexive
  have : P ≠ G := by forward_using lemma_betweennotequal
  have : G ≠ P := by conclude lemma_inequalitysymmetric
  have : Out G P P := by conclude lemma_ray4
  have : Col G S H := by conclude_def Col
  have : Col G H S := by forward_using lemma_collinearorder
  have : CongA G H D P G H := by conclude lemma_equalanglessymmetric
  have : nCol P G H := by conclude lemma_equalanglesNC
  have : nCol G H P := by forward_using lemma_NCorder
  have : OS A P G H := by conclude_def OS
  have : H = H := by conclude cn_equalityreflexive
  have : G ≠ H := by forward_using lemma_betweennotequal
  have : Out G H H := by conclude lemma_ray4
  have : ¬ LtA H G A H G P := by
      intro h
      obtain ⟨M, _, _⟩ : ∃ M, (BetS P M H ∧ Out G A M) := by conclude lemma_crossbar2
      have : Cong G S H S := by forward_using lemma_congruenceflip
      have : Cong S P S D := by forward_using lemma_congruenceflip
      obtain ⟨K, _, _⟩ : ∃ K, (BetS G M K ∧ BetS D H K) := by conclude postulate_Euclid5
      have : Col G A M := by conclude lemma_rayimpliescollinear
      have : Col G M K := by conclude_def Col
      have : Col M G A := by forward_using lemma_collinearorder
      have : Col M G K := by forward_using lemma_collinearorder
      have : G ≠ M := by conclude lemma_raystrict
      have : M ≠ G := by conclude lemma_inequalitysymmetric
      have : Col G A K := by conclude lemma_collinear4
      have : Col A G B := by conclude_def Col
      have : Col A G K := by forward_using lemma_collinearorder
      have : Col G A B := by forward_using lemma_collinearorder
      have : Col G A K := by forward_using lemma_collinearorder
      have : A ≠ G := by forward_using lemma_betweennotequal
      have : G ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A B K := by conclude lemma_collinear4
      have : Col H D K := by conclude_def Col
      have : Col H D C := by forward_using lemma_collinearorder
      have : H ≠ D := by forward_using lemma_betweennotequal
      have : Col D K C := by conclude lemma_collinear4
      have : Col C D K := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ LtA H G P H G A := by
      intro h
      have : nCol P G H := by forward_using lemma_NCorder
      have : CongA P G H H G P := by conclude lemma_ABCequalsCBA
      have : LtA P G H H G A := by conclude lemma_angleorderrespectscongruence2
      have : ¬ Col H G A := by
          intro h
          have : Col G H A := by forward_using lemma_collinearorder
          contradict
      have : CongA H G A A G H := by conclude lemma_ABCequalsCBA
      have : CongA A G H H G A := by conclude lemma_equalanglessymmetric
      have : LtA P G H A G H := by conclude lemma_angleorderrespectscongruence
      have : H = H := by conclude cn_equalityreflexive
      have : Out G H H := by conclude lemma_ray4
      have : Supp P G H H Q := by conclude_def Supp
      have : BetS D H C := by conclude axiom_betweennesssymmetry
      have : G = G := by conclude cn_equalityreflexive
      have : H ≠ G := by conclude lemma_inequalitysymmetric
      have : Out H G G := by conclude lemma_ray4
      have : Supp D H G G C := by conclude_def Supp
      have : CongA G H D D H G := by conclude lemma_ABCequalsCBA
      have : CongA P G H D H G := by conclude lemma_equalanglestransitive
      have : CongA H G Q G H C := by conclude lemma_supplements
      have : Supp A G H H B := by conclude_def Supp
      have : LtA H G B H G Q := by conclude lemma_supplementinequality
      have : BetS B G A := by conclude axiom_betweennesssymmetry
      have : G = G := by conclude cn_equalityreflexive
      have : Col G H G := by conclude_def Col
      have : ¬ Col G H B := by
          intro h
          have : Col A G B := by conclude_def Col
          have : Col B G A := by forward_using lemma_collinearorder
          have : Col B G H := by forward_using lemma_collinearorder
          have : G ≠ B := by forward_using lemma_betweennotequal
          have : B ≠ G := by conclude lemma_inequalitysymmetric
          have : Col G A H := by conclude lemma_collinear4
          have : Col H G A := by forward_using lemma_collinearorder
          contradict
      have : TS B G H A := by conclude_def TS
      have : TS A G H B := by conclude lemma_oppositesidesymmetric
      have : OS A P G H := by conclude_def OS
      have : OS P A G H := by forward_using lemma_samesidesymmetric
      have : TS P G H B := by conclude lemma_planeseparation
      obtain ⟨L, _, _, _⟩ : ∃ L, (BetS P L B ∧ Col G H L ∧ nCol G H P) := by conclude_def TS
      have : BetS B L P := by conclude axiom_betweennesssymmetry
      have : CongA G H C H G Q := by conclude lemma_equalanglessymmetric
      have : nCol H G Q := by conclude lemma_equalanglesNC
      have : ¬ Col G H Q := by
          intro h
          have : Col H G Q := by forward_using lemma_collinearorder
          contradict
      have : BetS Q G P := by conclude axiom_betweennesssymmetry
      have : OS B Q G H := by conclude_def OS
      have : Q = Q := by conclude cn_equalityreflexive
      have : Q ≠ G := by forward_using lemma_betweennotequal
      have : G ≠ Q := by conclude lemma_inequalitysymmetric
      have : Out G Q Q := by conclude lemma_ray4
      obtain ⟨M, _, _⟩ : ∃ M, (BetS Q M H ∧ Out G B M) := by conclude lemma_crossbar2
      have : Cong G S H S := by forward_using lemma_congruenceflip
      have : BetS Q S C := by conclude axiom_betweennesssymmetry
      have : Cong S Q C S := by conclude lemma_congruencesymmetric
      have : Cong S Q S C := by forward_using lemma_congruenceflip
      have : nCol G H C := by forward_using lemma_NCorder
      obtain ⟨K, _, _⟩ : ∃ K, (BetS G M K ∧ BetS C H K) := by conclude postulate_Euclid5
      have : Col G B M := by conclude lemma_rayimpliescollinear
      have : Col G M K := by conclude_def Col
      have : Col M G B := by forward_using lemma_collinearorder
      have : Col M G K := by forward_using lemma_collinearorder
      have : G ≠ M := by conclude lemma_raystrict
      have : M ≠ G := by conclude lemma_inequalitysymmetric
      have : Col G B K := by conclude lemma_collinear4
      have : Col B G A := by conclude_def Col
      have : Col B G K := by forward_using lemma_collinearorder
      have : Col G B A := by forward_using lemma_collinearorder
      have : Col G B K := by forward_using lemma_collinearorder
      have : B ≠ G := by forward_using lemma_betweennotequal
      have : G ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B A K := by conclude lemma_collinear4
      have : Col A B K := by forward_using lemma_collinearorder
      have : Col H C K := by conclude_def Col
      have : Col H C D := by forward_using lemma_collinearorder
      have : H ≠ C := by forward_using lemma_betweennotequal
      have : Col C K D := by conclude lemma_collinear4
      have : Col C D K := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ Col H G P := by
      intro h
      have : Col G H P := by forward_using lemma_collinearorder
      contradict
  have : ¬ Col H G A := by
      intro h
      have : Col G H A := by forward_using lemma_collinearorder
      have : nCol G H A := by conclude_def TS
      contradict
  have : ¬ ¬ CongA H G A H G P := by
      intro h
      have : LtA H G A H G P := by conclude lemma_angletrichotomy2
      contradict
  have : CongA H G P P G H := by conclude lemma_ABCequalsCBA
  have : CongA H G P G H D := by conclude lemma_equalanglestransitive
  have : CongA G H D D H G := by conclude lemma_ABCequalsCBA
  have : CongA H G P D H G := by conclude lemma_equalanglestransitive
  have : CongA H G A D H G := by conclude lemma_equalanglestransitive
  have : ¬ Col A G H := by
      intro h
      have : Col G H A := by forward_using lemma_collinearorder
      contradict
  have : CongA A G H H G A := by conclude lemma_ABCequalsCBA
  have : CongA A G H D H G := by conclude lemma_equalanglestransitive
  have : nCol D H G := by conclude lemma_equalanglesNC
  have : CongA D H G G H D := by conclude lemma_ABCequalsCBA
  have : CongA A G H G H D := by conclude lemma_equalanglestransitive
  have : BetS H G E := by conclude axiom_betweennesssymmetry
  have : CongA A G H E G B := by conclude proposition_15a
  have : CongA E G B A G H := by conclude lemma_equalanglessymmetric
  have : CongA E G B G H D := by conclude lemma_equalanglestransitive
  have : H = H := by conclude cn_equalityreflexive
  have : Out G H H := by conclude lemma_ray4
  have : Supp A G H H B := by conclude_def Supp
  have : ¬ Col B G H := by
      intro h
      have : Col A G B := by conclude_def Col
      have : Col B G A := by forward_using lemma_collinearorder
      have : G ≠ B := by forward_using lemma_betweennotequal
      have : B ≠ G := by conclude lemma_inequalitysymmetric
      have : Col G H A := by conclude lemma_collinear4
      have : Col A G H := by forward_using lemma_collinearorder
      contradict
  have : CongA B G H B G H := by conclude lemma_equalanglesreflexive
  have : CongA G H D A G H := by conclude lemma_equalanglessymmetric
  have : CongA A G H H G A := by conclude lemma_ABCequalsCBA
  have : CongA G H D H G A := by conclude lemma_equalanglestransitive
  have : Supp B G H H A := by conclude lemma_supplementsymmetric
  have : RT B G H G H D := by conclude_def RT
  close

end GeocoqTranslate.Elements
