/- Transpiled from ../theories/Elements/OriginalProofs/proposition_23.v :: proposition_23
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_TGsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_TGflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_23 :
    ∀ (A B C D E : Point), A ≠ B → nCol D C E → ∃ X Y, Out A B Y ∧ CongA X A Y D C E := by
  intro A B C D E h1 h2
  have : ¬ Col E C D := by
      intro h
      have : Col D C E := by forward_using lemma_collinearorder
      contradict
  have : ¬ Col C E D := by
      intro h
      have : Col D C E := by forward_using lemma_collinearorder
      contradict
  have : Triangle D C E := by conclude_def Triangle
  have : Triangle C E D := by conclude_def Triangle
  have : Triangle E C D := by conclude_def Triangle
  have : TG C D D E C E := by conclude proposition_20
  have : TG C E E D C D := by conclude proposition_20
  have : TG E C C D E D := by conclude proposition_20
  have : TG C D E C E D := by conclude lemma_TGsymmetric
  have : TG C D D E E C := by forward_using lemma_TGflip
  have : TG D E C D E C := by conclude lemma_TGsymmetric
  have : TG E D C D E C := by forward_using lemma_TGflip
  have : TG C D E D E C := by conclude lemma_TGsymmetric
  have : TG E C E D C D := by forward_using lemma_TGflip
  obtain ⟨G, F, _, _, _, _, _⟩ : ∃ G F, (Cong A G E C ∧ Cong A F C D ∧ Cong G F E D ∧ Out A B G ∧ Triangle A G F) := by conclude proposition_22
  have : Cong A G C E := by forward_using lemma_congruenceflip
  have : Cong F G D E := by forward_using lemma_congruenceflip
  have : E = E := by conclude cn_equalityreflexive
  have : D = D := by conclude cn_equalityreflexive
  have : F = F := by conclude cn_equalityreflexive
  have : G = G := by conclude cn_equalityreflexive
  have : ¬ C = E := by
      intro h
      have : Col D C E := by conclude_def Col
      contradict
  have : ¬ C = D := by
      intro h
      have : Col C D E := by conclude_def Col
      have : Col D C E := by forward_using lemma_collinearorder
      contradict
  have : Out C E E := by conclude lemma_ray4
  have : Out C D D := by conclude lemma_ray4
  have : ¬ Col F A G := by
      intro h
      have : Col A G F := by forward_using lemma_collinearorder
      have : nCol A G F := by conclude_def Triangle
      contradict
  have : ¬ A = F := by
      intro h
      have : Col A F G := by conclude_def Col
      have : Col F A G := by forward_using lemma_collinearorder
      contradict
  have : Out A F F := by conclude lemma_ray4
  have : ¬ A = G := by
      intro h
      have : Col A G F := by conclude_def Col
      have : Col F A G := by forward_using lemma_collinearorder
      contradict
  have : Out A G G := by conclude lemma_ray4
  have : CongA F A G D C E := by conclude_def CongA
  close

end GeocoqTranslate.Elements
