/- Transpiled from theories/Elements/OriginalProofs/proposition_35A.v :: proposition_35A
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_35helper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoffunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.proposition_29C
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_differenceofparts
import GeocoqTranslate.Elements.OriginalProofs.proposition_04
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearbetween
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ETreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_PGrotate
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_PGsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_PGflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trapezoiddiagonals
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_EFreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.proposition_34
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

set_option maxHeartbeats 800000 in
theorem proposition_35A :
    ∀ (A B C D E F : Point), PG A B C D → PG E B C F → BetS A D F → Col A E F → EF A B C D E B C F := by
  intro A B C D E F h1 h2 h3 h4
  have : (Par A B C D ∧ Par A D B C) := by conclude_def PG
  have : Par A B D C := by forward_using lemma_parallelflip
  have : Cong A D B C := by forward_using proposition_34
  have : Cong E F B C := by forward_using proposition_34
  have : Cong B C E F := by conclude lemma_congruencesymmetric
  have : Cong A D E F := by conclude lemma_congruencetransitive
  have : Cong E F F E := by conclude cn_equalityreverse
  have : Cong A D F E := by conclude lemma_congruencetransitive
  have : Cong A D A D := by conclude cn_congruencereflexive
  have : Lt A D A F := by conclude_def Lt
  have : Lt F E A F := by conclude lemma_lessthancongruence2
  have : Cong A F F A := by conclude cn_equalityreverse
  have : Lt F E F A := by conclude lemma_lessthancongruence
  obtain ⟨e, _, _⟩ : ∃ e, (BetS F e A ∧ Cong F e F E) := by conclude_def Lt
  have : F ≠ A := by forward_using lemma_betweennotequal
  have : Out F A e := by conclude lemma_ray4
  have : BetS A E F := by conclude lemma_35helper
  have : BetS F E A := by conclude axiom_betweennesssymmetry
  have : Out F A E := by conclude lemma_ray4
  have : e = E := by conclude lemma_layoffunique
  have : BetS F E A := by conclude cn_equalitysub
  have : BetS A E F := by conclude axiom_betweennesssymmetry
  have : Par D C A B := by conclude lemma_parallelsymmetric
  have : BetS F D A := by conclude axiom_betweennesssymmetry
  have : TP A D B C := by conclude lemma_paralleldef2B
  have : OS B C A D := by conclude_def TP
  have : OS C B D A := by forward_using lemma_samesidesymmetric
  have : CongA F D C D A B := by conclude proposition_29C
  have : D = D := by conclude cn_equalityreflexive
  have : C = C := by conclude cn_equalityreflexive
  have : B = B := by conclude cn_equalityreflexive
  have : A = A := by conclude cn_equalityreflexive
  have : nCol A D C := by forward_using lemma_parallelNC
  have : ¬ A = D := by
      intro h
      have : Col A D C := by conclude_def Col
      contradict
  have : A ≠ D := by forward_using lemma_betweennotequal
  have : nCol A B C := by forward_using lemma_parallelNC
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : Out A B B := by conclude lemma_ray4
  have : ¬ ¬ (BetS A D E ∨ BetS A E D ∨ D = E) := by
      intro h
      have : ¬ (BetS A D E) := fun c => h (Or.inl c)
      have : ¬ (BetS A E D) := fun c => h (Or.inr (Or.inl c))
      have : ¬ (D = E) := fun c => h (Or.inr (Or.inr (c)))
      have : D = E := by conclude axiom_connectivity
      contradict
  have : Out A D E := by
      rcases (show BetS A D E ∨ BetS A E D ∨ D = E by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · have : Out A D E := by conclude lemma_ray4
        close
      · have : Out A D E := by conclude lemma_ray4
        close
      · have : Out A D D := by conclude lemma_ray4
        have : Out A D E := by conclude cn_equalitysub
        close
  have : nCol A D B := by forward_using lemma_parallelNC
  have : nCol D A B := by perm_close
  have : CongA D A B D A B := by conclude lemma_equalanglesreflexive
  have : CongA D A B E A B := by conclude lemma_equalangleshelper
  have : CongA F D C E A B := by conclude lemma_equalanglestransitive
  have : Cong A B D C := by forward_using proposition_34
  have : Cong D E E D := by conclude cn_equalityreverse
  have : Cong A E D F := by
      rcases (show BetS A D E ∨ BetS A E D ∨ D = E by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · have : BetS D E F := by conclude lemma_3_6a
        have : BetS F E D := by conclude axiom_betweennesssymmetry
        have : Cong A E F D := by conclude cn_sumofparts
        have : Cong A E D F := by forward_using lemma_congruenceflip
        close
      · have : BetS D E A := by conclude axiom_betweennesssymmetry
        have : BetS E D F := by conclude lemma_3_6a
        have : Cong D A E F := by forward_using lemma_congruenceflip
        have : Cong E A D F := by conclude lemma_differenceofparts
        have : Cong A E D F := by forward_using lemma_congruenceflip
        close
      · have : Cong A E E F := by conclude cn_equalitysub
        have : Cong A E D F := by conclude cn_equalitysub
        close
  have : Cong D F A E := by conclude lemma_congruencesymmetric
  have : Cong D C A B := by conclude lemma_congruencesymmetric
  have : (Cong F C E B ∧ CongA D F C A E B ∧ CongA D C F A B E) := by conclude proposition_04
  have : Cong F D E A := by forward_using lemma_congruenceflip
  have : CongA A B E D C F := by conclude lemma_equalanglessymmetric
  have : nCol D C F := by conclude lemma_equalanglesNC
  have : nCol F D C := by perm_close
  have : Triangle F D C := by (try (have : nCol F D C := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Cong_3 F D C E A B := by conclude_def Cong_3
  have : ET F D C E A B := by conclude axiom_congruentequal
  have : EF A B C D E B C F := by
      rcases (show BetS A D E ∨ BetS A E D ∨ D = E by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · obtain ⟨M, _, _⟩ : ∃ M, (BetS A M C ∧ BetS B M D) := by conclude lemma_diagonalsmeet
        have : BetS D M B := by conclude axiom_betweennesssymmetry
        have : nCol A D B := by forward_using lemma_parallelNC
        have : Col A D E := by conclude_def Col
        have : Col A D A := by conclude_def Col
        have : A ≠ E := by forward_using lemma_betweennotequal
        have : nCol A E B := by conclude lemma_NChelper
        have : BetS B M D := by conclude axiom_betweennesssymmetry
        obtain ⟨H, _, _⟩ : ∃ H, (BetS B H E ∧ BetS A M H) := by conclude postulate_Pasch_outer
        have : Col A M H := by conclude_def Col
        have : Col A M C := by conclude_def Col
        have : A ≠ M := by forward_using lemma_betweennotequal
        have : M ≠ A := by conclude lemma_inequalitysymmetric
        have : Col M A H := by perm_close
        have : Col M A C := by perm_close
        have : Col A H C := by conclude lemma_collinear4
        have : BetS E H B := by conclude axiom_betweennesssymmetry
        have : E ≠ A := by conclude lemma_inequalitysymmetric
        have : ¬ B = C := by
            intro h
            have : Col A B C := by conclude_def Col
            contradict
        have : ¬ Meet A D B C := by conclude_def Par
        have : ¬ Meet E A C B := by
            intro h
            obtain ⟨q, _, _, _, _⟩ : ∃ q, (E ≠ A ∧ C ≠ B ∧ Col E A q ∧ Col C B q) := by conclude_def Meet
            have : B ≠ C := by conclude lemma_inequalitysymmetric
            have : Col B C q := by perm_close
            have : Col A E q := by perm_close
            have : Col A D E := by conclude_def Col
            have : Col E A D := by perm_close
            have : Col E A q := by perm_close
            have : A ≠ D := by forward_using lemma_betweennotequal
            have : Col A D q := by conclude lemma_collinear4
            have : Meet A D B C := by conclude_def Meet
            contradict
        have : Col A C H := by perm_close
        have : Col E A A := by conclude_def Col
        have : Col C C B := by conclude_def Col
        have : C ≠ B := by conclude lemma_inequalitysymmetric
        have : BetS A H C := by conclude lemma_collinearbetween
        have : BetS C H A := by conclude axiom_betweennesssymmetry
        have : BetS E D A := by conclude axiom_betweennesssymmetry
        have : nCol A D C := by forward_using lemma_parallelNC
        have : Col A D E := by conclude_def Col
        have : nCol A E C := by conclude lemma_NChelper
        have : nCol C A E := by perm_close
        obtain ⟨G, _, _⟩ : ∃ G, (BetS C G D ∧ BetS E G H) := by conclude postulate_Pasch_inner
        have : BetS E G B := by conclude lemma_3_6b
        have : BetS E G B := by conclude lemma_3_6b
        have : Col E G B := by conclude_def Col
        have : ¬ Col D E G := by
            intro h
            have : Col G E D := by perm_close
            have : Col G E B := by perm_close
            have : E ≠ G := by forward_using lemma_betweennotequal
            have : G ≠ E := by conclude lemma_inequalitysymmetric
            have : Col E D B := by conclude lemma_collinear4
            have : Col B C B := by conclude_def Col
            have : Col E D A := by perm_close
            have : Col E D D := by conclude_def Col
            have : D ≠ E := by forward_using lemma_betweennotequal
            have : E ≠ D := by conclude lemma_inequalitysymmetric
            have : Col A D B := by conclude lemma_collinear5
            have : Meet A D B C := by conclude_def Meet
            contradict
        have : Triangle D E G := by (try (have : nCol D E G := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
        have : ET D E G D E G := by conclude lemma_ETreflexive
        have : ET D E G E D G := by forward_using axiom_ETpermutation
        have : ET F D C A E B := by forward_using axiom_ETpermutation
        have : ET A E B F D C := by conclude axiom_ETsymmetric
        have : BetS B G E := by conclude axiom_betweennesssymmetry
        have : BetS D E F := by conclude lemma_3_6a
        have : BetS F E D := by conclude axiom_betweennesssymmetry
        have : EF A D G B F E G C := by conclude axiom_cutoff1
        have : nCol E G D := by perm_close
        have : G = G := by conclude cn_equalityreflexive
        have : Col E G G := by conclude_def Col
        have : G ≠ B := by forward_using lemma_betweennotequal
        have : B ≠ G := by conclude lemma_inequalitysymmetric
        have : nCol B G D := by conclude lemma_NChelper
        have : nCol D G B := by perm_close
        have : Col C G D := by conclude_def Col
        have : Col D G C := by perm_close
        have : Col D G G := by conclude_def Col
        have : C ≠ G := by forward_using lemma_betweennotequal
        have : nCol C G B := by conclude lemma_NChelper
        have : nCol G C B := by perm_close
        have : Triangle G C B := by (try (have : nCol G C B := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
        have : ET G C B G C B := by conclude lemma_ETreflexive
        have : ET G C B G B C := by forward_using axiom_ETpermutation
        have : BetS D G C := by conclude axiom_betweennesssymmetry
        have : PG B C D A := by conclude lemma_PGrotate
        have : PG D A B C := by conclude lemma_PGsymmetric
        have : PG A D C B := by conclude lemma_PGflip
        obtain ⟨q, _, _⟩ : ∃ q, (BetS A q C ∧ BetS D q B) := by conclude lemma_diagonalsmeet
        have : PG B C F E := by conclude lemma_PGrotate
        have : PG C F E B := by conclude lemma_PGrotate
        have : PG F E B C := by conclude lemma_PGrotate
        obtain ⟨m, _, _⟩ : ∃ m, (BetS F m B ∧ BetS E m C) := by conclude lemma_diagonalsmeet
        have : EF A D C B F E B C := by conclude axiom_paste2
        have : EF A D C B E B C F := by forward_using axiom_EFpermutation
        have : EF E B C F A D C B := by conclude axiom_EFsymmetric
        have : EF E B C F A B C D := by forward_using axiom_EFpermutation
        have : EF A B C D E B C F := by conclude axiom_EFsymmetric
        close
      · have : ET E A B F D C := by conclude axiom_ETsymmetric
        have : ET E A B D F C := by forward_using axiom_ETpermutation
        obtain ⟨H, _, _⟩ : ∃ H, (BetS B H D ∧ BetS C H E) := by conclude lemma_trapezoiddiagonals
        have : BetS E H C := by conclude axiom_betweennesssymmetry
        have : ¬ Col B E D := by
            intro h
            have : Col A E D := by conclude_def Col
            have : Col E D A := by perm_close
            have : Col E D B := by perm_close
            have : E ≠ D := by forward_using lemma_betweennotequal
            have : Col D A B := by conclude lemma_collinear4
            have : Col A D B := by perm_close
            have : B = B := by conclude cn_equalityreflexive
            have : Col B C B := by conclude_def Col
            have : A ≠ D := by conclude_def Par
            have : B ≠ C := by conclude_def Par
            have : Meet A D B C := by conclude_def Meet
            have : ¬ Meet A D B C := by conclude_def Par
            contradict
        have : EF B E D C B E D C := by conclude lemma_EFreflexive
        have : EF B E D C C D E B := by forward_using axiom_EFpermutation
        have : EF C D E B B E D C := by conclude axiom_EFsymmetric
        have : BetS D E A := by conclude axiom_betweennesssymmetry
        have : BetS E D F := by conclude lemma_3_6a
        have : PG C D A B := by conclude lemma_PGsymmetric
        obtain ⟨p, _, _⟩ : ∃ p, (BetS C p A ∧ BetS D p B) := by conclude lemma_diagonalsmeet
        have : PG B E F C := by conclude lemma_PGflip
        obtain ⟨m, _, _⟩ : ∃ m, (BetS B m F ∧ BetS E m C) := by conclude lemma_diagonalsmeet
        have : EF C D A B B E F C := by conclude axiom_paste2
        have : EF C D A B E B C F := by forward_using axiom_EFpermutation
        have : EF E B C F C D A B := by conclude axiom_EFsymmetric
        have : EF E B C F A B C D := by forward_using axiom_EFpermutation
        have : EF A B C D E B C F := by conclude axiom_EFsymmetric
        close
      · have : ET F D C B E A := by forward_using axiom_ETpermutation
        have : ET B E A F D C := by conclude axiom_ETsymmetric
        have : ET B E A C D F := by forward_using axiom_ETpermutation
        have : nCol D B C := by forward_using lemma_parallelNC
        have : nCol E B C := by conclude cn_equalitysub
        have : nCol B E C := by perm_close
        have : Triangle B E C := by (try (have : nCol B E C := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
        have : ET B E C B E C := by conclude lemma_ETreflexive
        have : ET B E C C E B := by forward_using axiom_ETpermutation
        have : ET B E C C D B := by conclude cn_equalitysub
        have : PG A B C E := by conclude cn_equalitysub
        obtain ⟨M, _, _⟩ : ∃ M, (BetS A M C ∧ BetS B M E) := by conclude lemma_diagonalsmeet
        have : BetS E M B := by conclude axiom_betweennesssymmetry
        have : Col E M B := by conclude_def Col
        have : Col B E M := by perm_close
        have : Par A E B C := by conclude_def PG
        have : nCol A E B := by forward_using lemma_parallelNC
        have : nCol B E A := by perm_close
        have : TS A B E C := by (try (have : nCol B E A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
        have : PG D B C F := by conclude cn_equalitysub
        have : nCol C D F := by perm_close
        obtain ⟨m, _, _⟩ : ∃ m, (BetS D m C ∧ BetS B m F) := by conclude lemma_diagonalsmeet
        have : BetS F m B := by conclude axiom_betweennesssymmetry
        have : Col D m C := by conclude_def Col
        have : Col C D m := by perm_close
        have : TS F C D B := by (try (have : nCol C D F := nCol_notCol _ _ _ (by assumption))); conclude_def TS
        obtain ⟨J, _, _⟩ : ∃ J, (BetS A J C ∧ BetS B J D) := by conclude lemma_diagonalsmeet
        have : BetS B J E := by conclude cn_equalitysub
        obtain ⟨j, _, _⟩ : ∃ j, (BetS E j C ∧ BetS B j F) := by conclude lemma_diagonalsmeet
        have : BetS D j C := by conclude cn_equalitysub
        have : BetS C j D := by conclude axiom_betweennesssymmetry
        have : BetS F j B := by conclude axiom_betweennesssymmetry
        have : EF B A E C C F D B := by conclude axiom_paste3
        have : EF B A E C D B C F := by forward_using axiom_EFpermutation
        have : EF B A E C E B C F := by conclude cn_equalitysub
        have : EF E B C F B A E C := by conclude axiom_EFsymmetric
        have : EF E B C F A B C E := by forward_using axiom_EFpermutation
        have : EF E B C F A B C D := by conclude cn_equalitysub
        have : EF A B C D E B C F := by conclude axiom_EFsymmetric
        close
  close

end GeocoqTranslate.Elements
