/- Transpiled from ../theories/Elements/OriginalProofs/proposition_06.v :: proposition_06
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.proposition_06a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem proposition_06 :
    ∀ (A B C : Point), Triangle A B C → CongA A B C A C B → Cong A B A C := by
  intro A B C h1 h2
  have : ¬ Lt A C A B := by conclude proposition_06a
  have : nCol A B C := by conclude_def Triangle
  have : ¬ Col A C B := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  have : Triangle A C B := by (try (have : nCol A C B := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : CongA A C B A B C := by conclude lemma_equalanglessymmetric
  have : ¬ Lt A B A C := by conclude proposition_06a
  have : A ≠ B := by forward_using lemma_angledistinct
  have : A ≠ C := by forward_using lemma_angledistinct
  have : Cong A B A C := by conclude lemma_trichotomy1
  close

end GeocoqTranslate.Elements
