/- Transpiled from ../theories/Elements/OriginalProofs/proposition_13.v :: proposition_13
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_13 :
    ∀ (A B C D : Point), BetS D B C → nCol A B C → RT C B A A B D := by
  intro A B C D h1 h2
  have : A = A := by conclude cn_equalityreflexive
  have : B ≠ A := by forward_using lemma_NCdistinct
  have : Out B A A := by conclude lemma_ray4
  have : BetS C B D := by conclude axiom_betweennesssymmetry
  have : Supp C B A A D := by conclude_def Supp
  have : nCol C B A := by forward_using lemma_NCorder
  have : Col D B C := by conclude_def Col
  have : Col C B D := by forward_using lemma_collinearorder
  have : B = B := by conclude cn_equalityreflexive
  have : Col C B B := by conclude_def Col
  have : D ≠ B := by forward_using lemma_betweennotequal
  have : nCol D B A := by conclude lemma_NChelper
  have : nCol A B D := by forward_using lemma_NCorder
  have : CongA A B D A B D := by conclude lemma_equalanglesreflexive
  have : CongA C B A C B A := by conclude lemma_equalanglesreflexive
  have : RT C B A A B D := by conclude_def RT
  close

end GeocoqTranslate.Elements
