/- Transpiled from ../theories/Elements/OriginalProofs/proposition_48A.v :: proposition_48A
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_squareparallelogram
import GeocoqTranslate.Elements.OriginalProofs.proposition_34
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_squarerectangle
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equaltorightisright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_Euclid4
import GeocoqTranslate.Elements.OriginalProofs.proposition_04
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crossimpliesopposite
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

set_option maxHeartbeats 800000 in
theorem proposition_48A :
    ∀ (A B C D a b c d : Point), SQ A B C D → SQ a b c d → EF A B C D a b c d → Cong A B a b := by
  intro A B C D a b c d h1 h2 h3
  have : PG A B C D := by conclude lemma_squareparallelogram
  have : PG a b c d := by conclude lemma_squareparallelogram
  have : Cong_3 B A D D C B := by conclude proposition_34
  have : Cong_3 b a d d c b := by conclude proposition_34
  have : ET B A D D C B := by conclude axiom_congruentequal
  have : ET b a d d c b := by conclude axiom_congruentequal
  have : ET B A D B D C := by forward_using axiom_ETpermutation
  have : ET B D C B A D := by conclude axiom_ETsymmetric
  have : ET B D C A B D := by forward_using axiom_ETpermutation
  have : ET A B D B D C := by conclude axiom_ETsymmetric
  have : ET b a d b d c := by forward_using axiom_ETpermutation
  have : ET b d c b a d := by conclude axiom_ETsymmetric
  have : ET b d c a b d := by forward_using axiom_ETpermutation
  have : ET a b d b d c := by conclude axiom_ETsymmetric
  have : RE A B C D := by conclude lemma_squarerectangle
  have : RE a b c d := by conclude lemma_squarerectangle
  have : CR A C B D := by conclude_def RE
  have : CR a c b d := by conclude_def RE
  have : Par A B C D := by conclude_def PG
  have : nCol A B D := by forward_using lemma_parallelNC
  have : Par a b c d := by conclude_def PG
  have : nCol a b d := by forward_using lemma_parallelNC
  have : TS A B D C := by forward_using lemma_crossimpliesopposite
  have : TS a b d c := by forward_using lemma_crossimpliesopposite
  have : ET A B D a b d := by conclude axiom_halvesofequals
  have : Cong a b d a := by conclude_def SQ
  have : Cong A B D A := by conclude_def SQ
  have : Cong a b a d := by forward_using lemma_congruenceflip
  have : Cong A B A D := by forward_using lemma_congruenceflip
  have : ¬ Lt a b A B := by
      intro h
      obtain ⟨E, _, _⟩ : ∃ E, (BetS A E B ∧ Cong A E a b) := by conclude_def Lt
      have : Lt a d A B := by conclude lemma_lessthancongruence2
      have : Lt a d A D := by conclude lemma_lessthancongruence
      obtain ⟨F, _, _⟩ : ∃ F, (BetS A F D ∧ Cong A F a d) := by conclude_def Lt
      have : Per D A B := by conclude_def SQ
      have : Per d a b := by conclude_def SQ
      have : A ≠ D := by forward_using lemma_betweennotequal
      have : A ≠ B := by forward_using lemma_betweennotequal
      have : Out A D F := by conclude lemma_ray4
      have : Out A B E := by conclude lemma_ray4
      have : nCol D A B := by perm_close
      have : CongA D A B D A B := by conclude lemma_equalanglesreflexive
      have : CongA D A B F A E := by conclude lemma_equalangleshelper
      have : CongA F A E D A B := by conclude lemma_equalanglessymmetric
      have : Per F A E := by conclude lemma_equaltorightisright
      have : CongA F A E d a b := by conclude lemma_Euclid4
      have : Cong F E d b := by conclude proposition_04
      have : Cong F A d a := by forward_using lemma_congruenceflip
      have : Cong_3 F A E d a b := by conclude_def Cong_3
      have : ET F A E d a b := by conclude axiom_congruentequal
      have : ET F A E a b d := by forward_using axiom_ETpermutation
      have : ET a b d A B D := by conclude axiom_ETsymmetric
      have : ET F A E A B D := by conclude axiom_ETtransitive
      have : ET F A E D A B := by forward_using axiom_ETpermutation
      have : ET D A B F A E := by conclude axiom_ETsymmetric
      have : Triangle D A B := by (try (have : nCol D A B := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
      have : ¬ ET D A B F A E := by conclude axiom_deZolt2
      contradict
  have : ¬ Lt A B a b := by
      intro h
      obtain ⟨e, _, _⟩ : ∃ e, (BetS a e b ∧ Cong a e A B) := by conclude_def Lt
      have : Lt A D a b := by conclude lemma_lessthancongruence2
      have : Lt A D a d := by conclude lemma_lessthancongruence
      obtain ⟨f, _, _⟩ : ∃ f, (BetS a f d ∧ Cong a f A D) := by conclude_def Lt
      have : Per d a b := by conclude_def SQ
      have : Per D A B := by conclude_def SQ
      have : a ≠ d := by forward_using lemma_betweennotequal
      have : a ≠ b := by forward_using lemma_betweennotequal
      have : Out a d f := by conclude lemma_ray4
      have : Out a b e := by conclude lemma_ray4
      have : nCol d a b := by perm_close
      have : CongA d a b d a b := by conclude lemma_equalanglesreflexive
      have : CongA d a b f a e := by conclude lemma_equalangleshelper
      have : CongA f a e d a b := by conclude lemma_equalanglessymmetric
      have : Per f a e := by conclude lemma_equaltorightisright
      have : CongA f a e D A B := by conclude lemma_Euclid4
      have : Cong f e D B := by conclude proposition_04
      have : Cong f a D A := by forward_using lemma_congruenceflip
      have : Cong_3 f a e D A B := by conclude_def Cong_3
      have : ET f a e D A B := by conclude axiom_congruentequal
      have : ET f a e A B D := by forward_using axiom_ETpermutation
      have : ET A B D f a e := by conclude axiom_ETsymmetric
      have : ET f a e a b d := by conclude axiom_ETtransitive
      have : ET f a e d a b := by forward_using axiom_ETpermutation
      have : ET d a b f a e := by conclude axiom_ETsymmetric
      have : Triangle d a b := by (try (have : nCol d a b := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
      have : ¬ ET d a b f a e := by conclude axiom_deZolt2
      contradict
  have : A ≠ B := by forward_using lemma_NCdistinct
  have : a ≠ b := by forward_using lemma_NCdistinct
  have : Cong A B a b := by conclude lemma_trichotomy1
  close

end GeocoqTranslate.Elements
