/- Transpiled from theories/Elements/OriginalProofs/proposition_34.v :: proposition_34
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.proposition_29B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.proposition_26A
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

set_option maxHeartbeats 800000 in
theorem proposition_34 :
    ∀ (A B C D : Point), PG A C D B → Cong A B C D ∧ Cong A C B D ∧ CongA C A B B D C ∧ CongA A B D D C A ∧ Cong_3 C A B B D C := by
  intro A B C D h1
  have : (Par A C D B ∧ Par A B C D) := by conclude_def PG
  have : Par A C B D := by forward_using lemma_parallelflip
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M D ∧ BetS C M B) := by conclude lemma_diagonalsmeet
  have : BetS B M C := by conclude axiom_betweennesssymmetry
  have : Col B M C := by conclude_def Col
  have : Col B C M := by forward_using lemma_collinearorder
  have : ¬ Meet A B C D := by conclude_def Par
  have : A ≠ B := by conclude_def Par
  have : C ≠ D := by conclude_def Par
  have : ¬ Col B C A := by
      intro h
      have : Col A B C := by forward_using lemma_collinearorder
      have : C = C := by conclude cn_equalityreflexive
      have : Col C D C := by conclude_def Col
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : TS A B C D := by (try (have : nCol B C A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
  have : CongA A B C B C D := by conclude proposition_29B
  have : ¬ Col B C D := by
      intro h
      have : Col C D B := by forward_using lemma_collinearorder
      have : B = B := by conclude cn_equalityreflexive
      have : Col A B B := by conclude_def Col
      have : Meet A B C D := by conclude_def Meet
      have : ¬ Meet A B C D := by conclude_def Par
      contradict
  have : CongA B C D D C B := by conclude lemma_ABCequalsCBA
  have : CongA A B C D C B := by conclude lemma_equalanglestransitive
  have : Col C B M := by forward_using lemma_collinearorder
  have : nCol C B A := by
      have : nCol B C A := by close
      forward_using lemma_NCorder
  have : TS A C B D := by (try (have : nCol C B A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
  have : CongA A C B C B D := by conclude proposition_29B
  have : nCol A B C := by forward_using lemma_NCorder
  have : CongA B C A A C B := by conclude lemma_ABCequalsCBA
  have : CongA B C A C B D := by conclude lemma_equalanglestransitive
  have : Triangle A B C := by (try (have : nCol A B C := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : nCol D C B := by conclude lemma_equalanglesNC
  have : Triangle D C B := by (try (have : nCol D C B := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Cong B C C B := by conclude cn_equalityreverse
  have : (Cong A B D C ∧ Cong A C D B ∧ CongA B A C C D B) := by conclude proposition_26A
  have : Cong A B C D := by forward_using lemma_congruenceflip
  have : Cong A C B D := by forward_using lemma_congruenceflip
  have : Cong C A B D := by forward_using lemma_congruenceflip
  have : Cong C B B C := by conclude cn_equalityreverse
  have : Cong_3 C A B B D C := by conclude_def Cong_3
  have : CongA C A B B D C := by conclude lemma_equalanglesflip
  have : Cong A D D A := by conclude cn_equalityreverse
  have : A = A := by conclude cn_equalityreflexive
  have : D = D := by conclude cn_equalityreflexive
  have : A ≠ C := by forward_using lemma_angledistinct
  have : C ≠ A := by conclude lemma_inequalitysymmetric
  have : C ≠ D := by forward_using lemma_angledistinct
  have : B ≠ A := by forward_using lemma_angledistinct
  have : D ≠ B := by forward_using lemma_angledistinct
  have : B ≠ D := by conclude lemma_inequalitysymmetric
  have : Out C A A := by conclude lemma_ray4
  have : Out C D D := by conclude lemma_ray4
  have : Out B A A := by conclude lemma_ray4
  have : Out B D D := by conclude lemma_ray4
  have : Cong B A C D := by forward_using lemma_congruenceflip
  have : Cong C A B D := by forward_using lemma_congruenceflip
  have : Cong B D C A := by conclude lemma_congruencesymmetric
  have : ¬ Col A B D := by
      intro h
      have : D = D := by conclude cn_equalityreflexive
      have : Col C D D := by conclude_def Col
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : CongA A B D D C A := by (try (have : nCol A B D := nCol_notCol _ _ _ (by assumption))); conclude_def CongA
  close

end GeocoqTranslate.Elements
