/- Transpiled from ../theories/Elements/OriginalProofs/proposition_28D.v :: proposition_28D
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem proposition_28D :
    ∀ (B D E G H : Point), BetS E G H → CongA E G B G H D → OS B D G H → Par G B H D := by
  intro B D E G H h1 h2 h3
  have : nCol G H B := by conclude_def OS
  have : nCol G H D := by conclude_def OS
  have : H ≠ D := by forward_using lemma_NCdistinct
  have : D ≠ H := by conclude lemma_inequalitysymmetric
  have : G ≠ B := by forward_using lemma_NCdistinct
  have : B ≠ G := by conclude lemma_inequalitysymmetric
  obtain ⟨A, _, _⟩ : ∃ A, (BetS B G A ∧ Cong G A G B) := by conclude lemma_extension
  have : BetS A G B := by conclude axiom_betweennesssymmetry
  obtain ⟨C, _, _⟩ : ∃ C, (BetS D H C ∧ Cong H C H D) := by conclude lemma_extension
  have : BetS C H D := by conclude axiom_betweennesssymmetry
  have : Par A B C D := by conclude proposition_28A
  have : Col D H C := by conclude_def Col
  have : Col C D H := by forward_using lemma_collinearorder
  have : H ≠ D := by forward_using lemma_NCdistinct
  have : Par A B H D := by conclude lemma_collinearparallel
  have : Par H D A B := by conclude lemma_parallelsymmetric
  have : Col B G A := by conclude_def Col
  have : Col A B G := by forward_using lemma_collinearorder
  have : Par H D G B := by conclude lemma_collinearparallel
  have : Par G B H D := by conclude lemma_parallelsymmetric
  close

end GeocoqTranslate.Elements
