/- Transpiled from ../theories/Elements/OriginalProofs/proposition_27B.v :: proposition_27B
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.proposition_27
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem proposition_27B :
    ∀ (A D E F : Point), CongA A E F E F D → TS A E F D → Par A E F D := by
  intro A D E F h1 h2
  have : A ≠ E := by forward_using lemma_angledistinct
  obtain ⟨B, _, _⟩ : ∃ B, (BetS A E B ∧ Cong E B A E) := by conclude lemma_extension
  have : F ≠ D := by forward_using lemma_angledistinct
  have : D ≠ F := by conclude lemma_inequalitysymmetric
  obtain ⟨C, _, _⟩ : ∃ C, (BetS D F C ∧ Cong F C F D) := by conclude lemma_extension
  have : BetS C F D := by conclude axiom_betweennesssymmetry
  have : Par A B C D := by conclude proposition_27
  have : Col D F C := by conclude_def Col
  have : Col C D F := by perm_close
  have : Par A B F D := by conclude lemma_collinearparallel
  have : Par F D A B := by conclude lemma_parallelsymmetric
  have : Par F D B A := by forward_using lemma_parallelflip
  have : Col A E B := by conclude_def Col
  have : Col B A E := by perm_close
  have : A ≠ E := by forward_using lemma_betweennotequal
  have : E ≠ A := by conclude lemma_inequalitysymmetric
  have : Par F D E A := by conclude lemma_collinearparallel
  have : Par F D A E := by forward_using lemma_parallelflip
  have : Par A E F D := by conclude lemma_parallelsymmetric
  close

end GeocoqTranslate.Elements
