/- Transpiled from ../theories/Elements/OriginalProofs/proposition_35.v :: proposition_35
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelPasch
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_planeseparation
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_EFreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthantransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

theorem proposition_35 :
    ∀ (A B C D E F : Point), PG A B C D → PG E B C F → Col A D E → Col A D F → EF A B C D E B C F := by
  intro A B C D E F h1 h2 h3 h4
  have : (Par A B C D ∧ Par A D B C) := by conclude_def PG
  have : (Par E B C F ∧ Par E F B C) := by conclude_def PG
  have : Par A B D C := by forward_using lemma_parallelflip
  have : Par E B F C := by forward_using lemma_parallelflip
  have : Par F C E B := by conclude lemma_parallelsymmetric
  have : Cong A D B C := by forward_using proposition_34
  have : Cong E F B C := by forward_using proposition_34
  have : Cong B C E F := by conclude lemma_congruencesymmetric
  have : Cong A D E F := by conclude lemma_congruencetransitive
  have : A ≠ D := by conclude_def Par
  have : E ≠ F := by conclude_def Par
  have : D ≠ A := by conclude lemma_inequalitysymmetric
  have : ¬ ¬ EF A B C D E B C F := by
      intro h
      have : ¬ BetS A D F := by
          intro h
          have : Col A D F := by conclude_def Col
          have : Col D A F := by forward_using lemma_collinearorder
          have : Col D A E := by forward_using lemma_collinearorder
          have : Col A F E := by conclude lemma_collinear4
          have : Col A E F := by forward_using lemma_collinearorder
          have : EF A B C D E B C F := by conclude proposition_35A
          contradict
      have : ¬ BetS A D E := by
          intro h
          obtain ⟨H, _, _⟩ : ∃ H, (BetS B H E ∧ BetS C H D) := by conclude lemma_parallelPasch
          have : BetS D H C := by conclude axiom_betweennesssymmetry
          have : Col B H E := by conclude_def Col
          have : Col B E H := by forward_using lemma_collinearorder
          have : nCol A D B := by forward_using lemma_parallelNC
          have : Col A D E := by conclude_def Col
          have : D = D := by conclude cn_equalityreflexive
          have : Col A D D := by conclude_def Col
          have : D ≠ E := by forward_using lemma_betweennotequal
          have : nCol D E B := by conclude lemma_NChelper
          have : nCol B E D := by forward_using lemma_NCorder
          have : TS D B E C := by conclude_def TS
          have : TS C B E D := by conclude lemma_oppositesidesymmetric
          have : Par F C B E := by forward_using lemma_parallelflip
          have : Par B E F C := by conclude lemma_parallelsymmetric
          have : TP B E F C := by conclude lemma_paralleldef2B
          have : OS F C B E := by conclude_def TP
          have : TS F B E D := by conclude lemma_planeseparation
          obtain ⟨e, _, _, _⟩ : ∃ e, (BetS F e D ∧ Col B E e ∧ nCol B E F) := by conclude_def TS
          have : F ≠ D := by forward_using lemma_betweennotequal
          have : Col F e D := by conclude_def Col
          have : ¬ e ≠ E := by
              intro h
              have : A ≠ D := by forward_using lemma_betweennotequal
              have : Col D E F := by conclude lemma_collinear4
              have : Col F D E := by forward_using lemma_collinearorder
              have : Col F D e := by forward_using lemma_collinearorder
              have : Col D E e := by conclude lemma_collinear4
              have : Col e E D := by forward_using lemma_collinearorder
              have : Col e E B := by forward_using lemma_collinearorder
              have : Col E D B := by conclude lemma_collinear4
              have : Col B E D := by forward_using lemma_collinearorder
              contradict
          have : BetS F E D := by conclude cn_equalitysub
          have : BetS D E F := by conclude axiom_betweennesssymmetry
          have : BetS A D F := by conclude lemma_3_7b
          contradict
      have : Par B A D C := by forward_using lemma_parallelflip
      have : Par D C B A := by conclude lemma_parallelsymmetric
      have : Par D A C B := by forward_using lemma_parallelflip
      have : PG D C B A := by conclude_def PG
      have : Par B E F C := by forward_using lemma_parallelflip
      have : Par F C B E := by conclude lemma_parallelsymmetric
      have : Par F E C B := by forward_using lemma_parallelflip
      have : PG F C B E := by conclude_def PG
      have : ¬ BetS E A D := by
          intro h
          have : BetS D A E := by conclude axiom_betweennesssymmetry
          have : Col D A E := by conclude_def Col
          have : Col A D E := by forward_using lemma_collinearorder
          have : A ≠ D := by forward_using lemma_betweennotequal
          have : Col D E F := by conclude lemma_collinear4
          have : Col D F E := by forward_using lemma_collinearorder
          have : EF D C B A F C B E := by conclude proposition_35A
          have : EF D C B A E B C F := by forward_using axiom_EFpermutation
          have : EF E B C F D C B A := by conclude axiom_EFsymmetric
          have : EF E B C F A B C D := by forward_using axiom_EFpermutation
          have : EF A B C D E B C F := by conclude axiom_EFsymmetric
          contradict
      have : ¬ BetS D A F := by
          intro h
          obtain ⟨H, _, _⟩ : ∃ H, (BetS C H F ∧ BetS B H A) := by conclude lemma_parallelPasch
          have : BetS A H B := by conclude axiom_betweennesssymmetry
          have : Col C H F := by conclude_def Col
          have : Col C F H := by forward_using lemma_collinearorder
          have : nCol D A C := by forward_using lemma_parallelNC
          have : Col D A F := by conclude_def Col
          have : A = A := by conclude cn_equalityreflexive
          have : Col D A A := by conclude_def Col
          have : A ≠ F := by forward_using lemma_betweennotequal
          have : nCol A F C := by conclude lemma_NChelper
          have : nCol C F A := by forward_using lemma_NCorder
          have : TS A C F B := by conclude_def TS
          have : TS B C F A := by conclude lemma_oppositesidesymmetric
          have : Par E B C F := by forward_using lemma_parallelflip
          have : Par C F E B := by conclude lemma_parallelsymmetric
          have : TP C F E B := by conclude lemma_paralleldef2B
          have : OS E B C F := by conclude_def TP
          have : TS E C F A := by conclude lemma_planeseparation
          obtain ⟨e, _, _, _⟩ : ∃ e, (BetS E e A ∧ Col C F e ∧ nCol C F E) := by conclude_def TS
          have : E ≠ A := by forward_using lemma_betweennotequal
          have : ¬ e ≠ F := by
              intro h
              have : Col D A E := by forward_using lemma_collinearorder
              have : D ≠ A := by forward_using lemma_betweennotequal
              have : Col A F E := by conclude lemma_collinear4
              have : Col E A F := by forward_using lemma_collinearorder
              have : Col E e A := by conclude_def Col
              have : Col E A e := by forward_using lemma_collinearorder
              have : Col A F e := by conclude lemma_collinear4
              have : Col e F A := by forward_using lemma_collinearorder
              have : Col e F C := by forward_using lemma_collinearorder
              have : Col F A C := by conclude lemma_collinear4
              have : Col C F A := by forward_using lemma_collinearorder
              contradict
          have : BetS E F A := by conclude cn_equalitysub
          have : BetS A F E := by conclude axiom_betweennesssymmetry
          have : BetS D A E := by conclude lemma_3_7b
          have : BetS E A D := by conclude axiom_betweennesssymmetry
          contradict
      have : (A = D ∨ A = F ∨ D = F ∨ BetS D A F ∨ BetS A D F ∨ BetS A F D) := by conclude_def Col
      have : (A = D ∨ A = E ∨ D = E ∨ BetS D A E ∨ BetS A D E ∨ BetS A E D) := by conclude_def Col
      have : ¬ A = F := by
          intro h
          have : (F = D ∨ F = E ∨ D = E ∨ BetS D A E ∨ BetS A D E ∨ BetS A E D) := by conclude cn_equalitysub
          have : A ≠ F := by
              rcases (show F = D ∨ F = E ∨ D = E ∨ BetS D A E ∨ BetS A D E ∨ BetS A E D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
              · have : A = D := by conclude cn_equalitysub
                have : ¬ A = F := by
                    intro h
                    contradict
                close
              · have : ¬ A = F := by
                    intro h
                    have : F ≠ E := by conclude lemma_inequalitysymmetric
                    contradict
                close
              · have : ¬ A = F := by
                    intro h
                    obtain ⟨p, _, _⟩ : ∃ p, (BetS E p C ∧ BetS B p F) := by conclude lemma_diagonalsmeet
                    have : Col E p C := by conclude_def Col
                    have : Col B p F := by conclude_def Col
                    have : Col F B p := by forward_using lemma_collinearorder
                    have : Col E C p := by forward_using lemma_collinearorder
                    have : nCol E F C := by forward_using lemma_parallelNC
                    have : E ≠ C := by forward_using lemma_NCdistinct
                    have : nCol E F B := by forward_using lemma_parallelNC
                    have : F ≠ B := by forward_using lemma_NCdistinct
                    have : Meet E C F B := by conclude_def Meet
                    have : Meet D C F B := by conclude cn_equalitysub
                    have : Meet D C A B := by conclude cn_equalitysub
                    have : Par D C A B := by conclude lemma_parallelsymmetric
                    have : ¬ Meet D C A B := by conclude_def Par
                    contradict
                close
              · have : ¬ A = F := by
                    intro h
                    have : BetS E A D := by conclude axiom_betweennesssymmetry
                    contradict
                close
              · have : ¬ A = F := by
                    intro h
                    contradict
                close
              · have : ¬ A = F := by
                    intro h
                    have : Cong A E A E := by conclude cn_congruencereflexive
                    have : Cong F E A E := by conclude cn_equalitysub
                    have : Cong A E F E := by conclude lemma_congruencesymmetric
                    have : Lt F E A D := by conclude_def Lt
                    have : Lt F E E F := by conclude lemma_lessthancongruence
                    have : Cong E F F E := by conclude cn_equalityreverse
                    have : Lt F E F E := by conclude lemma_lessthancongruence
                    have : ¬ Lt F E F E := by conclude lemma_trichotomy2
                    contradict
                close
          contradict
      have : ¬ D = F := by
          intro h
          have : (A = F ∨ A = E ∨ F = E ∨ BetS D A E ∨ BetS A D E ∨ BetS A E D) := by conclude cn_equalitysub
          have : D ≠ F := by
              rcases (show A = F ∨ A = E ∨ F = E ∨ BetS D A E ∨ BetS A D E ∨ BetS A E D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
              · have : ¬ D = F := by
                    intro h
                    contradict
                close
              · have : ¬ D = F := by
                    intro h
                    obtain ⟨M, _, _⟩ : ∃ M, (BetS A M C ∧ BetS B M D) := by conclude lemma_diagonalsmeet
                    have : ¬ Col A B C := by
                        intro h
                        have : C = C := by conclude cn_equalityreflexive
                        have : Col C D C := by conclude_def Col
                        have : A ≠ B := by conclude_def Par
                        have : C ≠ D := by conclude_def Par
                        have : Meet A B C D := by conclude_def Meet
                        have : ¬ Meet A B C D := by conclude_def Par
                        contradict
                    have : EF A B C D A B C D := by conclude lemma_EFreflexive
                    have : EF A B C D E B C D := by conclude cn_equalitysub
                    have : EF A B C D E B C F := by conclude cn_equalitysub
                    contradict
                close
              · have : ¬ D = F := by
                    intro h
                    have : F = E := by conclude cn_equalitysub
                    have : E = F := by conclude lemma_equalitysymmetric
                    contradict
                close
              · have : ¬ D = F := by
                    intro h
                    have : BetS E A D := by conclude axiom_betweennesssymmetry
                    contradict
                close
              · have : ¬ D = F := by
                    intro h
                    contradict
                close
              · have : ¬ D = F := by
                    intro h
                    have : BetS D E A := by conclude axiom_betweennesssymmetry
                    have : Cong D E D E := by conclude cn_congruencereflexive
                    have : Lt D E D A := by conclude_def Lt
                    have : Cong D E F E := by conclude cn_equalitysub
                    have : Lt F E D A := by conclude lemma_lessthancongruence2
                    have : Cong F E E F := by conclude cn_equalityreverse
                    have : Lt E F D A := by conclude lemma_lessthancongruence2
                    have : Cong D A A D := by conclude cn_equalityreverse
                    have : Lt E F A D := by conclude lemma_lessthancongruence
                    have : Lt E F E F := by conclude lemma_lessthancongruence
                    have : ¬ Lt E F E F := by conclude lemma_trichotomy2
                    contradict
                close
          contradict
      have : BetS A F D := by
          rcases (show A = D ∨ A = F ∨ D = F ∨ BetS D A F ∨ BetS A D F ∨ BetS A F D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
          · have : ¬ ¬ BetS A F D := by
                intro h
                contradict
            close
          · have : ¬ ¬ BetS A F D := by
                intro h
                contradict
            close
          · have : ¬ ¬ BetS A F D := by
                intro h
                contradict
            close
          · have : ¬ ¬ BetS A F D := by
                intro h
                contradict
            close
          · have : ¬ ¬ BetS A F D := by
                intro h
                contradict
            close
          · close
      have : BetS A E D := by
          rcases (show A = D ∨ A = E ∨ D = E ∨ BetS D A E ∨ BetS A D E ∨ BetS A E D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
          · have : ¬ ¬ BetS A E D := by
                intro h
                contradict
            close
          · have : ¬ ¬ BetS A E D := by
                intro h
                have : Cong A F A F := by conclude cn_congruencereflexive
                have : Cong A F E F := by conclude cn_equalitysub
                have : Lt E F A D := by conclude_def Lt
                have : Lt E F E F := by conclude lemma_lessthancongruence
                have : ¬ Lt E F E F := by conclude lemma_trichotomy2
                contradict
            close
          · have : ¬ ¬ BetS A E D := by
                intro h
                have : BetS D F A := by conclude axiom_betweennesssymmetry
                have : Cong D F D F := by conclude cn_congruencereflexive
                have : Lt D F D A := by conclude_def Lt
                have : Lt E F D A := by conclude cn_equalitysub
                have : Cong D A E F := by forward_using lemma_congruenceflip
                have : Lt E F E F := by conclude lemma_lessthancongruence
                have : ¬ Lt E F E F := by conclude lemma_trichotomy2
                contradict
            close
          · have : ¬ ¬ BetS A E D := by
                intro h
                have : BetS E A D := by conclude axiom_betweennesssymmetry
                contradict
            close
          · have : ¬ ¬ BetS A E D := by
                intro h
                contradict
            close
          · close
      have : ¬ BetS A E F := by
          intro h
          have : BetS E F D := by conclude lemma_3_6a
          have : Cong E F E F := by conclude cn_congruencereflexive
          have : Lt E F E D := by conclude_def Lt
          have : BetS D E A := by conclude axiom_betweennesssymmetry
          have : Cong D E D E := by conclude cn_congruencereflexive
          have : Lt D E D A := by conclude_def Lt
          have : Cong E D D E := by conclude cn_equalityreverse
          have : Lt E F D E := by conclude lemma_lessthancongruence
          have : Lt E F D A := by conclude lemma_lessthantransitive
          have : Cong D A A D := by conclude cn_equalityreverse
          have : Lt E F A D := by conclude lemma_lessthancongruence
          have : Lt E F E F := by conclude lemma_lessthancongruence
          have : ¬ Lt E F E F := by conclude lemma_trichotomy2
          contradict
      have : ¬ BetS A F E := by
          intro h
          have : BetS F E D := by conclude lemma_3_6a
          have : Cong F E F E := by conclude cn_congruencereflexive
          have : Lt F E F D := by conclude_def Lt
          have : BetS D F A := by conclude axiom_betweennesssymmetry
          have : Cong D F D F := by conclude cn_congruencereflexive
          have : Lt D F D A := by conclude_def Lt
          have : Cong F D D F := by conclude cn_equalityreverse
          have : Lt F E D F := by conclude lemma_lessthancongruence
          have : Lt F E D A := by conclude lemma_lessthantransitive
          have : Cong D A A D := by conclude cn_equalityreverse
          have : Lt F E A D := by conclude lemma_lessthancongruence
          have : Cong A D F E := by forward_using lemma_congruenceflip
          have : Lt F E F E := by conclude lemma_lessthancongruence
          have : ¬ Lt F E F E := by conclude lemma_trichotomy2
          contradict
      have : E = F := by conclude axiom_connectivity
      contradict
  close

end GeocoqTranslate.Elements
