/- Transpiled from theories/Elements/OriginalProofs/lemma_TGflip.v :: lemma_TGflip
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_TGflip :
    ∀ (A B C a b c : Point), TG A a B b C c → TG a A B b C c ∧ TG A a B b c C := by
  intro A B C a b c h1
  obtain ⟨H, _, _, _⟩ : ∃ H, (BetS A a H ∧ Cong a H B b ∧ Lt C c A H) := by conclude_def TG
  have : A ≠ a := by forward_using lemma_betweennotequal
  have : a ≠ A := by conclude lemma_inequalitysymmetric
  have : a ≠ H := by forward_using lemma_betweennotequal
  have : B ≠ b := by conclude axiom_nocollapse
  obtain ⟨h, _, _⟩ : ∃ h, (BetS a A h ∧ Cong A h B b) := by conclude lemma_extension
  have : Cong A a a A := by conclude cn_equalityreverse
  have : Cong B b A h := by conclude lemma_congruencesymmetric
  have : Cong a H A h := by conclude lemma_congruencetransitive
  have : Cong A H a h := by conclude cn_sumofparts
  have : Lt C c a h := by conclude lemma_lessthancongruence
  have : TG a A B b C c := by conclude_def TG
  have : Cong C c c C := by conclude cn_equalityreverse
  have : Lt c C A H := by conclude lemma_lessthancongruence2
  have : TG A a B b c C := by conclude_def TG
  have : Lt C c a h := by conclude lemma_lessthancongruence
  close

end GeocoqTranslate.Elements
