/- Transpiled from ../theories/Elements/OriginalProofs/lemma_equalanglesflip.v :: lemma_equalanglesflip
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_equalanglesflip :
    ∀ (A B C D E F : Point), CongA A B C D E F → CongA C B A F E D := by
  intro A B C D E F h1
  have : nCol D E F := by conclude lemma_equalanglesNC
  have : CongA D E F A B C := by conclude lemma_equalanglessymmetric
  have : nCol A B C := by conclude lemma_equalanglesNC
  have : ¬ Col C B A := by
      intro h
      have : Col A B C := by perm_close
      contradict
  have : CongA C B A A B C := by conclude lemma_ABCequalsCBA
  have : CongA C B A D E F := by conclude lemma_equalanglestransitive
  have : CongA D E F F E D := by conclude lemma_ABCequalsCBA
  have : CongA C B A F E D := by conclude lemma_equalanglestransitive
  close

end GeocoqTranslate.Elements
