/- Transpiled from ../theories/Elements/OriginalProofs/lemma_ondiameter.v :: lemma_ondiameter
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_ondiameter :
    ∀ (D F K M N P Q : Point), CI K F P Q → Cong F D P Q → Cong F M P Q → BetS D F M → BetS D N M → InCirc N K := by
  intro D F K M N P Q h1 h2 h3 h4 h5
  have : D ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ D := by conclude lemma_inequalitysymmetric
  have : ¬ ¬ (BetS D N F ∨ BetS F N M ∨ F = N) := by
      intro h
      have : ¬ BetS D F N := by
          intro h
          have : BetS F N M := by conclude lemma_3_6a
          contradict
      have : F = N := by conclude axiom_connectivity
      contradict
  have : Cong F N F N := by conclude cn_congruencereflexive
  sorry -- TODO: assert (InCirc N K).
  rcases (show BetS D N F ∨ BetS F N M ∨ F = N by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
  · have : BetS F N D := by conclude axiom_betweennesssymmetry
    have : InCirc N K := by conclude_def InCirc
    close
  · have : InCirc N K := by conclude_def InCirc
    close
  · have : N = F := by conclude lemma_equalitysymmetric
    have : InCirc N K := by conclude_def InCirc
    close
  close

end GeocoqTranslate.Elements
