/- Transpiled from ../theories/Elements/OriginalProofs/lemma_triangletoparallelogram.v :: lemma_triangletoparallelogram
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_Playfair
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

theorem lemma_triangletoparallelogram :
    ∀ (A C D E F : Point), Par D C E F → Col E F A → ∃ X, PG A X C D ∧ Col E F X := by
  intro A C D E F h1 h2
  have : nCol D C E := by forward_using lemma_parallelNC
  have : D ≠ C := by forward_using lemma_NCdistinct
  have : C ≠ D := by conclude lemma_inequalitysymmetric
  obtain ⟨B, _, _⟩ : ∃ B, (BetS C D B ∧ Cong D B C D) := by conclude lemma_extension
  have : BetS B D C := by conclude axiom_betweennesssymmetry
  have : nCol C E F := by forward_using lemma_parallelNC
  have : E ≠ F := by forward_using lemma_NCdistinct
  have : ¬ Col B C A := by
      intro h
      have : Col C D B := by conclude_def Col
      have : Col B C D := by forward_using lemma_collinearorder
      have : B ≠ C := by forward_using lemma_betweennotequal
      have : Col C A D := by conclude lemma_collinear4
      have : Col D C A := by forward_using lemma_collinearorder
      have : Meet D C E F := by conclude_def Meet
      have : ¬ Meet D C E F := by conclude_def Par
      contradict
  obtain ⟨c, b, M, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩ : ∃ c b M, (BetS c A b ∧ CongA b A D A D B ∧ CongA b A D B D A ∧ CongA D A b B D A ∧ CongA c A D A D C ∧ CongA c A D C D A ∧ CongA D A c C D A ∧ Par c b B C ∧ Cong c A D C ∧ Cong A b B D ∧ Cong A M M D ∧ Cong c M M C ∧ Cong B M M b ∧ BetS c M C ∧ BetS B M b ∧ BetS A M D) := by conclude proposition_31
  have : BetS b M B := by conclude axiom_betweennesssymmetry
  have : nCol b B C := by forward_using lemma_parallelNC
  obtain ⟨R, _, _⟩ : ∃ R, (BetS b R D ∧ BetS C R M) := by conclude postulate_Pasch_inner
  have : BetS C M c := by conclude axiom_betweennesssymmetry
  have : BetS C R c := by conclude lemma_3_6b
  have : BetS b A c := by conclude axiom_betweennesssymmetry
  have : nCol c b C := by forward_using lemma_parallelNC
  have : nCol b c C := by forward_using lemma_NCorder
  obtain ⟨Q, _, _⟩ : ∃ Q, (BetS b Q R ∧ BetS C Q A) := by conclude postulate_Pasch_inner
  have : BetS b Q D := by conclude lemma_3_6b
  have : Col C D B := by conclude_def Col
  have : Col B C D := by forward_using lemma_collinearorder
  have : Par c b D C := by conclude lemma_collinearparallel
  have : Par D C c b := by conclude lemma_parallelsymmetric
  have : Col c A b := by conclude_def Col
  have : Col c b A := by forward_using lemma_collinearorder
  have : A ≠ b := by forward_using lemma_betweennotequal
  have : Par D C A b := by conclude lemma_collinearparallel
  have : Par A b D C := by conclude lemma_parallelsymmetric
  have : Par b A C D := by forward_using lemma_parallelflip
  have : Cong B D D B := by conclude cn_equalityreverse
  have : Cong A b D B := by conclude lemma_congruencetransitive
  have : Cong A b C D := by conclude lemma_congruencetransitive
  have : Cong b A C D := by forward_using lemma_congruenceflip
  have : BetS A Q C := by conclude axiom_betweennesssymmetry
  have : (Par b C A D ∧ Cong b C A D) := by conclude proposition_33
  have : Par A b C D := by forward_using lemma_parallelflip
  have : Par A D b C := by conclude lemma_parallelsymmetric
  have : PG A b C D := by conclude_def PG
  have : E = E := by conclude cn_equalityreflexive
  have : Col E F E := by conclude_def Col
  sorry -- TODO: assert (Col E F b).
  rcases (show A = F ∨ A ≠ F by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
  · have : F ≠ E := by conclude lemma_inequalitysymmetric
    have : A ≠ E := by conclude cn_equalitysub
    have : Par D C A E := by conclude lemma_collinearparallel2
    have : Col A b E := by conclude lemma_Playfair
    have : Col F b E := by conclude cn_equalitysub
    have : Col E F b := by forward_using lemma_collinearorder
    close
  · have : Par D C A F := by conclude lemma_collinearparallel
    have : Col A b F := by conclude lemma_Playfair
    have : Col A F b := by forward_using lemma_collinearorder
    have : Col A F E := by forward_using lemma_collinearorder
    have : Col F b E := by conclude lemma_collinear4
    have : Col E F b := by forward_using lemma_collinearorder
    close
  close

end GeocoqTranslate.Elements
