/- Transpiled from ../theories/Elements/OriginalProofs/lemma_TTflip.v :: lemma_TTflip
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_TGsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_TGflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_TTflip :
    ∀ (A B C D E F G H : Point), TT A B C D E F G H → TT B A D C E F G H := by
  intro A B C D E F G H h1
  obtain ⟨J, _, _, _⟩ : ∃ J, (BetS E F J ∧ Cong F J G H ∧ TG A B C D E J) := by conclude_def TT
  have : TG B A C D E J := by forward_using lemma_TGflip
  have : TG C D B A E J := by conclude lemma_TGsymmetric
  have : TG D C B A E J := by forward_using lemma_TGflip
  have : TG B A D C E J := by conclude lemma_TGsymmetric
  have : TT B A D C E F G H := by conclude_def TT
  close

end GeocoqTranslate.Elements
