/- Transpiled from ../theories/Elements/OriginalProofs/lemma_diagonalsmeet.v :: lemma_diagonalsmeet
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_planeseparation
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearbetween
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_diagonalsmeet :
    ∀ (A B C D : Point), PG A B C D → ∃ X, BetS A X C ∧ BetS B X D := by
  intro A B C D h1
  have : (Par A B C D ∧ Par A D B C) := by conclude_def PG
  obtain ⟨a, b, c, d, m, _, _, _, _, _, _, _, _, _, _, _⟩ : ∃ a b c d m, (A ≠ B ∧ C ≠ D ∧ Col A B a ∧ Col A B b ∧ a ≠ b ∧ Col C D c ∧ Col C D d ∧ c ≠ d ∧ ¬ Meet A B C D ∧ BetS a m d ∧ BetS c m b) := by conclude_def Par
  have : Par C D A B := by conclude lemma_parallelsymmetric
  have : TP C D A B := by conclude lemma_paralleldef2B
  have : OS A B C D := by conclude_def TP
  have : D = D := by conclude cn_equalityreflexive
  have : Col D C D := by conclude_def Col
  have : ¬ A = D := by
      intro h
      have : Col D C A := by conclude cn_equalitysub
      have : Col C D A := by forward_using lemma_collinearorder
      have : A = A := by conclude cn_equalityreflexive
      have : Col A B A := by conclude_def Col
      have : Meet A B C D := by conclude_def Meet
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (BetS A D E ∧ Cong D E A D) := by conclude lemma_extension
  have : ¬ Col D C A := by
      intro h
      have : A = A := by conclude cn_equalityreflexive
      have : Col A B A := by conclude_def Col
      have : Col C D A := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      have : ¬ Meet A B C D := by conclude_def Par
      contradict
  have : TS A D C E := by (try (have : nCol D C A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
  have : OS B A D C := by forward_using lemma_samesidesymmetric
  have : TS B D C E := by conclude lemma_planeseparation
  obtain ⟨F, _, _, _⟩ : ∃ F, (BetS B F E ∧ Col D C F ∧ nCol D C B) := by conclude_def TS
  have : BetS E F B := by conclude axiom_betweennesssymmetry
  have : BetS E D A := by conclude axiom_betweennesssymmetry
  have : Col E D A := by conclude_def Col
  have : E ≠ D := by forward_using lemma_betweennotequal
  have : E ≠ A := by forward_using lemma_betweennotequal
  have : ¬ Meet A D B C := by conclude_def Par
  have : ¬ B = C := by
      intro h
      have : Col D B C := by conclude_def Col
      have : Col D C B := by forward_using lemma_collinearorder
      contradict
  obtain ⟨S, _, _⟩ : ∃ S, (BetS B C S ∧ Cong C S B C) := by conclude lemma_extension
  have : BetS S C B := by conclude axiom_betweennesssymmetry
  have : Col S C B := by conclude_def Col
  have : S ≠ B := by forward_using lemma_betweennotequal
  have : C ≠ B := by forward_using lemma_betweennotequal
  have : ¬ Meet E A S B := by
      intro h
      obtain ⟨R, _, _, _, _⟩ : ∃ R, (E ≠ A ∧ S ≠ B ∧ Col E A R ∧ Col S B R) := by conclude_def Meet
      have : Col B C S := by conclude_def Col
      have : Col S B C := by forward_using lemma_collinearorder
      have : Col B C R := by
          rcases (show B = R ∨ B ≠ R by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2
          · have : Col B C R := by conclude_def Col
            close
          · have : Col B R C := by conclude lemma_collinear4
            have : Col B C R := by forward_using lemma_collinearorder
            close
      have : Col A D E := by conclude_def Col
      have : Col E A D := by forward_using lemma_collinearorder
      have : A ≠ D := by forward_using lemma_betweennotequal
      have : Col A D R := by conclude lemma_collinear4
      have : Meet A D B C := by conclude_def Meet
      contradict
  have : Col D F C := by forward_using lemma_collinearorder
  have : BetS D F C := by conclude lemma_collinearbetween
  have : BetS C F D := by conclude axiom_betweennesssymmetry
  have : A ≠ E := by forward_using lemma_betweennotequal
  have : E ≠ A := by conclude lemma_inequalitysymmetric
  have : B ≠ S := by forward_using lemma_betweennotequal
  have : S ≠ B := by conclude lemma_inequalitysymmetric
  have : ¬ Col E A C := by
      intro h
      have : Col B C S := by conclude_def Col
      have : Col S B C := by forward_using lemma_collinearorder
      have : Meet E A S B := by conclude_def Meet
      contradict
  obtain ⟨H, _, _⟩ : ∃ H, (BetS C H A ∧ BetS E F H) := by conclude postulate_Pasch_outer
  have : Col E F H := by conclude_def Col
  have : Col E F B := by conclude_def Col
  have : E ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ E := by conclude lemma_inequalitysymmetric
  have : Col F E H := by forward_using lemma_collinearorder
  have : Col F E B := by forward_using lemma_collinearorder
  have : Col E H B := by conclude lemma_collinear4
  have : BetS A H C := by conclude axiom_betweennesssymmetry
  obtain ⟨R, _, _⟩ : ∃ R, (BetS A E R ∧ Cong E R A E) := by conclude lemma_extension
  have : Col A E R := by conclude_def Col
  have : A ≠ E := by forward_using lemma_betweennotequal
  have : A ≠ R := by forward_using lemma_betweennotequal
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  obtain ⟨T, _, _⟩ : ∃ T, (BetS C B T ∧ Cong B T C B) := by conclude lemma_extension
  have : ¬ Meet A R T C := by
      intro h
      obtain ⟨p, _, _, _, _⟩ : ∃ p, (A ≠ R ∧ T ≠ C ∧ Col A R p ∧ Col T C p) := by conclude_def Meet
      have : Col A E R := by conclude_def Col
      have : Col C B T := by conclude_def Col
      have : Col A D E := by conclude_def Col
      have : Col R A p := by forward_using lemma_collinearorder
      have : A = A := by conclude cn_equalityreflexive
      have : Col A R A := by conclude_def Col
      have : Col E A D := by forward_using lemma_collinearorder
      have : Col A E R := by conclude_def Col
      have : Col E A R := by forward_using lemma_collinearorder
      have : A ≠ D := by forward_using lemma_betweennotequal
      have : Col A D R := by conclude lemma_collinear4
      have : Col A R D := by forward_using lemma_collinearorder
      have : Col A D p := by conclude lemma_collinear5
      have : Col B T C := by forward_using lemma_collinearorder
      have : Col T C B := by forward_using lemma_collinearorder
      have : C ≠ T := by forward_using lemma_betweennotequal
      have : T ≠ C := by conclude lemma_inequalitysymmetric
      have : Col C B p := by conclude lemma_collinear4
      have : Col B C p := by forward_using lemma_collinearorder
      have : Meet A D B C := by conclude_def Meet
      contradict
  have : BetS T B C := by conclude axiom_betweennesssymmetry
  have : Col T B C := by conclude_def Col
  have : T ≠ C := by forward_using lemma_betweennotequal
  have : B ≠ C := by forward_using lemma_betweennotequal
  have : Col E B H := by forward_using lemma_collinearorder
  have : BetS E H B := by conclude lemma_collinearbetween
  have : BetS B H E := by conclude axiom_betweennesssymmetry
  have : ¬ Col B E A := by
      intro h
      have : Col A D E := by conclude_def Col
      have : Col E A D := by forward_using lemma_collinearorder
      have : Col E A B := by forward_using lemma_collinearorder
      have : Col A D B := by conclude lemma_collinear4
      have : B = B := by conclude cn_equalityreflexive
      have : Col B C B := by conclude_def Col
      have : Meet A D B C := by conclude_def Meet
      contradict
  obtain ⟨M, _, _⟩ : ∃ M, (BetS B M D ∧ BetS A M H) := by conclude postulate_Pasch_inner
  have : BetS A H C := by conclude axiom_betweennesssymmetry
  have : BetS A M C := by conclude lemma_3_6b
  close

end GeocoqTranslate.Elements
