/- Transpiled from theories/Elements/OriginalProofs/lemma_outerconnectivity.v :: lemma_outerconnectivity
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_5b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_differenceofparts
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extensionunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_outerconnectivity :
    ∀ (A B C D : Point), BetS A B C → BetS A B D → ¬ BetS B C D → ¬ BetS B D C → C = D := by
  intro A B C D h1 h2 h3 h4
  have : ¬ A = C := by
      intro h
      have : BetS A B A := by conclude cn_equalitysub
      have : ¬ BetS A B A := by conclude axiom_betweennessidentity
      contradict
  have : A ≠ D := by forward_using lemma_betweennotequal
  obtain ⟨E, _, _⟩ : ∃ E, (BetS A C E ∧ Cong C E A D) := by conclude lemma_extension
  have : BetS A B E := by conclude lemma_3_6b
  have : ¬ A = D := by
      intro h
      have : BetS A B A := by conclude cn_equalitysub
      have : ¬ BetS A B A := by conclude axiom_betweennessidentity
      contradict
  have : A ≠ C := by forward_using lemma_betweennotequal
  obtain ⟨F, _, _⟩ : ∃ F, (BetS A D F ∧ Cong D F A C) := by conclude lemma_extension
  have : BetS F D A := by conclude axiom_betweennesssymmetry
  have : BetS D B A := by conclude axiom_betweennesssymmetry
  have : BetS F B A := by conclude lemma_3_5b
  have : BetS A B F := by conclude axiom_betweennesssymmetry
  have : Cong F D D F := by conclude cn_equalityreverse
  have : Cong F D A C := by conclude lemma_congruencetransitive
  have : Cong A D C E := by conclude lemma_congruencesymmetric
  have : Cong D A A D := by conclude cn_equalityreverse
  have : Cong D A C E := by conclude lemma_congruencetransitive
  have : Cong F A A E := by conclude cn_sumofparts
  have : Cong A E F A := by conclude lemma_congruencesymmetric
  have : Cong F A A F := by conclude cn_equalityreverse
  have : Cong A E A F := by conclude lemma_congruencetransitive
  have : Cong A B A B := by conclude cn_congruencereflexive
  have : Cong B E B F := by conclude lemma_differenceofparts
  have : E = F := by conclude lemma_extensionunique
  have : BetS A D E := by conclude cn_equalitysub
  have : BetS B C E := by conclude lemma_3_6a
  have : BetS B D E := by conclude lemma_3_6a
  have : C = D := by conclude axiom_connectivity
  close

end GeocoqTranslate.Elements
