/- Transpiled from ../theories/Elements/OriginalProofs/lemma_8_3.v :: lemma_8_3
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_interior5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_8_3 :
    ∀ (A B C D : Point), Per A B C → Out B C D → Per A B D := by
  intro A B C D h1 h2
  obtain ⟨E, _, _, _, _⟩ : ∃ E, (BetS A B E ∧ Cong A B E B ∧ Cong A C E C ∧ B ≠ C) := by conclude_def Per
  have : Cong B C B C := by conclude cn_congruencereflexive
  have : Cong C D C D := by conclude cn_congruencereflexive
  have : Cong B A B E := by forward_using lemma_congruenceflip
  have : Cong C A C E := by forward_using lemma_congruenceflip
  have : (BetS B D C ∨ C = D ∨ BetS B C D) := by conclude lemma_ray1
  sorry -- TODO: assert (Per A B D).
  rcases (show BetS B D C ∨ C = D ∨ BetS B C D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
  · have : Cong B D B D := by conclude cn_congruencereflexive
    have : Cong D C D C := by conclude cn_congruencereflexive
    have : Cong D A D E := by conclude lemma_interior5
    have : Cong A D E D := by forward_using lemma_congruenceflip
    have : B ≠ D := by forward_using lemma_betweennotequal
    have : Per A B D := by conclude_def Per
    close
  · have : Per A B D := by conclude cn_equalitysub
    close
  · have : Cong A D E D := by conclude axiom_5_line
    have : B ≠ D := by forward_using lemma_betweennotequal
    have : Per A B D := by conclude_def Per
    close
  close

end GeocoqTranslate.Elements
