/- Transpiled from theories/Elements/OriginalProofs/lemma_Pasch_outer2.v :: lemma_Pasch_outer2
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_Pasch_outer2 :
    ∀ (A B C P Q : Point), BetS A P C → BetS B C Q → nCol B P A → ∃ X, BetS A X Q ∧ BetS B P X := by
  intro A B C P Q h1 h2 h3
  have : ¬ Col B Q A := by
      intro h
      have : Col A P C := by conclude_def Col
      have : Col B C Q := by conclude_def Col
      have : Col B Q C := by forward_using lemma_collinearorder
      have : ¬ Q = A := by
          intro h
          have : Col B A C := by conclude cn_equalitysub
          have : Col C A B := by forward_using lemma_collinearorder
          have : Col C A P := by forward_using lemma_collinearorder
          have : A ≠ C := by forward_using lemma_betweennotequal
          have : C ≠ A := by conclude lemma_inequalitysymmetric
          have : Col A B P := by conclude lemma_collinear4
          have : Col B P A := by forward_using lemma_collinearorder
          contradict
      have : Col B Q C := by forward_using lemma_collinearorder
      have : B ≠ Q := by forward_using lemma_betweennotequal
      have : Col Q A C := by conclude lemma_collinear4
      have : Col A C Q := by forward_using lemma_collinearorder
      have : Col A C P := by forward_using lemma_collinearorder
      have : A ≠ C := by forward_using lemma_betweennotequal
      have : Col C Q P := by conclude lemma_collinear4
      have : Col C Q B := by forward_using lemma_collinearorder
      have : C ≠ Q := by forward_using lemma_betweennotequal
      have : Col Q P B := by conclude lemma_collinear4
      have : Col Q B P := by forward_using lemma_collinearorder
      have : Col Q B A := by forward_using lemma_collinearorder
      have : Q ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B P A := by conclude lemma_collinear4
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (BetS A E Q ∧ BetS B P E) := by conclude postulate_Pasch_outer
  close

end GeocoqTranslate.Elements
