/- Transpiled from ../theories/Elements/OriginalProofs/lemma_supplementofright.v :: lemma_supplementofright
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_3
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_supplementofright :
    ∀ (A B C D F : Point), Supp A B C D F → Per A B C → Per F B D ∧ Per D B F := by
  intro A B C D F h1 h2
  have : (Out B C D ∧ BetS A B F) := by conclude_def Supp
  have : Col A B F := by conclude_def Col
  have : B ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ B := by conclude lemma_inequalitysymmetric
  have : Per F B C := by conclude lemma_collinearright
  have : Per F B D := by conclude lemma_8_3
  have : Per D B F := by conclude lemma_8_2
  close

end GeocoqTranslate.Elements
