/- Transpiled from theories/Elements/OriginalProofs/lemma_TCreflexive.v :: lemma_TCreflexive
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

theorem lemma_TCreflexive :
    ∀ (A B C : Point), Triangle A B C → Cong_3 A B C A B C := by
  intro A B C h1
  have : Cong A B A B := by conclude cn_congruencereflexive
  have : Cong B C B C := by conclude cn_congruencereflexive
  have : Cong A C A C := by conclude cn_congruencereflexive
  have : Cong_3 A B C A B C := by conclude_def Cong_3
  close

end GeocoqTranslate.Elements
