/- Transpiled from ../theories/Elements/OriginalProofs/lemma_paralleldef2A.v :: lemma_paralleldef2A
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_paralleldef2A :
    ∀ (A B C D : Point), TP A B C D → Par A B C D := by
  intro A B C D h1
  have : (A ≠ B ∧ C ≠ D ∧ ¬ Meet A B C D ∧ OS C D A B) := by conclude_def TP
  obtain ⟨a, b, e, _, _, _, _, _, _⟩ : ∃ a b e, (Col A B a ∧ Col A B b ∧ BetS C a e ∧ BetS D b e ∧ nCol A B C ∧ nCol A B D) := by conclude_def OS
  have : Col C a e := by conclude_def Col
  have : Col D b e := by conclude_def Col
  have : a ≠ e := by forward_using lemma_betweennotequal
  have : e ≠ a := by conclude lemma_inequalitysymmetric
  have : C ≠ e := by forward_using lemma_betweennotequal
  have : e ≠ C := by conclude lemma_inequalitysymmetric
  have : D ≠ e := by forward_using lemma_betweennotequal
  have : e ≠ D := by conclude lemma_inequalitysymmetric
  have : ¬ a = b := by
      intro h
      have : Col D a e := by conclude cn_equalitysub
      have : Col a e C := by forward_using lemma_collinearorder
      have : Col a e D := by forward_using lemma_collinearorder
      have : Col e C D := by conclude lemma_collinear4
      have : Col e D C := by forward_using lemma_collinearorder
      have : Col e D b := by forward_using lemma_collinearorder
      have : Col D C b := by conclude lemma_collinear4
      have : Col C D b := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ Col C e D := by
      intro h
      have : Col C e a := by forward_using lemma_collinearorder
      have : Col e D a := by conclude lemma_collinear4
      have : Col e D b := by forward_using lemma_collinearorder
      have : Col D a b := by conclude lemma_collinear4
      have : Col e D C := by forward_using lemma_collinearorder
      have : Col D C a := by conclude lemma_collinear4
      have : Col C D a := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      contradict
  obtain ⟨M, _, _⟩ : ∃ M, (BetS C M b ∧ BetS D M a) := by conclude postulate_Pasch_inner
  have : BetS a M D := by conclude axiom_betweennesssymmetry
  have : C = C := by conclude cn_equalityreflexive
  have : Col C D C := by conclude_def Col
  have : D = D := by conclude cn_equalityreflexive
  have : Col C D D := by conclude_def Col
  have : Par A B C D := by conclude_def Par
  close

end GeocoqTranslate.Elements
