/- Transpiled from ../theories/Elements/OriginalProofs/lemma_9_5a.v :: lemma_9_5a
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_9_5a :
    ∀ (A B C P Q R : Point), TS P A B C → BetS R P Q → nCol R Q C → Col A B R → TS Q A B C := by
  intro A B C P Q R h1 h2 h3 h4
  obtain ⟨S, _, _, _⟩ : ∃ S, (BetS P S C ∧ Col A B S ∧ nCol A B P) := by conclude_def TS
  have : BetS C S P := by conclude axiom_betweennesssymmetry
  obtain ⟨F, _, _⟩ : ∃ F, (BetS C F Q ∧ BetS R S F) := by conclude postulate_Pasch_outer
  have : Col R S F := by conclude_def Col
  have : ¬ A = B := by
      intro h
      have : Col A B P := by conclude_def Col
      contradict
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : Col B R S := by conclude lemma_collinear4
  have : Col R S B := by forward_using lemma_collinearorder
  have : R ≠ S := by forward_using lemma_betweennotequal
  have : Col S F B := by conclude lemma_collinear4
  have : Col S B A := by forward_using lemma_collinearorder
  have : Col S B F := by forward_using lemma_collinearorder
  have : Col A B F := by
      rcases (show S = B ∨ S ≠ B by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
      · have : Col B A S := by forward_using lemma_collinearorder
        have : Col R S F := by conclude_def Col
        have : Col R B F := by conclude cn_equalitysub
        have : Col R B A := by forward_using lemma_collinearorder
        have : ¬ R = B := by
            intro h
            have : R = S := by conclude cn_equalitysub
            have : R ≠ S := by forward_using lemma_betweennotequal
            have : R ≠ B := by conclude cn_equalitysub
            contradict
        have : Col B F A := by conclude lemma_collinear4
        have : Col A B F := by forward_using lemma_collinearorder
        close
      · have : Col B A F := by conclude lemma_collinear4
        have : Col A B F := by forward_using lemma_collinearorder
        close
  have : ¬ Col A B Q := by
      intro h
      have : Col B Q R := by conclude lemma_collinear4
      have : Col B R Q := by forward_using lemma_collinearorder
      have : Col B R F := by conclude lemma_collinear4
      have : Col R Q F := by
          rcases (show B = R ∨ B ≠ R by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
          · have : ¬ A = R := by
                intro h
                have : A = B := by conclude cn_equalitysub
                contradict
            have : Col B A R := by forward_using lemma_collinearorder
            have : Col B A F := by forward_using lemma_collinearorder
            have : Col A R F := by conclude lemma_collinear4
            have : Col B A Q := by forward_using lemma_collinearorder
            have : Col B A R := by forward_using lemma_collinearorder
            have : Col A R Q := by conclude lemma_collinear4
            have : Col R F Q := by conclude lemma_collinear4
            have : Col R Q F := by forward_using lemma_collinearorder
            close
          · have : Col R Q F := by conclude lemma_collinear4
            close
      have : Col F Q R := by forward_using lemma_collinearorder
      have : Col C F Q := by conclude_def Col
      have : Col F Q C := by forward_using lemma_collinearorder
      have : F ≠ Q := by forward_using lemma_betweennotequal
      have : Col Q R C := by conclude lemma_collinear4
      have : Col R Q C := by forward_using lemma_collinearorder
      contradict
  have : BetS Q F C := by conclude axiom_betweennesssymmetry
  have : TS Q A B C := by conclude_def TS
  close

end GeocoqTranslate.Elements
