/- Transpiled from ../theories/Elements/OriginalProofs/lemma_doublereverse.v :: lemma_doublereverse
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

set_option maxHeartbeats 800000 in
theorem lemma_doublereverse :
    ∀ (A B C D : Point), Cong A B C D → Cong D C B A ∧ Cong B A D C := by
  intro A B C D h1
  have : Cong C D D C := by conclude cn_equalityreverse
  have : Cong A B D C := by conclude lemma_congruencetransitive
  have : Cong B A A B := by conclude cn_equalityreverse
  have : Cong B A D C := by conclude lemma_congruencetransitive
  have : Cong D C B A := by conclude lemma_congruencesymmetric
  close

end GeocoqTranslate.Elements
