/- Transpiled from ../theories/Elements/OriginalProofs/lemma_equaltorightisright.v :: lemma_equaltorightisright
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_3
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_equaltorightisright :
    ∀ (A B C a b c : Point), Per A B C → CongA a b c A B C → Per a b c := by
  intro A B C a b c h1 h2
  have : CongA A B C a b c := by conclude lemma_equalanglessymmetric
  obtain ⟨E, F, e, f, _, _, _, _, _, _, _, _⟩ : ∃ E F e f, (Out B A E ∧ Out B C F ∧ Out b a e ∧ Out b c f ∧ Cong B E b e ∧ Cong B F b f ∧ Cong E F e f ∧ nCol A B C) := by conclude_def CongA
  have : Per A B F := by conclude lemma_8_3
  have : Per F B A := by conclude lemma_8_2
  have : Per F B E := by conclude lemma_8_3
  have : Per E B F := by conclude lemma_8_2
  have : B ≠ E := by conclude lemma_raystrict
  have : E ≠ B := by conclude lemma_inequalitysymmetric
  obtain ⟨W, _, _, _, _⟩ : ∃ W, (BetS E B W ∧ Cong E B W B ∧ Cong E F W F ∧ B ≠ F) := by conclude_def Per
  have : b ≠ e := by conclude axiom_nocollapse
  have : e ≠ b := by conclude lemma_inequalitysymmetric
  obtain ⟨w, _, _⟩ : ∃ w, (BetS e b w ∧ Cong b w e b) := by conclude lemma_extension
  have : Cong e b E B := by forward_using lemma_doublereverse
  have : Cong b w E B := by conclude lemma_congruencetransitive
  have : Cong E B B W := by forward_using lemma_congruenceflip
  have : Cong b w B W := by conclude lemma_congruencetransitive
  have : Cong b f B F := by conclude lemma_congruencesymmetric
  have : Cong e f E F := by conclude lemma_congruencesymmetric
  have : Cong e w E W := by conclude cn_sumofparts
  have : Cong f w F W := by conclude (axiom_5_line e b w f E B W F)
  have : Cong e b B W := by conclude lemma_congruencetransitive
  have : Cong B W b w := by conclude lemma_congruencesymmetric
  have : Cong e b b w := by conclude lemma_congruencetransitive
  have : Cong e b w b := by forward_using lemma_congruenceflip
  have : Cong e f W F := by conclude lemma_congruencetransitive
  have : Cong W F w f := by forward_using lemma_doublereverse
  have : Cong e f w f := by conclude lemma_congruencetransitive
  have : b ≠ f := by conclude lemma_raystrict
  have : Per e b f := by conclude_def Per
  have : Out b f c := by conclude lemma_ray5
  have : Per e b c := by conclude lemma_8_3
  have : Per c b e := by conclude lemma_8_2
  have : Out b e a := by conclude lemma_ray5
  have : Per c b a := by conclude lemma_8_3
  have : Per a b c := by conclude lemma_8_2
  close

end GeocoqTranslate.Elements
