/- Transpiled from ../theories/Elements/OriginalProofs/lemma_collinearbetween.v :: lemma_collinearbetween
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_collinearbetween :
    ∀ (A B C D E F H : Point), Col A E B → Col C F D → A ≠ B → C ≠ D → A ≠ E → F ≠ D → ¬ Meet A B C D → BetS A H D → Col E F H → BetS E H F := by
  intro A B C D E F H h1 h2 h3 h4 h5 h6 h7 h8 h9
  have : ¬ H = E := by
      intro h
      have : Col A H B := by conclude cn_equalitysub
      have : Col H A B := by forward_using lemma_collinearorder
      have : Col A H D := by conclude_def Col
      have : Col H A D := by forward_using lemma_collinearorder
      have : A ≠ H := by forward_using lemma_betweennotequal
      have : H ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A B D := by conclude lemma_collinear4
      have : D = D := by conclude cn_equalityreflexive
      have : Col C D D := by conclude_def Col
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ H = F := by
      intro h
      have : Col A H D := by conclude_def Col
      have : Col A F D := by conclude cn_equalitysub
      have : Col F D A := by forward_using lemma_collinearorder
      have : Col F D C := by forward_using lemma_collinearorder
      have : Col D A C := by conclude lemma_collinear4
      have : Col C D A := by forward_using lemma_collinearorder
      have : A = A := by conclude cn_equalityreflexive
      have : Col A B A := by conclude_def Col
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ BetS E F H := by
      intro h
      have : BetS D H A := by conclude axiom_betweennesssymmetry
      have : ¬ Col D A E := by
          intro h
          have : Col E A B := by forward_using lemma_collinearorder
          have : Col E A D := by forward_using lemma_collinearorder
          have : E ≠ A := by conclude lemma_inequalitysymmetric
          have : Col A B D := by conclude lemma_collinear4
          have : D = D := by conclude cn_equalityreflexive
          have : Col C D D := by conclude_def Col
          have : Meet A B C D := by conclude_def Meet
          contradict
      obtain ⟨Q, _, _⟩ : ∃ Q, (BetS E Q A ∧ BetS D F Q) := by conclude postulate_Pasch_outer
      have : Col E Q A := by conclude_def Col
      have : Col D F Q := by conclude_def Col
      have : Col E A Q := by forward_using lemma_collinearorder
      have : Col E A B := by forward_using lemma_collinearorder
      have : E ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A Q B := by conclude lemma_collinear4
      have : Col A B Q := by forward_using lemma_collinearorder
      have : Col F D Q := by forward_using lemma_collinearorder
      have : Col F D C := by forward_using lemma_collinearorder
      have : Col D Q C := by conclude lemma_collinear4
      have : Col C D Q := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ BetS F E H := by
      intro h
      have : ¬ Col A D F := by
          intro h
          have : Col F D C := by forward_using lemma_collinearorder
          have : Col F D A := by forward_using lemma_collinearorder
          have : Col D C A := by conclude lemma_collinear4
          have : Col C D A := by forward_using lemma_collinearorder
          have : A = A := by conclude cn_equalityreflexive
          have : Col A B A := by conclude_def Col
          have : Meet A B C D := by conclude_def Meet
          contradict
      obtain ⟨R, _, _⟩ : ∃ R, (BetS F R D ∧ BetS A E R) := by conclude postulate_Pasch_outer
      have : Col F R D := by conclude_def Col
      have : Col A E R := by conclude_def Col
      have : Col F D R := by forward_using lemma_collinearorder
      have : Col F D C := by forward_using lemma_collinearorder
      have : Col D R C := by conclude lemma_collinear4
      have : Col C D R := by forward_using lemma_collinearorder
      have : Col E A R := by forward_using lemma_collinearorder
      have : Col E A B := by forward_using lemma_collinearorder
      have : A ≠ E := by forward_using lemma_betweennotequal
      have : E ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A R B := by conclude lemma_collinear4
      have : Col A B R := by forward_using lemma_collinearorder
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : ¬ E = F := by
      intro h
      have : Col C D F := by forward_using lemma_collinearorder
      have : Col A B E := by forward_using lemma_collinearorder
      have : Col A B F := by conclude cn_equalitysub
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : (E = F ∨ E = H ∨ F = H ∨ BetS F E H ∨ BetS E F H ∨ BetS E H F) := by conclude_def Col
  have : BetS E H F := by
      rcases (show E = F ∨ E = H ∨ F = H ∨ BetS F E H ∨ BetS E F H ∨ BetS E H F by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
      · have : ¬ ¬ BetS E H F := by
            intro h
            contradict
        close
      · have : ¬ ¬ BetS E H F := by
            intro h
            have : E ≠ H := by conclude lemma_inequalitysymmetric
            contradict
        close
      · have : ¬ ¬ BetS E H F := by
            intro h
            have : F ≠ H := by conclude lemma_inequalitysymmetric
            contradict
        close
      · have : ¬ ¬ BetS E H F := by
            intro h
            contradict
        close
      · have : ¬ ¬ BetS E H F := by
            intro h
            contradict
        close
      · close
  close

end GeocoqTranslate.Elements
