/- Transpiled from ../theories/Elements/OriginalProofs/lemma_PGrectangle.v :: lemma_PGrectangle
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.proposition_34
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equaltorightisright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.proposition_29C
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplementofright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

set_option maxHeartbeats 800000 in
theorem lemma_PGrectangle :
    ∀ (A B C D : Point), PG A C D B → Per B A C → RE A C D B := by
  intro A B C D h1 h2
  have : (Cong A B C D ∧ Cong A C B D ∧ CongA C A B B D C ∧ CongA A B D D C A ∧ Cong_3 C A B B D C) := by conclude proposition_34
  have : Par A C D B := by conclude_def PG
  have : nCol A C B := by forward_using lemma_parallelNC
  have : nCol A B C := by perm_close
  have : nCol C A B := by perm_close
  have : CongA C A B B A C := by conclude lemma_ABCequalsCBA
  have : Per C A B := by conclude lemma_8_2
  have : A ≠ B := by forward_using lemma_NCdistinct
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : CongA B A C C A B := by conclude lemma_equalanglessymmetric
  have : CongA B A C B D C := by conclude lemma_equalanglestransitive
  have : CongA B D C B A C := by conclude lemma_equalanglessymmetric
  have : Per B D C := by conclude lemma_equaltorightisright
  have : Per C D B := by conclude lemma_8_2
  have : Par A C B D := by forward_using lemma_parallelflip
  have : Par A B C D := by conclude_def PG
  have : TP A B C D := by conclude lemma_paralleldef2B
  have : OS C D A B := by conclude_def TP
  have : C ≠ A := by forward_using lemma_NCdistinct
  obtain ⟨E, _, _⟩ : ∃ E, (BetS B A E ∧ Cong A E A B) := by conclude lemma_extension
  have : BetS E A B := by conclude axiom_betweennesssymmetry
  have : RT C A B A B D := by conclude proposition_29C
  obtain ⟨p, q, r, s, t, _, _, _⟩ : ∃ p q r s t, (Supp p q r s t ∧ CongA C A B p q r ∧ CongA A B D s q t) := by conclude_def RT
  have : CongA p q r C A B := by conclude lemma_equalanglessymmetric
  have : Per p q r := by conclude lemma_equaltorightisright
  have : Per s q t := by conclude lemma_supplementofright
  have : CongA s q t A B D := by conclude lemma_equalanglessymmetric
  have : Per A B D := by conclude lemma_equaltorightisright
  have : Per D B A := by conclude lemma_8_2
  have : CongA D C A A B D := by conclude lemma_equalanglessymmetric
  have : Per D C A := by conclude lemma_equaltorightisright
  have : Per A C D := by conclude lemma_8_2
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M D ∧ BetS C M B) := by conclude lemma_diagonalsmeet
  have : A ≠ D := by forward_using lemma_betweennotequal
  have : C ≠ B := by forward_using lemma_betweennotequal
  have : CR A D C B := by conclude_def CR
  have : RE A C D B := by conclude_def RE
  close

end GeocoqTranslate.Elements
