/- Transpiled from ../theories/Elements/OriginalProofs/lemma_paste5.v :: lemma_paste5
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rectangleparallelogram
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_sameside2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samenotopposite
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crisscross
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crossimpliesopposite
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass area
variable {Point : Type} [area Point]

theorem lemma_paste5 :
    ∀ (B C D E L M b c d e l m : Point), EF B M L D b m l d → EF M C E L m c e l → BetS B M C → BetS b m c → BetS E L D → BetS e l d → RE M C E L → RE m c e l → EF B C E D b c e d := by
  intro B C D E L M b c d e l m h1 h2 h3 h4 h5 h6 h7 h8
  have : PG M C E L := by conclude lemma_rectangleparallelogram
  have : PG m c e l := by conclude lemma_rectangleparallelogram
  obtain ⟨P, _, _⟩ : ∃ P, (BetS M P E ∧ BetS C P L) := by conclude lemma_diagonalsmeet
  obtain ⟨p, _, _⟩ : ∃ p, (BetS m p e ∧ BetS c p l) := by conclude lemma_diagonalsmeet
  have : Par M C E L := by conclude_def PG
  have : nCol M C L := by forward_using lemma_parallelNC
  have : Par m c e l := by conclude_def PG
  have : nCol m c l := by forward_using lemma_parallelNC
  have : Cong_3 C M L L E C := by conclude proposition_34
  have : Cong_3 c m l l e c := by conclude proposition_34
  have : ET C M L L E C := by conclude axiom_congruentequal
  have : ET c m l l e c := by conclude axiom_congruentequal
  have : CR M E C L := by conclude_def RE
  have : CR m e c l := by conclude_def RE
  have : ET c m l c l e := by forward_using axiom_ETpermutation
  have : ET c l e c m l := by conclude axiom_ETsymmetric
  have : ET c l e m c l := by forward_using axiom_ETpermutation
  have : ET m c l c l e := by conclude axiom_ETsymmetric
  have : ET C M L C L E := by forward_using axiom_ETpermutation
  have : ET C L E C M L := by conclude axiom_ETsymmetric
  have : ET C L E M C L := by forward_using axiom_ETpermutation
  have : ET M C L C L E := by conclude axiom_ETsymmetric
  have : TS M C L E := by forward_using lemma_crossimpliesopposite
  have : TS m c l e := by forward_using lemma_crossimpliesopposite
  have : ET M C L m c l := by conclude axiom_halvesofequals
  have : EF M C E L e c m l := by forward_using axiom_EFpermutation
  have : EF e c m l M C E L := by conclude axiom_EFsymmetric
  have : EF e c m l E C M L := by forward_using axiom_EFpermutation
  have : EF E C M L e c m l := by conclude axiom_EFsymmetric
  have : TS E C L M := by conclude lemma_oppositesidesymmetric
  have : TS e c l m := by conclude lemma_oppositesidesymmetric
  have : ET M C L E C L := by forward_using axiom_ETpermutation
  have : ET E C L M C L := by conclude axiom_ETsymmetric
  have : ET E C L C L M := by forward_using axiom_ETpermutation
  have : ET m c l e c l := by forward_using axiom_ETpermutation
  have : ET e c l m c l := by conclude axiom_ETsymmetric
  have : ET e c l c l m := by forward_using axiom_ETpermutation
  have : ET E C L e c l := by conclude axiom_halvesofequals
  have : EF B M L D d b m l := by forward_using axiom_EFpermutation
  have : EF d b m l B M L D := by conclude axiom_EFsymmetric
  have : EF d b m l D B M L := by forward_using axiom_EFpermutation
  have : EF D B M L d b m l := by conclude axiom_EFsymmetric
  have : Col B M C := by conclude_def Col
  have : Col M C B := by forward_using lemma_collinearorder
  have : B ≠ C := by forward_using lemma_betweennotequal
  have : Par E L M C := by conclude lemma_parallelsymmetric
  have : Par E L B C := by conclude lemma_collinearparallel
  have : Par B C E L := by conclude lemma_parallelsymmetric
  have : Col E L D := by conclude_def Col
  have : L ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ L := by conclude lemma_inequalitysymmetric
  have : Par B C D L := by conclude lemma_collinearparallel
  have : E ≠ L := by forward_using lemma_betweennotequal
  have : M ≠ C := by forward_using lemma_betweennotequal
  have : ¬ CR B D C L := by
      intro h
      have : ¬ Col C L M := by
          intro h
          have : Col M C L := by forward_using lemma_collinearorder
          have : L = L := by conclude cn_equalityreflexive
          have : Col E L L := by conclude_def Col
          have : Meet E L M C := by conclude_def Meet
          have : ¬ Meet E L M C := by conclude_def Par
          contradict
      have : ¬ Col C L D := by
          intro h
          have : Col D L C := by forward_using lemma_collinearorder
          have : Col E L D := by conclude_def Col
          have : Col D L E := by forward_using lemma_collinearorder
          have : L ≠ D := by forward_using lemma_betweennotequal
          have : D ≠ L := by conclude lemma_inequalitysymmetric
          have : Col L E C := by conclude lemma_collinear4
          have : Col E L C := by forward_using lemma_collinearorder
          have : C = C := by conclude cn_equalityreflexive
          have : Col M C C := by conclude_def Col
          have : Meet E L M C := by conclude_def Meet
          have : ¬ Meet E L M C := by conclude_def Par
          contradict
      have : L = L := by conclude cn_equalityreflexive
      have : Col C L L := by conclude_def Col
      have : BetS D L E := by conclude axiom_betweennesssymmetry
      have : Col C L P := by conclude_def Col
      have : OS D M C L := by unfold OS; exists E; exists L; exists P; splits;auto
      have : BetS C M B := by conclude axiom_betweennesssymmetry
      have : C ≠ M := by forward_using lemma_betweennotequal
      have : Out C M B := by conclude lemma_ray4
      have : C = C := by conclude cn_equalityreflexive
      have : Col C C L := by conclude_def Col
      have : OS D B C L := by conclude lemma_sameside2
      have : OS B D C L := by forward_using lemma_samesidesymmetric
      have : ¬ TS B C L D := by conclude lemma_samenotopposite
      have : ¬ Col B C L := by
          intro h
          have : Col B M C := by conclude_def Col
          have : Col B C M := by forward_using lemma_collinearorder
          have : B ≠ C := by forward_using lemma_betweennotequal
          have : Col C M L := by conclude lemma_collinear4
          have : Col M C L := by forward_using lemma_collinearorder
          have : Col E L L := by conclude_def Col
          have : Meet E L M C := by conclude_def Meet
          have : ¬ Meet E L M C := by conclude_def Par
          contradict
      have : TS B C L D := by conclude (lemma_crossimpliesopposite B D C L)
      contradict
  have : CR B L D C := by conclude lemma_crisscross
  obtain ⟨R, _, _⟩ : ∃ R, (BetS B R L ∧ BetS D R C) := by conclude_def CR
  have : Col b m c := by conclude_def Col
  have : Col m c b := by forward_using lemma_collinearorder
  have : b ≠ c := by forward_using lemma_betweennotequal
  have : Par e l m c := by conclude lemma_parallelsymmetric
  have : Par e l b c := by conclude lemma_collinearparallel
  have : Par b c e l := by conclude lemma_parallelsymmetric
  have : Col e l d := by conclude_def Col
  have : l ≠ d := by forward_using lemma_betweennotequal
  have : d ≠ l := by conclude lemma_inequalitysymmetric
  have : Par b c d l := by conclude lemma_collinearparallel
  have : e ≠ l := by forward_using lemma_betweennotequal
  have : m ≠ c := by forward_using lemma_betweennotequal
  have : ¬ CR b d c l := by
      intro h
      have : ¬ Col c l m := by
          intro h
          have : Col m c l := by forward_using lemma_collinearorder
          have : l = l := by conclude cn_equalityreflexive
          have : Col e l l := by conclude_def Col
          have : Meet e l m c := by conclude_def Meet
          have : ¬ Meet e l m c := by conclude_def Par
          contradict
      have : ¬ Col c l d := by
          intro h
          have : Col d l c := by forward_using lemma_collinearorder
          have : Col e l d := by conclude_def Col
          have : Col d l e := by forward_using lemma_collinearorder
          have : l ≠ d := by forward_using lemma_betweennotequal
          have : d ≠ l := by conclude lemma_inequalitysymmetric
          have : Col l e c := by conclude lemma_collinear4
          have : Col e l c := by forward_using lemma_collinearorder
          have : c = c := by conclude cn_equalityreflexive
          have : Col m c c := by conclude_def Col
          have : Meet e l m c := by conclude_def Meet
          have : ¬ Meet e l m c := by conclude_def Par
          contradict
      have : l = l := by conclude cn_equalityreflexive
      have : Col c l l := by conclude_def Col
      have : BetS d l e := by conclude axiom_betweennesssymmetry
      have : Col c l p := by conclude_def Col
      have : OS d m c l := by unfold OS; exists e;exists l;exists p;splits;auto
      have : BetS c m b := by conclude axiom_betweennesssymmetry
      have : c ≠ m := by forward_using lemma_betweennotequal
      have : Out c m b := by conclude lemma_ray4
      have : c = c := by conclude cn_equalityreflexive
      have : Col c c l := by conclude_def Col
      have : OS d b c l := by conclude lemma_sameside2
      have : OS b d c l := by forward_using lemma_samesidesymmetric
      have : ¬ TS b c l d := by conclude lemma_samenotopposite
      have : ¬ Col b c l := by
          intro h
          have : Col b m c := by conclude_def Col
          have : Col b c m := by forward_using lemma_collinearorder
          have : b ≠ c := by forward_using lemma_betweennotequal
          have : Col c m l := by conclude lemma_collinear4
          have : Col m c l := by forward_using lemma_collinearorder
          have : Col e l l := by conclude_def Col
          have : Meet e l m c := by conclude_def Meet
          have : ¬ Meet e l m c := by conclude_def Par
          contradict
      have : TS b c l d := by conclude (lemma_crossimpliesopposite b d c l)
      contradict
  have : CR b l d c := by conclude lemma_crisscross
  obtain ⟨r, _, _⟩ : ∃ r, (BetS b r l ∧ BetS d r c) := by conclude_def CR
  have : EF D B C L d b c l := by conclude axiom_paste2
  have : EF D B C L b d l c := by forward_using axiom_EFpermutation
  have : EF b d l c D B C L := by conclude axiom_EFsymmetric
  have : EF b d l c B D L C := by forward_using axiom_EFpermutation
  have : EF B D L C b d l c := by conclude axiom_EFsymmetric
  have : ET E C L l e c := by forward_using axiom_ETpermutation
  have : ET l e c E C L := by conclude axiom_ETsymmetric
  have : ET l e c L E C := by forward_using axiom_ETpermutation
  have : ET L E C l e c := by conclude axiom_ETsymmetric
  have : BetS D L E := by conclude axiom_betweennesssymmetry
  have : BetS d l e := by conclude axiom_betweennesssymmetry
  have : Par B C L E := by forward_using lemma_parallelflip
  have : Col E L D := by conclude_def Col
  have : Col L E D := by forward_using lemma_collinearorder
  have : E ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ E := by conclude lemma_inequalitysymmetric
  have : Par B C D E := by conclude lemma_collinearparallel
  have : Par M L C E := by conclude_def PG
  have : Par C E M L := by conclude lemma_parallelsymmetric
  have : TP C E M L := by conclude lemma_paralleldef2B
  have : OS M L C E := by conclude_def TP
  have : OS L M C E := by forward_using lemma_samesidesymmetric
  have : M ≠ C := by forward_using lemma_betweennotequal
  have : C ≠ M := by conclude lemma_inequalitysymmetric
  have : BetS C M B := by conclude axiom_betweennesssymmetry
  have : Out C M B := by conclude lemma_ray4
  have : C = C := by conclude cn_equalityreflexive
  have : Col C C E := by conclude_def Col
  have : OS L B C E := by conclude lemma_sameside2
  have : OS B L C E := by forward_using lemma_samesidesymmetric
  have : E ≠ L := by forward_using lemma_betweennotequal
  have : Out E L D := by conclude lemma_ray4
  have : E = E := by conclude cn_equalityreflexive
  have : Col C E E := by conclude_def Col
  have : OS B D C E := by conclude lemma_sameside2
  have : OS D B C E := by forward_using lemma_samesidesymmetric
  have : ¬ CR B D C E := by
      intro h
      have : ¬ Col B C E := by
          intro h
          have : E = E := by conclude cn_equalityreflexive
          have : Col D E E := by conclude_def Col
          have : Meet B C D E := by conclude_def Meet
          have : ¬ Meet B C D E := by conclude_def Par
          contradict
      have : TS B C E D := by conclude (lemma_crossimpliesopposite B D C E)
      have : ¬ TS B C E D := by conclude lemma_samenotopposite
      contradict
  have : CR B E D C := by conclude lemma_crisscross
  obtain ⟨T, _, _⟩ : ∃ T, (BetS B T E ∧ BetS D T C) := by conclude_def CR
  have : Par b c l e := by forward_using lemma_parallelflip
  have : Col e l d := by conclude_def Col
  have : Col l e d := by forward_using lemma_collinearorder
  have : e ≠ d := by forward_using lemma_betweennotequal
  have : d ≠ e := by conclude lemma_inequalitysymmetric
  have : Par b c d e := by conclude lemma_collinearparallel
  have : Par m l c e := by conclude_def PG
  have : Par c e m l := by conclude lemma_parallelsymmetric
  have : TP c e m l := by conclude lemma_paralleldef2B
  have : OS m l c e := by conclude_def TP
  have : OS l m c e := by forward_using lemma_samesidesymmetric
  have : m ≠ c := by forward_using lemma_betweennotequal
  have : c ≠ m := by conclude lemma_inequalitysymmetric
  have : BetS c m b := by conclude axiom_betweennesssymmetry
  have : Out c m b := by conclude lemma_ray4
  have : c = c := by conclude cn_equalityreflexive
  have : Col c c e := by conclude_def Col
  have : OS l b c e := by conclude lemma_sameside2
  have : OS b l c e := by forward_using lemma_samesidesymmetric
  have : e ≠ l := by forward_using lemma_betweennotequal
  have : Out e l d := by conclude lemma_ray4
  have : e = e := by conclude cn_equalityreflexive
  have : Col c e e := by conclude_def Col
  have : OS b d c e := by conclude lemma_sameside2
  have : OS d b c e := by forward_using lemma_samesidesymmetric
  have : ¬ CR b d c e := by
      intro h
      have : ¬ Col b c e := by
          intro h
          have : e = e := by conclude cn_equalityreflexive
          have : Col d e e := by conclude_def Col
          have : Meet b c d e := by conclude_def Meet
          have : ¬ Meet b c d e := by conclude_def Par
          contradict
      have : TS b c e d := by conclude (lemma_crossimpliesopposite b d c e)
      have : ¬ TS b c e d := by conclude lemma_samenotopposite
      contradict
  have : CR b e d c := by conclude lemma_crisscross
  obtain ⟨t, _, _⟩ : ∃ t, (BetS b t e ∧ BetS d t c) := by conclude_def CR
  have : EF B D E C b d e c := by conclude axiom_paste2
  have : EF B D E C b c e d := by forward_using axiom_EFpermutation
  have : EF b c e d B D E C := by conclude axiom_EFsymmetric
  have : EF b c e d B C E D := by forward_using axiom_EFpermutation
  have : EF B C E D b c e d := by conclude axiom_EFsymmetric
  close

end GeocoqTranslate.Elements
