/- Transpiled from ../theories/Elements/OriginalProofs/lemma_parallelcollinear1.v :: lemma_parallelcollinear1
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearbetween
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_parallelcollinear1 :
    ∀ (A B C c d : Point), TP A B c d → BetS C c d → TP A B C d := by
  intro A B C c d h1 h2
  have : Col C c d := by conclude_def Col
  have : C ≠ c := by forward_using lemma_betweennotequal
  have : c ≠ d := by forward_using lemma_betweennotequal
  have : C ≠ d := by forward_using lemma_betweennotequal
  have : (A ≠ B ∧ c ≠ d ∧ ¬ Meet A B c d ∧ OS c d A B) := by conclude_def TP
  obtain ⟨p, q, r, _, _, _, _, _, _⟩ : ∃ p q r, (Col A B p ∧ Col A B r ∧ BetS c p q ∧ BetS d r q ∧ nCol A B c ∧ nCol A B d) := by conclude_def OS
  have : BetS q r d := by conclude axiom_betweennesssymmetry
  have : Col C c d := by conclude_def Col
  have : Col c d C := by forward_using lemma_collinearorder
  have : BetS d c C := by conclude axiom_betweennesssymmetry
  have : BetS q p c := by conclude axiom_betweennesssymmetry
  have : ¬ p = r := by
      intro h
      have : Col q r d := by conclude_def Col
      have : Col q p c := by conclude_def Col
      have : Col q p d := by conclude cn_equalitysub
      have : q ≠ p := by forward_using lemma_betweennotequal
      have : Col p c d := by conclude lemma_collinear4
      have : Col c d p := by forward_using lemma_collinearorder
      have : Meet A B c d := by conclude_def Meet
      contradict
  have : Col q p c := by conclude_def Col
  have : ¬ Col q d C := by
      intro h
      have : Col d c C := by conclude_def Col
      have : Col C d c := by forward_using lemma_collinearorder
      have : Col C d q := by forward_using lemma_collinearorder
      have : C ≠ d := by forward_using lemma_betweennotequal
      have : Col d c q := by conclude lemma_collinear4
      have : Col c q d := by forward_using lemma_collinearorder
      have : Col c q p := by forward_using lemma_collinearorder
      have : q ≠ c := by forward_using lemma_betweennotequal
      have : c ≠ q := by conclude lemma_inequalitysymmetric
      have : Col q d p := by conclude lemma_collinear4
      have : Col q r d := by conclude_def Col
      have : Col q d r := by forward_using lemma_collinearorder
      have : q ≠ d := by forward_using lemma_betweennotequal
      have : Col d p r := by conclude lemma_collinear4
      have : Col B p r := by conclude lemma_collinear4
      have : Col B A p := by forward_using lemma_collinearorder
      have : Col B p A := by forward_using lemma_collinearorder
      have : Col B A r := by forward_using lemma_collinearorder
      have : B ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A p r := by conclude lemma_collinear4
      have : ¬ B ≠ p := by
          intro h
          have : Col p r A := by conclude lemma_collinear4
          have : Col p r d := by forward_using lemma_collinearorder
          have : Col r A d := by conclude lemma_collinear4
          have : Col r A B := by forward_using lemma_collinearorder
          have : ¬ r ≠ A := by
              intro h
              have : Col A d B := by conclude lemma_collinear4
              have : Col A B d := by forward_using lemma_collinearorder
              contradict
          have : Col p A d := by conclude cn_equalitysub
          have : Col p A B := by forward_using lemma_collinearorder
          have : ¬ p ≠ A := by
              intro h
              have : Col A d B := by conclude lemma_collinear4
              have : Col A B d := by forward_using lemma_collinearorder
              contradict
          have : A = p := by conclude lemma_equalitysymmetric
          have : r = p := by conclude cn_equalitytransitive
          have : Col q p d := by conclude cn_equalitysub
          have : q ≠ p := by forward_using lemma_betweennotequal
          have : Col p c d := by conclude lemma_collinear4
          have : Col c d p := by forward_using lemma_collinearorder
          have : Meet A B c d := by conclude_def Meet
          contradict
      have : A ≠ p := by conclude cn_equalitysub
      have : Col A p B := by forward_using lemma_collinearorder
      have : ¬ r = A := by
          intro h
          have : Col d p A := by conclude cn_equalitysub
          have : Col d B A := by conclude cn_equalitysub
          have : Col A B d := by forward_using lemma_collinearorder
          contradict
      have : Col r A B := by forward_using lemma_collinearorder
      have : Col d B r := by conclude cn_equalitysub
      have : Col r B d := by forward_using lemma_collinearorder
      have : Col r B A := by forward_using lemma_collinearorder
      have : ¬ r ≠ B := by
          intro h
          have : Col B d A := by conclude lemma_collinear4
          have : Col A B d := by forward_using lemma_collinearorder
          contradict
      have : B = r := by conclude lemma_equalitysymmetric
      have : p = B := by conclude lemma_equalitysymmetric
      have : p = r := by conclude cn_equalitytransitive
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (BetS q E c ∧ BetS C E r) := by conclude postulate_Pasch_inner
  have : BetS r E C := by conclude axiom_betweennesssymmetry
  have : Col q E c := by conclude_def Col
  have : Col q c p := by forward_using lemma_collinearorder
  have : Col q c E := by forward_using lemma_collinearorder
  have : q ≠ c := by forward_using lemma_betweennotequal
  have : Col c p E := by conclude lemma_collinear4
  have : Col c E p := by forward_using lemma_collinearorder
  have : r ≠ p := by conclude lemma_inequalitysymmetric
  obtain ⟨J, _, _⟩ : ∃ J, (BetS r p J ∧ Cong p J r p) := by conclude lemma_extension
  have : BetS J p r := by conclude axiom_betweennesssymmetry
  have : Col J p r := by conclude_def Col
  have : J ≠ r := by forward_using lemma_betweennotequal
  have : p ≠ r := by forward_using lemma_betweennotequal
  have : J ≠ p := by forward_using lemma_betweennotequal
  have : Col B p r := by conclude lemma_collinear4
  have : Col B A p := by forward_using lemma_collinearorder
  have : Col B A r := by forward_using lemma_collinearorder
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : Col A p r := by conclude lemma_collinear4
  have : Col p r A := by forward_using lemma_collinearorder
  have : Col p r B := by forward_using lemma_collinearorder
  have : ¬ Meet C d J r := by
      intro h
      obtain ⟨K, _, _, _, _⟩ : ∃ K, (C ≠ d ∧ J ≠ r ∧ Col C d K ∧ Col J r K) := by conclude_def Meet
      have : Col C c d := by conclude_def Col
      have : Col C d c := by forward_using lemma_collinearorder
      have : c ≠ d := by forward_using lemma_betweennotequal
      have : d ≠ c := by conclude lemma_inequalitysymmetric
      have : Col d c K := by conclude lemma_collinear4
      have : Col c d K := by forward_using lemma_collinearorder
      have : Col r p J := by conclude_def Col
      have : Col r J p := by forward_using lemma_collinearorder
      have : r ≠ J := by forward_using lemma_betweennotequal
      have : Col r J K := by forward_using lemma_collinearorder
      have : Col J p K := by conclude lemma_collinear4
      have : Col J p r := by forward_using lemma_collinearorder
      have : p ≠ J := by forward_using lemma_betweennotequal
      have : J ≠ p := by conclude lemma_inequalitysymmetric
      have : Col p K r := by conclude lemma_collinear4
      have : Col p r K := by forward_using lemma_collinearorder
      have : Col A B K := by conclude lemma_collinear5
      have : Meet A B c d := by conclude_def Meet
      contradict
  have : BetS c E p := by conclude lemma_collinearbetween
  have : BetS p E c := by conclude axiom_betweennesssymmetry
  have : BetS q p E := by conclude axiom_innertransitivity
  have : nCol p r c := by conclude lemma_NChelper
  have : nCol p c r := by forward_using lemma_NCorder
  have : Col q p c := by conclude_def Col
  have : Col p c q := by forward_using lemma_collinearorder
  have : c = c := by conclude cn_equalityreflexive
  have : Col p c c := by conclude_def Col
  have : q ≠ c := by forward_using lemma_betweennotequal
  have : nCol q c r := by conclude lemma_NChelper
  have : nCol q r c := by forward_using lemma_NCorder
  have : q ≠ d := by forward_using lemma_betweennotequal
  have : Col q r d := by conclude_def Col
  have : q = q := by conclude cn_equalityreflexive
  have : Col q r q := by conclude_def Col
  have : nCol q d c := by conclude lemma_NChelper
  have : nCol d c q := by forward_using lemma_NCorder
  have : Col C c d := by conclude_def Col
  have : Col d c C := by forward_using lemma_collinearorder
  have : d = d := by conclude cn_equalityreflexive
  have : Col d c d := by conclude_def Col
  have : C ≠ d := by forward_using lemma_betweennotequal
  have : d ≠ C := by conclude lemma_inequalitysymmetric
  have : nCol d C q := by conclude lemma_NChelper
  have : nCol d q C := by forward_using lemma_NCorder
  have : Col q r d := by conclude_def Col
  have : Col d q r := by forward_using lemma_collinearorder
  have : Col d q q := by conclude_def Col
  have : ¬ r = C := by
      intro h
      have : Col A B C := by conclude cn_equalitysub
      have : Meet A B c d := by conclude_def Meet
      contradict
  have : ¬ r = q := by
      intro h
      have : Col r q c := by conclude_def Col
      have : Col q r c := by forward_using lemma_collinearorder
      contradict
  have : nCol r q C := by conclude lemma_NChelper
  have : nCol r C q := by forward_using lemma_NCorder
  have : BetS r E C := by conclude axiom_betweennesssymmetry
  obtain ⟨F, _, _⟩ : ∃ F, (BetS q F C ∧ BetS r p F) := by conclude postulate_Pasch_outer
  have : BetS C F q := by conclude axiom_betweennesssymmetry
  have : Col r p F := by conclude_def Col
  have : Col r p A := by forward_using lemma_collinearorder
  have : Col r p B := by forward_using lemma_collinearorder
  have : Col A B F := by conclude lemma_collinear5
  have : r = r := by conclude cn_equalityreflexive
  have : Col d q r := by conclude_def Col
  have : q ≠ r := by forward_using lemma_betweennotequal
  have : nCol q r C := by conclude lemma_NChelper
  have : nCol q C r := by forward_using lemma_NCorder
  have : Col q F C := by conclude_def Col
  have : Col q C F := by forward_using lemma_collinearorder
  have : C = C := by conclude cn_equalityreflexive
  have : Col q C C := by conclude_def Col
  have : F ≠ C := by forward_using lemma_betweennotequal
  have : nCol F C r := by conclude lemma_NChelper
  have : nCol F r C := by forward_using lemma_NCorder
  have : Col B r p := by conclude lemma_collinear4
  have : Col B p r := by forward_using lemma_collinearorder
  have : Col B p A := by forward_using lemma_collinearorder
  have : Col B A r := by forward_using lemma_collinearorder
  have : Col B A p := by forward_using lemma_collinearorder
  have : Col A r p := by conclude lemma_collinear4
  have : Col p r A := by forward_using lemma_collinearorder
  have : Col p r F := by forward_using lemma_collinearorder
  have : p ≠ r := by forward_using lemma_betweennotequal
  have : Col r A F := by conclude lemma_collinear4
  have : Col F r A := by forward_using lemma_collinearorder
  have : Col B A r := by forward_using lemma_collinearorder
  have : Col B A p := by forward_using lemma_collinearorder
  have : Col A r p := by conclude lemma_collinear4
  have : Col A p r := by forward_using lemma_collinearorder
  have : Col A p B := by forward_using lemma_collinearorder
  have : Col A B r := by forward_using lemma_collinearorder
  have : Col A B p := by forward_using lemma_collinearorder
  have : Col B r p := by conclude lemma_collinear4
  have : Col p r B := by forward_using lemma_collinearorder
  have : Col r B F := by conclude lemma_collinear4
  have : Col F r B := by forward_using lemma_collinearorder
  have : nCol A B C := by conclude lemma_NChelper
  have : TS C A B q := by conclude_def TS
  have : OS C d A B := by conclude_def OS
  have : ¬ Meet A B C d := by
      intro h
      obtain ⟨K, _, _, _, _⟩ : ∃ K, (A ≠ B ∧ C ≠ d ∧ Col A B K ∧ Col C d K) := by conclude_def Meet
      have : Col C c d := by conclude_def Col
      have : Col C d c := by forward_using lemma_collinearorder
      have : C ≠ d := by forward_using lemma_betweennotequal
      have : Col d c K := by conclude lemma_collinear4
      have : Col c d K := by forward_using lemma_collinearorder
      have : Meet A B c d := by conclude_def Meet
      contradict
  have : C ≠ d := by forward_using lemma_betweennotequal
  have : TP A B C d := by conclude_def TP
  close

end GeocoqTranslate.Elements
