/- Transpiled from ../theories/Elements/OriginalProofs/lemma_congruencesymmetric.v :: lemma_congruencesymmetric
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

theorem lemma_congruencesymmetric :
    ∀ (A B C D : Point), Cong B C A D → Cong A D B C := by
  intro A B C D h1
  have : Cong B C B C := by conclude cn_congruencereflexive
  have : Cong A D B C := by conclude cn_congruencetransitive
  close

end GeocoqTranslate.Elements
