/- Transpiled from ../theories/Elements/OriginalProofs/lemma_extension.v :: lemma_extension
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_extension :
    ∀ (A B P Q : Point), A ≠ B → P ≠ Q → ∃ X, BetS A B X ∧ Cong B X P Q := by
  intro A B P Q h1 h2
  have : B = B := by conclude cn_equalityreflexive
  sorry -- TODO: assert (exists D, Cong B D P Q).
  rcases (show B = P ∨ B ≠ P by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
  · have : Q ≠ P := by conclude lemma_inequalitysymmetric
    have : Q ≠ B := by conclude cn_equalitysub
    have : B ≠ Q := by conclude lemma_inequalitysymmetric
    obtain ⟨D, _⟩ : ∃ D, Cong B D Q P := by conclude proposition_02
    have : Cong B D P Q := by forward_using lemma_congruenceflip
    close
  · obtain ⟨D, _⟩ : ∃ D, Cong B D P Q := by conclude proposition_02
    sorry -- TODO: exists D;auto.
  sorry -- TODO: destruct H2 as [D];spliter.
  have : Cong P Q B D := by conclude lemma_congruencesymmetric
  have : B ≠ D := by conclude axiom_nocollapse
  obtain ⟨J, _⟩ : ∃ J, CI J B B D := by conclude postulate_Euclid3
  have : InCirc B J := by conclude_def InCirc
  obtain ⟨C, E, _, _, _, _, _⟩ : ∃ C E, (Col A B C ∧ BetS A B E ∧ OnCirc C J ∧ OnCirc E J ∧ BetS C B E) := by conclude postulate_line_circle
  have : Cong B E B D := by conclude axiom_circle_center_radius
  have : Cong B E P Q := by conclude lemma_congruencetransitive
  close

end GeocoqTranslate.Elements
