/- Transpiled from ../theories/Elements/OriginalProofs/lemma_angleordertransitive.v :: lemma_angleordertransitive
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoff
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.proposition_04
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crossbar
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_angleordertransitive :
    ∀ (A B C D E F P Q R : Point), LtA A B C D E F → LtA D E F P Q R → LtA A B C P Q R := by
  intro A B C D E F P Q R h1 h2
  obtain ⟨U, V, W, _, _, _, _⟩ : ∃ U V W, (BetS U W V ∧ Out Q P U ∧ Out Q R V ∧ CongA D E F P Q W) := by conclude_def LtA
  have : CongA P Q W D E F := by conclude lemma_equalanglessymmetric
  have : D ≠ E := by forward_using lemma_angledistinct
  have : E ≠ D := by conclude lemma_inequalitysymmetric
  have : E ≠ F := by forward_using lemma_angledistinct
  have : Q ≠ U := by conclude lemma_raystrict
  obtain ⟨G, _, _⟩ : ∃ G, (Out E D G ∧ Cong E G Q U) := by conclude lemma_layoff
  have : Q ≠ W := by forward_using lemma_angledistinct
  obtain ⟨J, _, _⟩ : ∃ J, (Out E F J ∧ Cong E J Q W) := by conclude lemma_layoff
  have : nCol D E F := by conclude lemma_equalanglesNC
  have : CongA D E F D E F := by conclude lemma_equalanglesreflexive
  have : CongA D E F G E J := by conclude lemma_equalangleshelper
  have : CongA G E J D E F := by conclude lemma_equalanglessymmetric
  have : CongA G E J P Q W := by conclude lemma_equalanglestransitive
  have : W = W := by conclude cn_equalityreflexive
  have : Out Q W W := by conclude lemma_ray4
  have : CongA G E J U Q W := by conclude lemma_equalangleshelper
  have : nCol G E J := by conclude lemma_equalanglesNC
  have : nCol U Q W := by conclude lemma_equalanglesNC
  have : Triangle G E J := by (try (have : nCol G E J := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Triangle U Q W := by (try (have : nCol U Q W := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Cong G J U W := by conclude proposition_04
  have : W = W := by conclude cn_equalityreflexive
  have : CongA D E F U Q W := by conclude lemma_equalangleshelper
  have : CongA U Q W D E F := by conclude lemma_equalanglessymmetric
  have : CongA D E F U Q W := by conclude lemma_equalangleshelper
  have : LtA A B C U Q W := by conclude lemma_angleorderrespectscongruence
  obtain ⟨H, S, T, _, _, _, _⟩ : ∃ H S T, (BetS S H T ∧ Out Q U S ∧ Out Q W T ∧ CongA A B C U Q H) := by conclude_def LtA
  have : Out Q U P := by conclude lemma_ray5
  have : Q ≠ H := by forward_using lemma_angledistinct
  have : H = H := by conclude cn_equalityreflexive
  have : Out Q H H := by conclude lemma_ray4
  have : CongA A B C P Q H := by conclude lemma_equalangleshelper
  have : CongA D E F P Q T := by conclude lemma_equalangleshelper
  have : nCol P Q T := by conclude lemma_equalanglesNC
  have : Triangle P Q T := by (try (have : nCol P Q T := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Q ≠ P := by conclude lemma_ray2
  have : Out Q T W := by conclude lemma_ray5
  have : ¬ Col S Q T := by
      intro h
      have : Col Q U S := by conclude lemma_rayimpliescollinear
      have : Col U Q S := by forward_using lemma_collinearorder
      have : Col Q P U := by conclude lemma_rayimpliescollinear
      have : Col U Q P := by forward_using lemma_collinearorder
      have : Q ≠ U := by conclude lemma_raystrict
      have : U ≠ Q := by conclude lemma_inequalitysymmetric
      have : Col Q S P := by conclude lemma_collinear4
      have : Col S Q P := by forward_using lemma_collinearorder
      have : Q ≠ S := by conclude lemma_raystrict
      have : S ≠ Q := by conclude lemma_inequalitysymmetric
      have : Col Q T P := by conclude lemma_collinear4
      have : Col P Q T := by forward_using lemma_collinearorder
      contradict
  have : Triangle S Q T := by (try (have : nCol S Q T := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Out Q S U := by conclude lemma_ray5
  obtain ⟨K, _, _⟩ : ∃ K, (Out Q H K ∧ BetS U K W) := by conclude lemma_crossbar
  have : BetS U K V := by conclude lemma_3_6b
  have : P = P := by conclude cn_equalityreflexive
  have : Out Q P P := by conclude lemma_ray4
  have : CongA A B C P Q K := by conclude lemma_equalangleshelper
  have : LtA A B C P Q R := by conclude_def LtA
  close

end GeocoqTranslate.Elements
