/- Transpiled from ../theories/Elements/OriginalProofs/lemma_supplements2.v :: lemma_supplements2
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplements

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_supplements2 :
    ∀ (A B C D E F J K L P Q R : Point), RT A B C P Q R → CongA A B C J K L → RT J K L D E F → CongA P Q R D E F ∧ CongA D E F P Q R := by
  intro A B C D E F J K L P Q R h1 h2 h3
  obtain ⟨a, b, c, d, e, _, _, _⟩ : ∃ a b c d e, (Supp a b c d e ∧ CongA A B C a b c ∧ CongA P Q R d b e) := by conclude_def RT
  obtain ⟨j, k, l, m, n, _, _, _⟩ : ∃ j k l m n, (Supp j k l m n ∧ CongA J K L j k l ∧ CongA D E F m k n) := by conclude_def RT
  have : CongA a b c A B C := by conclude lemma_equalanglessymmetric
  have : CongA a b c J K L := by conclude lemma_equalanglestransitive
  have : CongA a b c j k l := by conclude lemma_equalanglestransitive
  have : CongA d b e m k n := by conclude lemma_supplements
  have : CongA P Q R m k n := by conclude lemma_equalanglestransitive
  have : CongA m k n D E F := by conclude lemma_equalanglessymmetric
  have : CongA P Q R D E F := by conclude lemma_equalanglestransitive
  have : CongA D E F P Q R := by conclude lemma_equalanglessymmetric
  close

end GeocoqTranslate.Elements
