/- Transpiled from ../theories/Elements/OriginalProofs/lemma_tarskiparallelflip.v :: lemma_tarskiparallelflip
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

set_option maxHeartbeats 800000 in
theorem lemma_tarskiparallelflip :
    ∀ (A B C D : Point), TP A B C D → TP B A C D ∧ TP A B D C ∧ TP B A D C := by
  intro A B C D h1
  have : (A ≠ B ∧ C ≠ D ∧ ¬ Meet A B C D ∧ OS C D A B) := by conclude_def TP
  have : OS D C A B := by forward_using lemma_samesidesymmetric
  have : D ≠ C := by conclude lemma_inequalitysymmetric
  have : ¬ Meet A B D C := by
      intro h
      obtain ⟨T, _, _, _, _⟩ : ∃ T, (A ≠ B ∧ D ≠ C ∧ Col A B T ∧ Col D C T) := by conclude_def Meet
      have : Col C D T := by perm_close
      have : C ≠ D := by conclude lemma_inequalitysymmetric
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : TP A B D C := by conclude_def TP
  have : ¬ Meet B A C D := by
      intro h
      obtain ⟨T, _, _, _, _⟩ : ∃ T, (B ≠ A ∧ C ≠ D ∧ Col B A T ∧ Col C D T) := by conclude_def Meet
      have : Col A B T := by perm_close
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : OS D C A B := by forward_using lemma_samesidesymmetric
  have : OS C D B A := by forward_using lemma_samesidesymmetric
  have : OS D C B A := by forward_using lemma_samesidesymmetric
  have : TP B A C D := by conclude_def TP
  have : ¬ Meet B A D C := by
      intro h
      obtain ⟨T, _, _, _, _⟩ : ∃ T, (B ≠ A ∧ D ≠ C ∧ Col B A T ∧ Col D C T) := by conclude_def Meet
      have : Col A B T := by perm_close
      have : Col C D T := by perm_close
      have : Meet A B C D := by conclude_def Meet
      contradict
  have : TP B A D C := by conclude_def TP
  obtain ⟨Q, P, R, _, _, _, _, _, _⟩ : ∃ Q P R, (Col A B P ∧ Col A B R ∧ BetS C P Q ∧ BetS D R Q ∧ nCol A B C ∧ nCol A B D) := by conclude_def OS
  close

end GeocoqTranslate.Elements
