/- Transpiled from ../theories/Elements/OriginalProofs/lemma_angledistinct.v :: lemma_angledistinct
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_angledistinct :
    ∀ (A B C a b c : Point), CongA A B C a b c → A ≠ B ∧ B ≠ C ∧ A ≠ C ∧ a ≠ b ∧ b ≠ c ∧ a ≠ c := by
  intro A B C a b c h1
  have : nCol A B C := by conclude_def CongA
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : ¬ A = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : CongA a b c A B C := by conclude lemma_equalanglessymmetric
  have : nCol a b c := by conclude_def CongA
  have : ¬ a = b := by
      intro h
      have : Col a b c := by conclude_def Col
      contradict
  have : ¬ b = c := by
      intro h
      have : Col a b c := by conclude_def Col
      contradict
  have : ¬ a = c := by
      intro h
      have : Col a b c := by conclude_def Col
      contradict
  close

end GeocoqTranslate.Elements
