/- Transpiled from ../theories/Elements/OriginalProofs/lemma_TTorder.v :: lemma_TTorder
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_TGsymmetric

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_TTorder :
    ∀ (A B C D E F G H : Point), TT A B C D E F G H → TT C D A B E F G H := by
  intro A B C D E F G H h1
  obtain ⟨J, _, _, _⟩ : ∃ J, (BetS E F J ∧ Cong F J G H ∧ TG A B C D E J) := by conclude_def TT
  have : TG C D A B E J := by conclude lemma_TGsymmetric
  have : TT C D A B E F G H := by conclude_def TT
  close

end GeocoqTranslate.Elements
