/- Transpiled from ../theories/Elements/OriginalProofs/lemma_PGrotate.v :: lemma_PGrotate
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

set_option maxHeartbeats 800000 in
theorem lemma_PGrotate :
    ∀ (A B C D : Point), PG A B C D → PG B C D A := by
  intro A B C D h1
  have : (Par A B C D ∧ Par A D B C) := by conclude_def PG
  have : Par B C A D := by conclude lemma_parallelsymmetric
  have : Par B C D A := by forward_using lemma_parallelflip
  have : Par B A C D := by forward_using lemma_parallelflip
  have : PG B C D A := by conclude_def PG
  close

end GeocoqTranslate.Elements
