/- Transpiled from ../theories/Elements/OriginalProofs/lemma_35helper.v :: lemma_35helper
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsmeet
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearbetween
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthantransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

theorem lemma_35helper :
    ∀ (A B C D E F : Point), PG A B C D → PG E B C F → BetS A D F → Col A E F → BetS A E F := by
  intro A B C D E F h1 h2 h3 h4
  have : (Par A B C D ∧ Par A D B C) := by conclude_def PG
  have : (Par E B C F ∧ Par E F B C) := by conclude_def PG
  have : Par A B D C := by forward_using lemma_parallelflip
  have : Par E B F C := by forward_using lemma_parallelflip
  have : Cong A D B C := by forward_using proposition_34
  have : Cong E F B C := by forward_using proposition_34
  have : Cong B C E F := by conclude lemma_congruencesymmetric
  have : Cong A D E F := by conclude lemma_congruencetransitive
  have : Col A D F := by conclude_def Col
  have : Col F A E := by forward_using lemma_collinearorder
  have : Col F A D := by forward_using lemma_collinearorder
  have : A ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ A := by conclude lemma_inequalitysymmetric
  have : Col A E D := by conclude lemma_collinear4
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M C ∧ BetS B M D) := by conclude lemma_diagonalsmeet
  have : BetS D M B := by conclude axiom_betweennesssymmetry
  have : BetS C M A := by conclude axiom_betweennesssymmetry
  have : BetS B M D := by conclude axiom_betweennesssymmetry
  obtain ⟨m, _, _⟩ : ∃ m, (BetS E m C ∧ BetS B m F) := by conclude lemma_diagonalsmeet
  have : BetS F m B := by conclude axiom_betweennesssymmetry
  have : BetS B m F := by conclude axiom_betweennesssymmetry
  have : nCol A D B := by forward_using lemma_parallelNC
  have : Col A D F := by conclude_def Col
  have : A = A := by conclude cn_equalityreflexive
  have : Col A D A := by conclude_def Col
  have : nCol A F B := by conclude lemma_NChelper
  obtain ⟨Q, _, _⟩ : ∃ Q, (BetS B Q F ∧ BetS A M Q) := by conclude postulate_Pasch_outer
  have : Col A M Q := by conclude_def Col
  have : Col A M C := by conclude_def Col
  have : Col M A Q := by forward_using lemma_collinearorder
  have : Col M A C := by forward_using lemma_collinearorder
  have : A ≠ M := by forward_using lemma_betweennotequal
  have : M ≠ A := by conclude lemma_inequalitysymmetric
  have : Col A Q C := by conclude lemma_collinear4
  have : A = A := by conclude cn_equalityreflexive
  have : C = C := by conclude cn_equalityreflexive
  have : Col F A A := by conclude_def Col
  have : Col C C B := by conclude_def Col
  have : A ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ A := by conclude lemma_inequalitysymmetric
  have : B ≠ C := by conclude_def Par
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : ¬ Meet F A C B := by
      intro h
      obtain ⟨p, _, _, _, _⟩ : ∃ p, (F ≠ A ∧ C ≠ B ∧ Col F A p ∧ Col C B p) := by conclude_def Meet
      have : Col A D F := by conclude_def Col
      have : Col F A D := by forward_using lemma_collinearorder
      have : A ≠ D := by forward_using lemma_betweennotequal
      have : Col A D p := by conclude lemma_collinear4
      have : Col B C p := by forward_using lemma_collinearorder
      have : Meet A D B C := by conclude_def Meet
      have : ¬ Meet A D B C := by conclude_def Par
      contradict
  have : BetS F Q B := by conclude axiom_betweennesssymmetry
  have : ¬ Meet A D B C := by conclude_def Par
  have : Col A C Q := by forward_using lemma_collinearorder
  have : BetS A Q C := by conclude lemma_collinearbetween
  have : BetS C Q A := by conclude axiom_betweennesssymmetry
  have : ¬ A = E := by
      intro h
      have : Cong A F A F := by conclude cn_congruencereflexive
      have : Cong A F E F := by conclude cn_equalitysub
      have : Cong E F A D := by conclude lemma_congruencesymmetric
      have : Cong A F A D := by conclude lemma_congruencetransitive
      have : Cong A D A F := by conclude lemma_congruencesymmetric
      have : Cong A D A D := by conclude cn_congruencereflexive
      have : Lt A D A F := by conclude_def Lt
      have : Lt A F A F := by conclude lemma_lessthancongruence2
      have : ¬ Lt A F A F := by conclude lemma_trichotomy2
      contradict
  have : ¬ BetS A F E := by
      intro h
      have : BetS E F A := by conclude axiom_betweennesssymmetry
      have : nCol A D C := by forward_using lemma_parallelNC
      have : Col A D E := by forward_using lemma_collinearorder
      have : nCol A E C := by conclude lemma_NChelper
      have : nCol C A E := by forward_using lemma_NCorder
      obtain ⟨r, _, _⟩ : ∃ r, (BetS C r F ∧ BetS E r Q) := by conclude postulate_Pasch_inner
      have : BetS Q r E := by conclude axiom_betweennesssymmetry
      have : nCol E B F := by forward_using lemma_parallelNC
      have : nCol F B E := by forward_using lemma_NCorder
      obtain ⟨H, _, _⟩ : ∃ H, (BetS E H B ∧ BetS F r H) := by conclude postulate_Pasch_outer
      have : Col E H B := by conclude_def Col
      have : Col F r H := by conclude_def Col
      have : Col E B H := by forward_using lemma_collinearorder
      have : Col C r F := by conclude_def Col
      have : Col r F C := by forward_using lemma_collinearorder
      have : Col r F H := by forward_using lemma_collinearorder
      have : r ≠ F := by forward_using lemma_betweennotequal
      have : Col F C H := by conclude lemma_collinear4
      have : B ≠ E := by forward_using lemma_NCdistinct
      have : E ≠ B := by conclude lemma_inequalitysymmetric
      have : F ≠ C := by conclude_def Par
      have : Meet E B F C := by conclude_def Meet
      have : ¬ Meet E B F C := by conclude_def Par
      contradict
  have : Col A F E := by forward_using lemma_collinearorder
  have : (A = F ∨ A = E ∨ F = E ∨ BetS F A E ∨ BetS A F E ∨ BetS A E F) := by conclude_def Col
  have : BetS A E F := by
      rcases (show A = F ∨ A = E ∨ F = E ∨ BetS F A E ∨ BetS A F E ∨ BetS A E F by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
      · have : ¬ ¬ BetS A E F := by
            intro h
            have : BetS A D A := by conclude cn_equalitysub
            have : ¬ BetS A D A := by conclude axiom_betweennessidentity
            contradict
        close
      · have : ¬ ¬ BetS A E F := by
            intro h
            contradict
        close
      · have : ¬ ¬ BetS A E F := by
            intro h
            have : E = F := by conclude lemma_equalitysymmetric
            have : Col B E F := by conclude_def Col
            have : Col E B F := by forward_using lemma_collinearorder
            have : F = F := by conclude cn_equalityreflexive
            have : Col F C F := by conclude_def Col
            have : E ≠ B := by conclude_def Par
            have : F ≠ C := by conclude_def Par
            have : Meet E B F C := by conclude_def Meet
            have : ¬ Meet E B F C := by conclude_def Par
            contradict
        close
      · have : ¬ ¬ BetS A E F := by
            intro h
            have : BetS F D A := by conclude axiom_betweennesssymmetry
            have : BetS D A E := by conclude lemma_3_6a
            have : Cong D A D A := by conclude cn_congruencereflexive
            have : Lt D A D E := by conclude_def Lt
            have : Cong D A A D := by conclude cn_equalityreverse
            have : Lt A D D E := by conclude lemma_lessthancongruence2
            have : Cong D E E D := by conclude cn_equalityreverse
            have : Lt A D E D := by conclude lemma_lessthancongruence
            have : Cong A D A D := by conclude cn_congruencereflexive
            have : Lt A D A F := by conclude_def Lt
            have : Cong A D D A := by conclude cn_equalityreverse
            have : Lt D A A F := by conclude lemma_lessthancongruence2
            have : Cong A F F A := by conclude cn_equalityreverse
            have : Lt D A F A := by conclude lemma_lessthancongruence
            have : Cong F A F A := by conclude cn_congruencereflexive
            have : Lt F A F E := by conclude_def Lt
            have : Lt D A F E := by conclude lemma_lessthantransitive
            have : Cong D A F E := by forward_using lemma_congruenceflip
            have : Lt F E F E := by conclude lemma_lessthancongruence2
            have : ¬ Lt F E F E := by conclude lemma_trichotomy2
            contradict
        close
      · have : ¬ ¬ BetS A E F := by
            intro h
            contradict
        close
      · close
  close

end GeocoqTranslate.Elements
