/- Transpiled from ../theories/Elements/OriginalProofs/lemma_betweennesspreserved.v :: lemma_betweennesspreserved
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_localextension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_betweennesspreserved :
    ∀ (A B C a b c : Point), Cong A B a b → Cong A C a c → Cong B C b c → BetS A B C → BetS a b c := by
  intro A B C a b c h1 h2 h3 h4
  have : A ≠ B := by forward_using lemma_betweennotequal
  have : a ≠ b := by conclude axiom_nocollapse
  have : B ≠ C := by forward_using lemma_betweennotequal
  have : b ≠ c := by conclude axiom_nocollapse
  obtain ⟨d, _, _⟩ : ∃ d, (BetS a b d ∧ Cong b d b c) := by conclude lemma_localextension
  have : Cong b c b d := by conclude lemma_congruencesymmetric
  have : Cong b c B C := by conclude lemma_congruencesymmetric
  have : Cong b d B C := by conclude cn_congruencetransitive
  have : Cong B C b d := by conclude lemma_congruencesymmetric
  have : Cong C C c d := by conclude axiom_5_line
  have : Cong c d C C := by conclude lemma_congruencesymmetric
  have : ¬ c ≠ d := by
      intro h
      have : C ≠ C := by conclude axiom_nocollapse
      have : C = C := by conclude cn_equalityreflexive
      contradict
  have : BetS a b c := by conclude cn_equalitysub
  close

end GeocoqTranslate.Elements
