/- Transpiled from ../theories/Elements/OriginalProofs/lemma_together2.v :: lemma_together2
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_tworays
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_together
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_trichotomy2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthanadditive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthantransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_outerconnectivity
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_together2 :
    ∀ (A B C F G M N a b c : Point), TG A a C c B b → Cong F G B b → Out F G M → Cong F M A a → Out G F N → Cong G N C c → Out M F N := by
  intro A B C F G M N a b c h1 h2 h3 h4 h5 h6
  obtain ⟨J, _, _, _⟩ : ∃ J, (BetS A a J ∧ Cong a J C c ∧ Lt B b A J) := by conclude_def TG
  have : a ≠ J := by forward_using lemma_betweennotequal
  have : C ≠ c := by conclude axiom_nocollapse
  have : ¬ M = N := by
      intro h
      have : Out F G N := by conclude cn_equalitysub
      have : Out G F M := by conclude cn_equalitysub
      have : BetS F M G := by conclude lemma_tworays
      have : Cong G M C c := by conclude cn_equalitysub
      have : Cong M G C c := by forward_using lemma_congruenceflip
      have : Lt F G F G := by conclude lemma_together
      have : ¬ Lt F G F G := by conclude lemma_trichotomy2
      contradict
  have : F ≠ M := by conclude lemma_raystrict
  have : M ≠ F := by conclude lemma_inequalitysymmetric
  obtain ⟨D, _, _⟩ : ∃ D, (BetS M F D ∧ Cong F D M F) := by conclude lemma_extension
  have : (BetS F M G ∨ G = M ∨ BetS F G M) := by conclude lemma_ray1
  have : BetS G F D := by
      rcases (show BetS F M G ∨ G = M ∨ BetS F G M by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · have : BetS G M F := by conclude axiom_betweennesssymmetry
        have : BetS G F D := by conclude lemma_3_7a
        close
      · have : BetS G F D := by conclude cn_equalitysub
        close
      · have : BetS M G F := by conclude axiom_betweennesssymmetry
        have : BetS G F D := by conclude lemma_3_6a
        close
  have : BetS D F M := by conclude axiom_betweennesssymmetry
  have : BetS D F G := by conclude axiom_betweennesssymmetry
  have : ¬ BetS F M N := by
      intro h
      have : F ≠ M := by forward_using lemma_betweennotequal
      obtain ⟨P, _, _⟩ : ∃ P, (BetS F M P ∧ Cong M P C c) := by conclude lemma_extension
      have : Lt F G F P := by conclude lemma_together
      have : Cong C c G N := by conclude lemma_congruencesymmetric
      have : Cong C c N G := by forward_using lemma_congruenceflip
      have : Cong M P N G := by conclude lemma_congruencetransitive
      have : Cong F M F M := by conclude cn_congruencereflexive
      have : Lt F M F N := by conclude_def Lt
      have : ¬ BetS F N G := by
          intro h
          have : Lt F P F G := by conclude lemma_lessthanadditive
          have : Lt F G F G := by conclude lemma_lessthantransitive
          have : ¬ Lt F G F G := by conclude lemma_trichotomy2
          contradict
      have : ¬ BetS G N F := by
          intro h
          have : BetS F N G := by conclude axiom_betweennesssymmetry
          contradict
      have : (BetS G N F ∨ F = N ∨ BetS G F N) := by conclude lemma_ray1
      have : F ≠ N := by forward_using lemma_betweennotequal
      have : ¬ ¬ BetS G F N := by
          intro h
          contradict
      have : BetS N F G := by conclude axiom_betweennesssymmetry
      have : ¬ ¬ BetS N F M := by
          intro h
          have : ¬ BetS F M G := by
              intro h
              have : BetS N F M := by conclude axiom_innertransitivity
              contradict
          have : ¬ BetS F G M := by
              intro h
              have : BetS N F M := by conclude lemma_3_7b
              contradict
          have : G = M := by conclude lemma_outerconnectivity
          have : BetS N F M := by conclude cn_equalitysub
          contradict
      have : BetS N F N := by conclude lemma_3_7b
      have : ¬ BetS N F N := by conclude axiom_betweennessidentity
      contradict
  have : Col G F N := by conclude lemma_rayimpliescollinear
  have : Col F G M := by conclude lemma_rayimpliescollinear
  have : Col G F M := by forward_using lemma_collinearorder
  have : F ≠ G := by forward_using lemma_betweennotequal
  have : G ≠ F := by conclude lemma_inequalitysymmetric
  have : Col F N M := by conclude lemma_collinear4
  have : Col M F N := by forward_using lemma_collinearorder
  have : (M = F ∨ M = N ∨ F = N ∨ BetS F M N ∨ BetS M F N ∨ BetS M N F) := by conclude_def Col
  have : Out M F N := by
      rcases (show M = F ∨ M = N ∨ F = N ∨ BetS F M N ∨ BetS M F N ∨ BetS M N F by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
      · have : ¬ ¬ Out M F N := by
            intro h
            contradict
        close
      · have : ¬ ¬ Out M F N := by
            intro h
            contradict
        close
      · have : N = F := by conclude lemma_equalitysymmetric
        have : Out M F N := by conclude lemma_ray4
        close
      · have : ¬ ¬ Out M F N := by
            intro h
            contradict
        close
      · have : Out M F N := by conclude lemma_ray4
        close
      · have : Out M F N := by conclude lemma_ray4
        close
  close

end GeocoqTranslate.Elements
