/- Transpiled from ../theories/Elements/OriginalProofs/lemma_tworays.v :: lemma_tworays
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_tworays :
    ∀ (A B C : Point), Out A B C → Out B A C → BetS A C B := by
  intro A B C h1 h2
  have : (BetS A C B ∨ B = C ∨ BetS A B C) := by conclude lemma_ray1
  have : (BetS B C A ∨ A = C ∨ BetS B A C) := by conclude lemma_ray1
  have : BetS A C B := by
      rcases (show BetS A C B ∨ B = C ∨ BetS A B C by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · close
      · have : ¬ ¬ BetS A C B := by
            intro h
            have : B ≠ C := by conclude lemma_raystrict
            contradict
        close
      · have : BetS A C B := by
            rcases (show BetS B C A ∨ A = C ∨ BetS B A C by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
            · have : BetS A C B := by conclude axiom_betweennesssymmetry
              close
            · have : ¬ ¬ BetS A C B := by
                  intro h
                  have : A ≠ C := by conclude lemma_raystrict
                  contradict
              close
            · have : ¬ ¬ BetS A C B := by
                  intro h
                  have : BetS A B A := by conclude axiom_innertransitivity
                  have : ¬ BetS A B A := by conclude axiom_betweennessidentity
                  contradict
              close
        close
  close

end GeocoqTranslate.Elements
