/- Transpiled from ../theories/Elements/OriginalProofs/lemma_crossbar2.v :: lemma_crossbar2
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray3
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crossbar
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoff
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.proposition_04
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_sameside2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.proposition_07
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angledistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_crossbar2 :
    ∀ (A G H P S T : Point), LtA H G A H G P → OS A P G H → Out G H S → Out G P T → ∃ X, BetS T X S ∧ Out G A X := by
  intro A G H P S T h1 h2 h3 h4
  have : nCol G H P := by conclude_def OS
  obtain ⟨J, K, L, _, _, _, _⟩ : ∃ J K L, (BetS L K J ∧ Out G H L ∧ Out G P J ∧ CongA H G A H G K) := by conclude_def LtA
  have : nCol H G K := by conclude lemma_equalanglesNC
  have : ¬ Col L G J := by
      intro h
      have : Col G H L := by conclude lemma_rayimpliescollinear
      have : Col G P J := by conclude lemma_rayimpliescollinear
      have : Col L G H := by forward_using lemma_collinearorder
      have : G ≠ L := by conclude lemma_raystrict
      have : L ≠ G := by conclude lemma_inequalitysymmetric
      have : Col G J H := by conclude lemma_collinear4
      have : Col J G H := by forward_using lemma_collinearorder
      have : Col J G P := by forward_using lemma_collinearorder
      have : G ≠ J := by conclude lemma_raystrict
      have : J ≠ G := by conclude lemma_inequalitysymmetric
      have : Col G H P := by conclude lemma_collinear4
      contradict
  have : Triangle L G J := by (try (have : nCol L G J := nCol_notCol _ _ _ (by assumption))); conclude_def Triangle
  have : Out G J T := by conclude lemma_ray3
  have : Out G L S := by conclude lemma_ray3
  obtain ⟨M, _, _⟩ : ∃ M, (Out G K M ∧ BetS S M T) := by conclude lemma_crossbar
  have : BetS T M S := by conclude axiom_betweennesssymmetry
  have : CongA H G K H G A := by conclude lemma_equalanglessymmetric
  have : G ≠ A := by forward_using lemma_angledistinct
  have : G ≠ M := by conclude lemma_raystrict
  obtain ⟨N, _, _⟩ : ∃ N, (Out G A N ∧ Cong G N G M) := by conclude lemma_layoff
  have : H = H := by conclude cn_equalityreflexive
  have : ¬ G = H := by
      intro h
      have : Col G H P := by conclude_def Col
      contradict
  have : Out G H H := by conclude lemma_ray4
  have : ¬ Col H G M := by
      intro h
      have : Col G K M := by conclude lemma_rayimpliescollinear
      have : Col M G K := by forward_using lemma_collinearorder
      have : Col M G H := by forward_using lemma_collinearorder
      have : G ≠ M := by conclude lemma_raystrict
      have : M ≠ G := by conclude lemma_inequalitysymmetric
      have : Col G K H := by conclude lemma_collinear4
      have : Col H G K := by forward_using lemma_collinearorder
      contradict
  have : CongA H G M H G M := by conclude lemma_equalanglesreflexive
  have : Out G M K := by conclude lemma_ray5
  have : CongA H G M H G K := by conclude lemma_equalangleshelper
  have : CongA H G M H G A := by conclude lemma_equalanglestransitive
  have : nCol H G A := by conclude lemma_equalanglesNC
  have : CongA H G A H G A := by conclude lemma_equalanglesreflexive
  have : CongA H G A H G N := by conclude lemma_equalangleshelper
  have : CongA H G M H G N := by conclude lemma_equalanglestransitive
  have : CongA H G N H G M := by conclude lemma_equalanglessymmetric
  have : Cong G H G H := by conclude cn_congruencereflexive
  have : Cong H N H M := by conclude proposition_04
  have : G = G := by conclude cn_equalityreflexive
  have : Col G G H := by conclude_def Col
  have : OS A T G H := by conclude lemma_sameside2
  have : S ≠ M := by forward_using lemma_betweennotequal
  have : Out S M T := by conclude lemma_ray4
  have : Out S T M := by conclude lemma_ray5
  have : Col G H S := by conclude lemma_rayimpliescollinear
  have : Col G S H := by forward_using lemma_collinearorder
  have : OS A M G H := by conclude lemma_sameside2
  have : OS M A G H := by forward_using lemma_samesidesymmetric
  have : OS M N G H := by conclude lemma_sameside2
  have : Cong N H M H := by forward_using lemma_congruenceflip
  have : Cong M H N H := by conclude lemma_congruencesymmetric
  have : Cong N G M G := by forward_using lemma_congruenceflip
  have : Cong M G N G := by conclude lemma_congruencesymmetric
  have : M = N := by conclude proposition_07
  have : N = M := by conclude lemma_equalitysymmetric
  have : Out G A M := by conclude cn_equalitysub
  close

end GeocoqTranslate.Elements
