/- Transpiled from ../theories/Elements/OriginalProofs/lemma_crossimpliesopposite.v :: lemma_crossimpliesopposite
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_crossimpliesopposite :
    ∀ (A B C D : Point), CR A B C D → nCol A C D → TS A C D B ∧ TS A D C B ∧ TS B C D A ∧ TS B D C A := by
  intro A B C D h1 h2
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M B ∧ BetS C M D) := by conclude_def CR
  have : Col C M D := by conclude_def Col
  have : Col C D M := by perm_close
  have : nCol C D A := by perm_close
  have : nCol D C A := by perm_close
  have : TS A C D B := by (try (have : nCol C D A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
  have : Col D C M := by perm_close
  have : TS A D C B := by (try (have : nCol D C A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
  have : TS B C D A := by conclude lemma_oppositesidesymmetric
  have : TS B D C A := by conclude lemma_oppositesidesymmetric
  close

end GeocoqTranslate.Elements
