/- Transpiled from ../theories/Elements/OriginalProofs/lemma_linereflectionisometry.v :: lemma_linereflectionisometry
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.proposition_10
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_3
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rightangleNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_pointreflectionisometry
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rightreverse
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennesspreserved
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extensionunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_linereflectionisometry :
    ∀ (A B C D E F : Point), Per B A C → Per A B D → BetS C A E → BetS D B F → Cong A C A E → Cong B D B F → Cong C D E F := by
  intro A B C D E F h1 h2 h3 h4 h5 h6
  obtain ⟨H, _, _, _, _⟩ : ∃ H, (BetS B A H ∧ Cong B A H A ∧ Cong B C H C ∧ A ≠ C) := by conclude_def Per
  obtain ⟨G, _, _, _, _⟩ : ∃ G, (BetS A B G ∧ Cong A B G B ∧ Cong A D G D ∧ B ≠ D) := by conclude_def Per
  have : A ≠ B := by forward_using lemma_betweennotequal
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M B ∧ Cong M A M B) := by conclude proposition_10
  have : Per D B A := by conclude lemma_8_2
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : BetS B M A := by conclude axiom_betweennesssymmetry
  have : Out B A M := by conclude lemma_ray4
  have : Per D B M := by conclude lemma_8_3
  have : nCol D B M := by conclude lemma_rightangleNC
  have : ¬ D = M := by
      intro h
      have : Col D B M := by conclude_def Col
      contradict
  have : M ≠ D := by conclude lemma_inequalitysymmetric
  obtain ⟨R, _, _⟩ : ∃ R, (BetS D M R ∧ Cong M R M D) := by conclude lemma_extension
  have : Cong D B B F := by forward_using lemma_congruenceflip
  have : Col D B F := by conclude_def Col
  have : B ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ B := by conclude lemma_inequalitysymmetric
  have : Per D B A := by conclude lemma_8_2
  have : Per F B A := by conclude lemma_collinearright
  have : Per F B M := by conclude lemma_8_3
  have : nCol F B M := by conclude lemma_rightangleNC
  have : ¬ F = M := by
      intro h
      have : Col F B M := by conclude_def Col
      contradict
  have : M ≠ F := by conclude lemma_inequalitysymmetric
  obtain ⟨Q, _, _⟩ : ∃ Q, (BetS F M Q ∧ Cong M Q M F) := by conclude lemma_extension
  have : Cong M D M R := by conclude lemma_congruencesymmetric
  have : Cong D M M R := by forward_using lemma_congruenceflip
  have : Midpoint D M R := by conclude_def Midpoint
  have : Cong M F M Q := by conclude lemma_congruencesymmetric
  have : Cong F M M Q := by forward_using lemma_congruenceflip
  have : Midpoint F M Q := by conclude_def Midpoint
  have : Cong M B M A := by conclude lemma_congruencesymmetric
  have : Cong B M M A := by forward_using lemma_congruenceflip
  have : BetS B M A := by conclude axiom_betweennesssymmetry
  have : Midpoint B M A := by conclude_def Midpoint
  have : Cong F B Q A := by conclude lemma_pointreflectionisometry
  have : Cong B F F B := by conclude cn_equalityreverse
  have : Cong B D F B := by conclude lemma_congruencetransitive
  have : Per C A B := by conclude lemma_8_2
  have : Out A B M := by conclude lemma_ray4
  have : Per C A M := by conclude lemma_8_3
  have : BetS Q M F := by conclude axiom_betweennesssymmetry
  have : BetS R M D := by conclude axiom_betweennesssymmetry
  have : Cong D B B F := by forward_using lemma_congruenceflip
  have : Cong D M F M := by conclude lemma_rightreverse
  have : Cong F M D M := by conclude lemma_congruencesymmetric
  have : Cong F M M Q := by forward_using lemma_congruenceflip
  have : Cong Q M F M := by forward_using lemma_congruenceflip
  have : Cong Q M D M := by conclude lemma_congruencetransitive
  have : Cong Q M M R := by conclude lemma_congruencetransitive
  have : Cong Q M R M := by forward_using lemma_congruenceflip
  have : Cong M F M D := by forward_using lemma_congruenceflip
  have : Cong C A A E := by forward_using lemma_congruenceflip
  have : Cong C M E M := by conclude lemma_rightreverse
  have : Cong E M C M := by conclude lemma_congruencesymmetric
  have : Cong M E M C := by forward_using lemma_congruenceflip
  have : Midpoint D M R := by conclude_def Midpoint
  have : Midpoint F M Q := by conclude_def Midpoint
  have : Cong M B M A := by conclude lemma_congruencesymmetric
  have : Cong B M M A := by forward_using lemma_congruenceflip
  have : Midpoint B M A := by conclude_def Midpoint
  have : Cong F B Q A := by conclude lemma_pointreflectionisometry
  have : nCol D B A := by conclude lemma_rightangleNC
  have : D ≠ B := by forward_using lemma_NCdistinct
  have : Cong D B R A := by conclude lemma_pointreflectionisometry
  have : Cong Q A F B := by conclude lemma_congruencesymmetric
  have : Cong B F D B := by conclude lemma_congruencesymmetric
  have : Cong F B D B := by forward_using lemma_congruenceflip
  have : Cong Q A D B := by conclude lemma_congruencetransitive
  have : Cong Q A R A := by conclude lemma_congruencetransitive
  have : Cong Q A A R := by forward_using lemma_congruenceflip
  have : D ≠ F := by forward_using lemma_betweennotequal
  have : Cong D F R Q := by conclude lemma_pointreflectionisometry
  have : Cong F D Q R := by forward_using lemma_congruenceflip
  have : BetS F B D := by conclude axiom_betweennesssymmetry
  have : Cong B D A R := by forward_using lemma_congruenceflip
  have : BetS Q A R := by conclude lemma_betweennesspreserved
  have : Midpoint Q A R := by conclude_def Midpoint
  have : Cong E A A C := by forward_using lemma_doublereverse
  have : BetS E A C := by conclude axiom_betweennesssymmetry
  have : Midpoint E A C := by conclude_def Midpoint
  have : Cong C D E F := by
      rcases (show E ≠ Q ∨ E = Q by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2
      · have : Cong E Q C R := by conclude lemma_pointreflectionisometry
        have : Cong Q E R C := by forward_using lemma_congruenceflip
        have : Cong E F C D := by conclude axiom_5_line
        have : Cong C D E F := by conclude lemma_congruencesymmetric
        close
      · have : Midpoint F M E := by conclude cn_equalitysub
        have : F ≠ B := by forward_using lemma_betweennotequal
        have : F ≠ D := by forward_using lemma_betweennotequal
        have : B ≠ D := by forward_using lemma_betweennotequal
        have : Cong F B E A := by conclude lemma_pointreflectionisometry
        have : Cong B D A R := by conclude lemma_pointreflectionisometry
        have : Cong F D E R := by conclude lemma_pointreflectionisometry
        have : BetS E A R := by conclude lemma_betweennesspreserved
        have : BetS E A C := by conclude axiom_betweennesssymmetry
        have : Cong A C A C := by conclude cn_congruencereflexive
        have : Cong A R B D := by conclude lemma_congruencesymmetric
        have : Cong A R B F := by conclude lemma_congruencetransitive
        have : Cong B F A E := by forward_using lemma_congruenceflip
        have : Cong A R A E := by conclude lemma_congruencetransitive
        have : Cong A E A C := by conclude lemma_congruencesymmetric
        have : Cong A R A C := by conclude lemma_congruencetransitive
        have : R = C := by conclude lemma_extensionunique
        have : Col D B F := by conclude_def Col
        have : B ≠ F := by forward_using lemma_betweennotequal
        have : F ≠ B := by conclude lemma_inequalitysymmetric
        have : Per F B M := by conclude lemma_collinearright
        have : Cong F B B D := by forward_using lemma_congruenceflip
        have : Cong F M D M := by conclude lemma_rightreverse
        have : Cong F M M D := by forward_using lemma_congruenceflip
        have : Cong F M M R := by conclude lemma_congruencetransitive
        have : Cong F M M C := by conclude cn_equalitysub
        have : Cong D M F M := by conclude lemma_congruencesymmetric
        have : Cong F M M E := by conclude cn_equalitysub
        have : Cong D M M E := by conclude lemma_congruencetransitive
        have : Cong M C F M := by conclude lemma_congruencesymmetric
        have : Cong C M F M := by forward_using lemma_congruenceflip
        have : Cong M D M E := by forward_using lemma_congruenceflip
        have : BetS C M D := by conclude cn_equalitysub
        have : BetS F M E := by conclude cn_equalitysub
        have : Cong C D F E := by conclude cn_sumofparts
        have : Cong C D E F := by forward_using lemma_congruenceflip
        close
  close

end GeocoqTranslate.Elements
