/- Transpiled from ../theories/Elements/OriginalProofs/lemma_collinear1.v :: lemma_collinear1
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

set_option maxHeartbeats 800000 in
theorem lemma_collinear1 :
    ∀ (A B C : Point), Col A B C → Col B A C := by
  intro A B C h1
  have : (A = B ∨ A = C ∨ B = C ∨ BetS B A C ∨ BetS A B C ∨ BetS A C B) := by conclude_def Col
  have : Col B A C := by
      rcases (show A = B ∨ A = C ∨ B = C ∨ BetS B A C ∨ BetS A B C ∨ BetS A C B by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
      · have : B = A := by conclude lemma_equalitysymmetric
        have : Col B A C := by conclude_def Col
        close
      · have : Col B A C := by conclude_def Col
        close
      · have : Col B A C := by conclude_def Col
        close
      · have : Col B A C := by conclude_def Col
        close
      · have : Col B A C := by conclude_def Col
        close
      · have : BetS B C A := by conclude axiom_betweennesssymmetry
        have : Col B A C := by conclude_def Col
        close
  close

end GeocoqTranslate.Elements
