/- Transpiled from ../theories/Elements/OriginalProofs/lemma_planeseparation.v :: lemma_planeseparation
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_twolines2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_9_5b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_9_5a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_outerconnectivity
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_planeseparation :
    ∀ (A B C D E : Point), OS C D A B → TS D A B E → TS C A B E := by
  intro A B C D E h1 h2
  obtain ⟨G, H, Q, _, _, _, _, _, _⟩ : ∃ G H Q, (Col A B G ∧ Col A B H ∧ BetS C G Q ∧ BetS D H Q ∧ nCol A B C ∧ nCol A B D) := by conclude_def OS
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  obtain ⟨W, _, _, _⟩ : ∃ W, (BetS D W E ∧ Col A B W ∧ nCol A B D) := by conclude_def TS
  have : C ≠ G := by forward_using lemma_betweennotequal
  have : G ≠ C := by conclude lemma_inequalitysymmetric
  have : G ≠ Q := by forward_using lemma_betweennotequal
  have : TS C A B E := by
      rcases (show Col C Q D ∨ nCol C Q D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
      · have : ¬ ¬ TS C A B E := by
            intro h
            have : Col Q C D := by forward_using lemma_collinearorder
            have : ¬ G ≠ H := by
                intro h
                have : D ≠ Q := by forward_using lemma_betweennotequal
                have : Col C G Q := by conclude_def Col
                have : Col D H Q := by conclude_def Col
                have : Col Q C G := by forward_using lemma_collinearorder
                have : C ≠ Q := by forward_using lemma_betweennotequal
                have : Q ≠ C := by conclude lemma_inequalitysymmetric
                have : Col C G D := by conclude lemma_collinear4
                have : Col D Q H := by forward_using lemma_collinearorder
                have : Col D Q C := by forward_using lemma_collinearorder
                have : Col Q H C := by conclude lemma_collinear4
                have : Col Q C H := by forward_using lemma_collinearorder
                have : ¬ Col C A B := by
                    intro h
                    have : Col A B C := by forward_using lemma_collinearorder
                    contradict
                have : ¬ (Col C A B ∧ Col D A B) := by
                    intro h
                    contradict
                have : Col G A B := by forward_using lemma_collinearorder
                have : Col H A B := by forward_using lemma_collinearorder
                have : Col G C D := by forward_using lemma_collinearorder
                have : Col Q D H := by forward_using lemma_collinearorder
                have : Col Q D C := by forward_using lemma_collinearorder
                have : D ≠ Q := by forward_using lemma_betweennotequal
                have : Q ≠ D := by conclude lemma_inequalitysymmetric
                have : Col D C H := by conclude lemma_collinear4
                have : Col H C D := by forward_using lemma_collinearorder
                have : ¬ C = D := by
                    intro h
                    have : TS C A B E := by conclude cn_equalitysub
                    contradict
                have : G = H := by conclude lemma_twolines2
                contradict
            have : BetS Q G C := by conclude axiom_betweennesssymmetry
            have : BetS Q H D := by conclude axiom_betweennesssymmetry
            have : BetS Q G D := by conclude cn_equalitysub
            have : ¬ nCol E D G := by
                intro h
                have : ¬ nCol E C G := by
                    intro h
                    have : ¬ BetS G C D := by
                        intro h
                        have : TS C A B E := by conclude lemma_9_5b
                        contradict
                    have : ¬ BetS G D C := by
                        intro h
                        have : ¬ Col G C E := by
                            intro h
                            have : Col E C G := by forward_using lemma_collinearorder
                            contradict
                        have : TS C A B E := by conclude lemma_9_5a
                        contradict
                    have : C = D := by conclude lemma_outerconnectivity
                    have : TS C A B E := by conclude cn_equalitysub
                    contradict
                have : Col C G E := by forward_using lemma_collinearorder
                have : Col Q G D := by conclude_def Col
                have : Col Q G C := by conclude_def Col
                have : Q ≠ G := by forward_using lemma_betweennotequal
                have : Col G D C := by conclude lemma_collinear4
                have : Col C G D := by forward_using lemma_collinearorder
                have : Col C G E := by forward_using lemma_collinearorder
                have : G ≠ C := by forward_using lemma_betweennotequal
                have : C ≠ G := by conclude lemma_inequalitysymmetric
                have : Col G D E := by conclude lemma_collinear4
                have : Col E D G := by forward_using lemma_collinearorder
                contradict
            have : Col D G E := by forward_using lemma_collinearorder
            have : Col D H Q := by conclude_def Col
            have : Col D G Q := by conclude cn_equalitysub
            have : G ≠ D := by forward_using lemma_betweennotequal
            have : D ≠ G := by conclude lemma_inequalitysymmetric
            have : Col G E Q := by conclude lemma_collinear4
            have : Col G E D := by forward_using lemma_collinearorder
            have : Col D W E := by conclude_def Col
            have : Col D E W := by forward_using lemma_collinearorder
            have : Col D E G := by forward_using lemma_collinearorder
            have : D ≠ E := by forward_using lemma_betweennotequal
            have : Col E W G := by conclude lemma_collinear4
            have : Col E W D := by forward_using lemma_collinearorder
            have : W ≠ E := by forward_using lemma_betweennotequal
            have : E ≠ W := by conclude lemma_inequalitysymmetric
            have : Col W G D := by conclude lemma_collinear4
            have : Col B W G := by conclude lemma_collinear4
            have : Col W G B := by forward_using lemma_collinearorder
            have : Col B A W := by forward_using lemma_collinearorder
            have : Col B A G := by forward_using lemma_collinearorder
            have : Col A W G := by conclude lemma_collinear4
            have : Col W G A := by forward_using lemma_collinearorder
            have : ¬ W ≠ G := by
                intro h
                have : Col G D B := by conclude lemma_collinear4
                have : Col G B D := by forward_using lemma_collinearorder
                have : Col G B A := by forward_using lemma_collinearorder
                have : ¬ G ≠ B := by
                    intro h
                    have : Col B D A := by conclude lemma_collinear4
                    have : Col A B D := by forward_using lemma_collinearorder
                    contradict
                have : Col G D A := by conclude lemma_collinear4
                have : Col G A D := by forward_using lemma_collinearorder
                have : Col G A B := by forward_using lemma_collinearorder
                have : ¬ G ≠ A := by
                    intro h
                    have : Col A D B := by conclude lemma_collinear4
                    have : Col A B D := by forward_using lemma_collinearorder
                    contradict
                have : A = G := by conclude lemma_equalitysymmetric
                have : B = G := by conclude lemma_equalitysymmetric
                have : A = B := by conclude cn_equalitytransitive
                contradict
            have : BetS D G E := by conclude cn_equalitysub
            have : BetS E G D := by conclude axiom_betweennesssymmetry
            have : ¬ BetS G D C := by
                intro h
                have : BetS E G C := by conclude lemma_3_7b
                have : BetS C G E := by conclude axiom_betweennesssymmetry
                have : TS C A B E := by conclude_def TS
                contradict
            have : ¬ BetS G C D := by
                intro h
                have : BetS E G C := by conclude axiom_innertransitivity
                have : BetS C G E := by conclude axiom_betweennesssymmetry
                have : TS C A B E := by conclude_def TS
                contradict
            have : ¬ BetS C G D := by
                intro h
                have : BetS D G Q := by conclude cn_equalitysub
                have : BetS Q G C := by conclude axiom_betweennesssymmetry
                have : BetS D G C := by conclude axiom_betweennesssymmetry
                have : G ≠ D := by forward_using lemma_betweennotequal
                have : ¬ BetS G D C := by
                    intro h
                    have : BetS C D G := by conclude axiom_betweennesssymmetry
                    have : BetS C G C := by conclude lemma_3_7a
                    have : C ≠ C := by forward_using lemma_betweennotequal
                    have : C = C := by conclude cn_equalityreflexive
                    contradict
                have : ¬ BetS G C D := by
                    intro h
                    have : BetS D G C := by conclude axiom_betweennesssymmetry
                    have : BetS C G C := by conclude axiom_innertransitivity
                    have : C ≠ C := by forward_using lemma_betweennotequal
                    have : C = C := by conclude cn_equalityreflexive
                    contradict
                have : BetS Q G D := by conclude axiom_betweennesssymmetry
                have : BetS Q G C := by conclude axiom_betweennesssymmetry
                have : C = D := by conclude lemma_outerconnectivity
                have : TS C A B E := by conclude cn_equalitysub
                contradict
            have : Col Q C D := by forward_using lemma_collinearorder
            have : Col Q G C := by conclude_def Col
            have : Col Q C G := by forward_using lemma_collinearorder
            have : Q ≠ C := by forward_using lemma_betweennotequal
            have : Col C D G := by conclude lemma_collinear4
            have : Col G C D := by forward_using lemma_collinearorder
            have : (G = C ∨ G = D ∨ C = D ∨ BetS C G D ∨ BetS G C D ∨ BetS G D C) := by conclude_def Col
            have : TS C A B E := by
                rcases (show G = C ∨ G = D ∨ C = D ∨ BetS C G D ∨ BetS G C D ∨ BetS G D C by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
                · have : ¬ ¬ TS C A B E := by
                      intro h
                      have : Col A B C := by conclude cn_equalitysub
                      contradict
                  close
                · have : ¬ ¬ TS C A B E := by
                      intro h
                      have : Col A B D := by conclude cn_equalitysub
                      contradict
                  close
                · have : ¬ ¬ TS C A B E := by
                      intro h
                      have : TS C A B E := by conclude cn_equalitysub
                      contradict
                  close
                · have : ¬ ¬ TS C A B E := by
                      intro h
                      contradict
                  close
                · have : ¬ ¬ TS C A B E := by
                      intro h
                      contradict
                  close
                · have : ¬ ¬ TS C A B E := by
                      intro h
                      contradict
                  close
            contradict
        close
      · have : ¬ ¬ TS C A B E := by
            intro h
            have : ¬ Col Q C D := by
                intro h
                have : Col C Q D := by forward_using lemma_collinearorder
                contradict
            obtain ⟨F, _, _⟩ : ∃ F, (BetS C F H ∧ BetS D F G) := by conclude postulate_Pasch_inner
            have : BetS H F C := by conclude axiom_betweennesssymmetry
            have : BetS G F D := by conclude axiom_betweennesssymmetry
            have : ¬ Col E D G := by
                intro h
                have : ¬ W ≠ G := by
                    intro h
                    have : Col D E G := by forward_using lemma_collinearorder
                    have : Col D W E := by conclude_def Col
                    have : Col B G W := by conclude lemma_collinear4
                    have : Col W B G := by forward_using lemma_collinearorder
                    have : Col W B A := by forward_using lemma_collinearorder
                    have : Col B G A := by
                        rcases (show W = B ∨ W ≠ B by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
                        · have : Col B A G := by forward_using lemma_collinearorder
                          have : Col B A W := by forward_using lemma_collinearorder
                          have : Col A G W := by conclude lemma_collinear4
                          have : Col A G B := by conclude cn_equalitysub
                          have : Col B G A := by forward_using lemma_collinearorder
                          close
                        · have : Col B G A := by conclude lemma_collinear4
                          close
                    have : Col G A B := by forward_using lemma_collinearorder
                    have : Col E D G := by forward_using lemma_collinearorder
                    have : Col E D W := by forward_using lemma_collinearorder
                    have : D ≠ E := by forward_using lemma_betweennotequal
                    have : E ≠ D := by conclude lemma_inequalitysymmetric
                    have : Col D G W := by conclude lemma_collinear4
                    have : Col G W D := by forward_using lemma_collinearorder
                    have : B = B := by conclude cn_equalityreflexive
                    have : Col A B B := by conclude_def Col
                    have : G ≠ W := by conclude lemma_inequalitysymmetric
                    have : Col G W B := by conclude lemma_collinear5
                    have : Col W D B := by conclude lemma_collinear4
                    have : Col W B D := by forward_using lemma_collinearorder
                    have : Col B A W := by forward_using lemma_collinearorder
                    have : Col B A G := by forward_using lemma_collinearorder
                    have : A = A := by conclude cn_equalityreflexive
                    have : Col B A A := by conclude_def Col
                    have : Col G W A := by conclude lemma_collinear5
                    have : Col W D A := by conclude lemma_collinear4
                    have : D ≠ W := by forward_using lemma_betweennotequal
                    have : W ≠ D := by conclude lemma_inequalitysymmetric
                    have : Col D B A := by conclude lemma_collinear4
                    have : Col A B D := by forward_using lemma_collinearorder
                    contradict
                have : BetS D G E := by conclude cn_equalitysub
                have : BetS E G D := by conclude axiom_betweennesssymmetry
                have : BetS G F D := by conclude axiom_betweennesssymmetry
                have : BetS E G F := by conclude axiom_innertransitivity
                have : ¬ Col H C E := by
                    intro h
                    have : Col H E C := by forward_using lemma_collinearorder
                    have : Col E H C := by forward_using lemma_collinearorder
                    have : Col C F H := by conclude_def Col
                    have : Col H C F := by forward_using lemma_collinearorder
                    have : Col H C E := by forward_using lemma_collinearorder
                    have : C ≠ H := by forward_using lemma_betweennotequal
                    have : H ≠ C := by conclude lemma_inequalitysymmetric
                    have : Col C F E := by conclude lemma_collinear4
                    have : Col E F C := by forward_using lemma_collinearorder
                    have : BetS D F E := by conclude lemma_3_6b
                    have : Col D F E := by conclude_def Col
                    have : Col E F D := by forward_using lemma_collinearorder
                    have : F ≠ E := by forward_using lemma_betweennotequal
                    have : E ≠ F := by conclude lemma_inequalitysymmetric
                    have : Col F C D := by conclude lemma_collinear4
                    have : Col F D C := by forward_using lemma_collinearorder
                    have : Col D F G := by conclude_def Col
                    have : Col F D G := by forward_using lemma_collinearorder
                    have : D ≠ F := by forward_using lemma_betweennotequal
                    have : F ≠ D := by conclude lemma_inequalitysymmetric
                    have : Col D C G := by conclude lemma_collinear4
                    have : Col G C D := by forward_using lemma_collinearorder
                    have : Col C G Q := by conclude_def Col
                    have : Col G C Q := by forward_using lemma_collinearorder
                    have : C ≠ G := by forward_using lemma_betweennotequal
                    have : G ≠ C := by conclude lemma_inequalitysymmetric
                    have : Col C D Q := by conclude lemma_collinear4
                    have : Col Q C D := by forward_using lemma_collinearorder
                    contradict
                obtain ⟨M, _, _⟩ : ∃ M, (BetS E M C ∧ BetS H G M) := by conclude postulate_Pasch_outer
                have : Col H G M := by conclude_def Col
                have : Col B H G := by conclude lemma_collinear4
                have : Col H G B := by forward_using lemma_collinearorder
                have : H ≠ G := by forward_using lemma_betweennotequal
                have : Col G M B := by conclude lemma_collinear4
                have : Col G B M := by forward_using lemma_collinearorder
                have : Col G B A := by forward_using lemma_collinearorder
                have : Col A B M := by
                    rcases (show B = G ∨ B ≠ G by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
                    · have : Col B A H := by forward_using lemma_collinearorder
                      have : Col B A G := by forward_using lemma_collinearorder
                      have : Col A H G := by conclude lemma_collinear4
                      have : Col H G A := by forward_using lemma_collinearorder
                      have : Col G A M := by conclude lemma_collinear4
                      have : Col B A M := by conclude cn_equalitysub
                      have : Col A B M := by forward_using lemma_collinearorder
                      close
                    · have : G ≠ B := by conclude lemma_inequalitysymmetric
                      have : Col B M A := by conclude lemma_collinear4
                      have : Col A B M := by forward_using lemma_collinearorder
                      close
                have : BetS C M E := by conclude axiom_betweennesssymmetry
                have : TS C A B E := by conclude_def TS
                contradict
            have : TS F A B E := by conclude lemma_9_5b
            have : ¬ G = H := by
                intro h
                have : Col D H Q := by conclude_def Col
                have : Col C G Q := by conclude_def Col
                have : Col Q H D := by forward_using lemma_collinearorder
                have : Col Q G C := by forward_using lemma_collinearorder
                have : Col Q H C := by conclude cn_equalitysub
                have : H ≠ Q := by forward_using lemma_betweennotequal
                have : Q ≠ H := by conclude lemma_inequalitysymmetric
                have : Col H D C := by conclude lemma_collinear4
                have : Col H D Q := by forward_using lemma_collinearorder
                have : D ≠ H := by forward_using lemma_betweennotequal
                have : H ≠ D := by conclude lemma_inequalitysymmetric
                have : Col D C Q := by conclude lemma_collinear4
                have : Col C Q D := by forward_using lemma_collinearorder
                contradict
            have : ¬ Col H C E := by
                intro h
                obtain ⟨K, _, _⟩ : ∃ K, (BetS G K H ∧ Cong K G K H) := by conclude proposition_10
                have : ¬ Col G D E := by
                    intro h
                    have : Col E D G := by forward_using lemma_collinearorder
                    contradict
                have : BetS E W D := by conclude axiom_betweennesssymmetry
                have : BetS G F D := by conclude axiom_betweennesssymmetry
                obtain ⟨J, _, _⟩ : ∃ J, (BetS E J F ∧ BetS G J W) := by conclude postulate_Pasch_inner
                have : Col G J W := by conclude_def Col
                have : Col E F J := by conclude_def Col
                have : Col E C H := by forward_using lemma_collinearorder
                have : Col F E J := by forward_using lemma_collinearorder
                have : Col C F H := by conclude_def Col
                have : Col C H F := by forward_using lemma_collinearorder
                have : Col C H E := by forward_using lemma_collinearorder
                have : C ≠ H := by forward_using lemma_betweennotequal
                have : Col H F E := by conclude lemma_collinear4
                have : Col F E H := by forward_using lemma_collinearorder
                have : E ≠ F := by forward_using lemma_betweennotequal
                have : F ≠ E := by conclude lemma_inequalitysymmetric
                have : Col E J H := by conclude lemma_collinear4
                have : Col E H J := by forward_using lemma_collinearorder
                have : Col G W J := by forward_using lemma_collinearorder
                have : H = H := by conclude cn_equalityreflexive
                have : Col E H H := by conclude_def Col
                have : Col G H W := by conclude lemma_collinear5
                have : Col G W H := by forward_using lemma_collinearorder
                have : ¬ G = W := by
                    intro h
                    have : Col D W E := by conclude_def Col
                    have : Col D G E := by conclude cn_equalitysub
                    have : Col E D G := by forward_using lemma_collinearorder
                    contradict
                have : Col E J H := by conclude lemma_collinear4
                have : Col W J H := by conclude lemma_collinear4
                have : Col J H E := by forward_using lemma_collinearorder
                have : Col J H W := by forward_using lemma_collinearorder
                have : ¬ H = W := by
                    intro h
                    have : Col D W E := by conclude_def Col
                    have : Col D H E := by conclude cn_equalitysub
                    have : Col D H Q := by conclude_def Col
                    have : D ≠ H := by forward_using lemma_betweennotequal
                    have : Col H E Q := by conclude lemma_collinear4
                    have : Col H E C := by forward_using lemma_collinearorder
                    have : W ≠ E := by forward_using lemma_betweennotequal
                    have : H ≠ E := by conclude cn_equalitysub
                    have : Col E Q C := by conclude lemma_collinear4
                    have : Col E C Q := by forward_using lemma_collinearorder
                    have : Col E C H := by forward_using lemma_collinearorder
                    have : ¬ E ≠ C := by
                        intro h
                        have : Col C Q H := by conclude lemma_collinear4
                        have : Col H Q C := by forward_using lemma_collinearorder
                        have : Col H Q D := by forward_using lemma_collinearorder
                        have : H ≠ Q := by forward_using lemma_betweennotequal
                        have : Col Q C D := by conclude lemma_collinear4
                        contradict
                    have : Col E W D := by forward_using lemma_collinearorder
                    have : Col C W D := by conclude cn_equalitysub
                    have : Col C H D := by conclude cn_equalitysub
                    have : Col D H C := by forward_using lemma_collinearorder
                    have : Col D H Q := by conclude_def Col
                    have : D ≠ H := by forward_using lemma_betweennotequal
                    have : Col H C Q := by conclude lemma_collinear4
                    have : Col H Q C := by forward_using lemma_collinearorder
                    have : Col H Q D := by forward_using lemma_collinearorder
                    have : H ≠ Q := by forward_using lemma_betweennotequal
                    have : Col Q C D := by conclude lemma_collinear4
                    have : Col C Q D := by forward_using lemma_collinearorder
                    contradict
                have : ¬ J ≠ H := by
                    intro h
                    have : Col H E W := by conclude lemma_collinear4
                    have : Col H W E := by forward_using lemma_collinearorder
                    have : Col H W G := by forward_using lemma_collinearorder
                    have : Col W E G := by conclude lemma_collinear4
                    have : Col D W E := by conclude_def Col
                    have : Col W E D := by forward_using lemma_collinearorder
                    have : W ≠ E := by forward_using lemma_betweennotequal
                    have : Col E G D := by conclude lemma_collinear4
                    have : Col E D G := by forward_using lemma_collinearorder
                    contradict
                have : BetS E H F := by conclude cn_equalitysub
                have : BetS F H E := by conclude axiom_betweennesssymmetry
                have : BetS C H E := by conclude lemma_3_7a
                have : TS C A B E := by conclude_def TS
                contradict
            have : TS C A B E := by conclude lemma_9_5a
            contradict
        close
  close

end GeocoqTranslate.Elements
