/- Transpiled from ../theories/Elements/OriginalProofs/lemma_TTflip2.v :: lemma_TTflip2
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthancongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_TTflip2 :
    ∀ (A B C D E F G H : Point), TT A B C D E F G H → TT A B C D H G F E := by
  intro A B C D E F G H h1
  obtain ⟨J, _, _, _⟩ : ∃ J, (BetS E F J ∧ Cong F J G H ∧ TG A B C D E J) := by conclude_def TT
  obtain ⟨K, _, _, _⟩ : ∃ K, (BetS A B K ∧ Cong B K C D ∧ Lt E J A K) := by conclude_def TG
  have : F ≠ J := by forward_using lemma_betweennotequal
  have : G ≠ H := by conclude axiom_nocollapse
  have : H ≠ G := by conclude lemma_inequalitysymmetric
  have : E ≠ F := by forward_using lemma_betweennotequal
  have : F ≠ E := by conclude lemma_inequalitysymmetric
  obtain ⟨L, _, _⟩ : ∃ L, (BetS H G L ∧ Cong G L F E) := by conclude lemma_extension
  have : Cong L G E F := by forward_using lemma_congruenceflip
  have : Cong G H F J := by conclude lemma_congruencesymmetric
  have : BetS L G H := by conclude axiom_betweennesssymmetry
  have : Cong L H E J := by conclude cn_sumofparts
  have : Cong H L L H := by conclude cn_equalityreverse
  have : Cong H L E J := by conclude lemma_congruencetransitive
  have : Cong E J H L := by conclude lemma_congruencesymmetric
  have : Lt H L A K := by conclude lemma_lessthancongruence2
  have : TG A B C D H L := by conclude_def TG
  have : TT A B C D H G F E := by conclude_def TT
  close

end GeocoqTranslate.Elements
