/- Transpiled from ../theories/Elements/OriginalProofs/lemma_samesidecollinear.v :: lemma_samesidecollinear
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_samesidecollinear :
    ∀ (A B C P Q : Point), OS P Q A B → Col A B C → A ≠ C → OS P Q A C := by
  intro A B C P Q h1 h2 h3
  obtain ⟨p, q, r, _, _, _, _, _, _⟩ : ∃ p q r, (Col A B p ∧ Col A B q ∧ BetS P p r ∧ BetS Q q r ∧ nCol A B P ∧ nCol A B Q) := by conclude_def OS
  have : A ≠ B := by forward_using lemma_NCdistinct
  have : A = A := by conclude cn_equalityreflexive
  have : Col A B A := by conclude_def Col
  have : nCol A C P := by conclude lemma_NChelper
  have : nCol A C Q := by conclude lemma_NChelper
  have : Col B A p := by forward_using lemma_collinearorder
  have : Col B A C := by forward_using lemma_collinearorder
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : Col A C p := by conclude lemma_collinear4
  have : Col B A q := by forward_using lemma_collinearorder
  have : Col A C q := by conclude lemma_collinear4
  have : OS P Q A C := by conclude_def OS
  close

end GeocoqTranslate.Elements
