/- Transpiled from ../theories/Elements/OriginalProofs/lemma_Playfair.v :: lemma_Playfair
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_crisscross
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_Playfairhelper2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

theorem lemma_Playfair :
    ∀ (A B C D E : Point), Par A B C D → Par A B C E → Col C D E := by
  intro A B C D E h1 h2
  have : A ≠ B := by conclude_def Par
  have : C ≠ D := by conclude_def Par
  have : ¬ ¬ (CR A D B C ∨ CR A C B D) := by
      intro h
      have : Par A B D C := by forward_using lemma_parallelflip
      have : CR A C D B := by conclude lemma_crisscross
      obtain ⟨p, _, _⟩ : ∃ p, (BetS A p C ∧ BetS D p B) := by conclude_def CR
      have : D ≠ B := by forward_using lemma_betweennotequal
      have : B ≠ D := by conclude lemma_inequalitysymmetric
      have : BetS B p D := by conclude axiom_betweennesssymmetry
      have : CR A C B D := by conclude_def CR
      contradict
  sorry -- TODO: assert (Col C D E).
  rcases (show CR A D B C ∨ CR A C B D by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2
  · have : Col C D E := by conclude lemma_Playfairhelper2
    close
  · obtain ⟨p, _, _⟩ : ∃ p, (BetS A p C ∧ BetS B p D) := by conclude_def CR
    have : CR B D A C := by conclude_def CR
    have : Par B A C D := by forward_using lemma_parallelflip
    have : Par B A C E := by forward_using lemma_parallelflip
    have : Col C D E := by conclude lemma_Playfairhelper2
    close
  close

end GeocoqTranslate.Elements
