/- Transpiled from ../theories/Elements/OriginalProofs/lemma_ray4.v :: lemma_ray4
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7b

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_ray4 :
    ∀ (A B E : Point), (BetS A E B ∨ E = B ∨ BetS A B E) → A ≠ B → Out A B E := by
  intro A B E h1 h2
  have : ¬ B = A := by
      intro h
      have : A = B := by conclude lemma_equalitysymmetric
      contradict
  obtain ⟨J, _, _⟩ : ∃ J, (BetS B A J ∧ Cong A J A B) := by conclude lemma_extension
  have : BetS J A B := by conclude axiom_betweennesssymmetry
  sorry -- TODO: assert (Out A B E).
  rcases (show BetS A E B ∨ E = B ∨ BetS A B E by first | assumption | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
  · have : BetS J A E := by conclude axiom_innertransitivity
    have : Out A B E := by conclude_def Out
    close
  · have : BetS J A E := by conclude cn_equalitysub
    have : Out A B E := by conclude_def Out
    close
  · have : BetS J A E := by conclude lemma_3_7b
    have : Out A B E := by conclude_def Out
    close
  close

end GeocoqTranslate.Elements
