/- Transpiled from ../theories/Elements/OriginalProofs/lemma_altitudebisectsbase.v :: lemma_altitudebisectsbase
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_3
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extensionunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rightangleNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_altitudebisectsbase :
    ∀ (A B M P : Point), BetS A M B → Cong A P B P → Per A M P → Midpoint A M B := by
  intro A B M P h1 h2 h3
  obtain ⟨C, _, _, _, _⟩ : ∃ C, (BetS A M C ∧ Cong A M C M ∧ Cong A P C P ∧ M ≠ P) := by conclude_def Per
  have : BetS C M A := by conclude axiom_betweennesssymmetry
  have : Cong C M A M := by conclude lemma_congruencesymmetric
  have : Cong C P A P := by conclude lemma_congruencesymmetric
  have : Per C M P := by conclude_def Per
  have : Per P M A := by conclude lemma_8_2
  obtain ⟨Q, _, _, _, _⟩ : ∃ Q, (BetS P M Q ∧ Cong P M Q M ∧ Cong P A Q A ∧ M ≠ A) := by conclude_def Per
  have : Cong Q M P M := by conclude lemma_congruencesymmetric
  have : Per P M C := by conclude lemma_8_2
  have : Out M C B := by conclude_def Out
  have : Per P M B := by conclude lemma_8_3
  obtain ⟨E, _, _, _, _⟩ : ∃ E, (BetS P M E ∧ Cong P M E M ∧ Cong P B E B ∧ M ≠ B) := by conclude_def Per
  have : Cong P A P B := by forward_using lemma_congruenceflip
  have : Cong M Q P M := by forward_using lemma_congruenceflip
  have : Cong P M M Q := by conclude lemma_congruencesymmetric
  have : Cong E M P M := by conclude lemma_congruencesymmetric
  have : Cong E M M Q := by conclude lemma_congruencetransitive
  have : Cong M E M Q := by forward_using lemma_congruenceflip
  have : Cong M Q M E := by conclude lemma_congruencesymmetric
  have : P ≠ M := by forward_using lemma_betweennotequal
  have : Q = E := by conclude lemma_extensionunique
  have : Cong P B Q B := by conclude cn_equalitysub
  have : Cong A P P B := by forward_using lemma_congruenceflip
  have : Cong A P Q B := by conclude lemma_congruencetransitive
  have : Cong A Q A P := by forward_using lemma_doublereverse
  have : Cong A Q Q B := by conclude lemma_congruencetransitive
  have : Cong A Q B Q := by forward_using lemma_congruenceflip
  have : Cong P Q P Q := by conclude cn_congruencereflexive
  have : A = A := by conclude cn_equalityreflexive
  have : B = B := by conclude cn_equalityreflexive
  have : nCol A M P := by conclude lemma_rightangleNC
  have : ¬ Col A P M := by
      intro h
      have : Col A M P := by forward_using lemma_collinearorder
      contradict
  have : ¬ A = P := by
      intro h
      have : Col A P M := by conclude_def Col
      contradict
  have : P ≠ A := by conclude lemma_inequalitysymmetric
  have : Out P A A := by conclude lemma_ray4
  have : ¬ P = B := by
      intro h
      have : Cong A P B B := by conclude cn_equalitysub
      have : ¬ A ≠ P := by
          intro h
          have : B ≠ B := by conclude axiom_nocollapse
          have : B = B := by conclude cn_equalityreflexive
          contradict
      contradict
  have : Out P B B := by conclude lemma_ray4
  have : Out P M Q := by conclude lemma_ray4
  have : CongA A P M B P M := by conclude_def CongA
  have : Cong P M P M := by conclude cn_congruencereflexive
  have : (Cong A M B M ∧ CongA P A M P B M ∧ CongA P M A P M B) := by conclude proposition_04
  have : Cong A M M B := by forward_using lemma_congruenceflip
  have : Midpoint A M B := by conclude_def Midpoint
  close

end GeocoqTranslate.Elements
