/- Transpiled from ../theories/Elements/OriginalProofs/lemma_TTtransitive.v :: lemma_TTtransitive
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoffunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_lessthantransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_TTtransitive :
    ∀ (A B C D E F G H P Q R S : Point), TT A B C D E F G H → TT E F G H P Q R S → TT A B C D P Q R S := by
  intro A B C D E F G H P Q R S h1 h2
  obtain ⟨K, _, _, _⟩ : ∃ K, (BetS E F K ∧ Cong F K G H ∧ TG A B C D E K) := by conclude_def TT
  obtain ⟨J, _, _, _⟩ : ∃ J, (BetS A B J ∧ Cong B J C D ∧ Lt E K A J) := by conclude_def TG
  obtain ⟨L, _, _, _⟩ : ∃ L, (BetS P Q L ∧ Cong Q L R S ∧ TG E F G H P L) := by conclude_def TT
  obtain ⟨M, _, _, _⟩ : ∃ M, (BetS E F M ∧ Cong F M G H ∧ Lt P L E M) := by conclude_def TG
  have : K = K := by conclude cn_equalityreflexive
  have : F ≠ K := by forward_using lemma_betweennotequal
  have : F ≠ M := by forward_using lemma_betweennotequal
  have : Out F K M := by conclude_def Out
  have : Out F K K := by conclude lemma_ray4
  have : Cong G H F M := by conclude lemma_congruencesymmetric
  have : Cong F K F M := by conclude lemma_congruencetransitive
  have : K = M := by conclude lemma_layoffunique
  have : Lt P L E K := by conclude cn_equalitysub
  have : Lt P L A J := by conclude lemma_lessthantransitive
  have : TG A B C D P L := by conclude_def TG
  have : TT A B C D P Q R S := by conclude_def TT
  close

end GeocoqTranslate.Elements
