/- Transpiled from ../theories/Elements/OriginalProofs/lemma_crisscross.v :: lemma_crisscross
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_planeseparation
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearbetween
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_5b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_crisscross :
    ∀ (A B C D : Point), Par A C B D → ¬ CR A B C D → CR A D B C := by
  intro A B C D h1 h2
  have : Par B D A C := by conclude lemma_parallelsymmetric
  have : TP B D A C := by conclude lemma_paralleldef2B
  have : OS A C B D := by conclude_def TP
  have : nCol A C B := by forward_using lemma_parallelNC
  have : A ≠ B := by forward_using lemma_NCdistinct
  obtain ⟨E, _, _⟩ : ∃ E, (BetS A B E ∧ Cong B E A B) := by conclude lemma_extension
  have : B = B := by conclude cn_equalityreflexive
  have : Col B D B := by conclude_def Col
  have : nCol A B D := by forward_using lemma_parallelNC
  have : nCol B D A := by perm_close
  have : OS C A B D := by forward_using lemma_samesidesymmetric
  have : TS A B D E := by (try (have : nCol B D A := nCol_notCol _ _ _ (by assumption))); conclude_def TS
  have : TS C B D E := by conclude lemma_planeseparation
  obtain ⟨F, _, _, _⟩ : ∃ F, (BetS C F E ∧ Col B D F ∧ nCol B D C) := by conclude_def TS
  have : B ≠ D := by forward_using lemma_NCdistinct
  have : nCol A B D := by forward_using lemma_parallelNC
  have : A ≠ D := by forward_using lemma_NCdistinct
  have : nCol A C D := by forward_using lemma_parallelNC
  have : A ≠ C := by forward_using lemma_NCdistinct
  have : C ≠ D := by forward_using lemma_NCdistinct
  have : C ≠ A := by conclude lemma_inequalitysymmetric
  have : nCol A C B := by forward_using lemma_parallelNC
  have : C ≠ B := by forward_using lemma_NCdistinct
  have : B ≠ C := by conclude lemma_inequalitysymmetric
  have : (B = D ∨ B = F ∨ D = F ∨ BetS D B F ∨ BetS B D F ∨ BetS B F D) := by conclude_def Col
  have : CR A D B C := by
      rcases (show B = D ∨ B = F ∨ D = F ∨ BetS D B F ∨ BetS B D F ∨ BetS B F D by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
      · have : ¬ ¬ CR A D B C := by
            intro h
            contradict
        close
      · have : ¬ ¬ CR A D B C := by
            intro h
            have : Col C F E := by conclude_def Col
            have : Col E F C := by perm_close
            have : B ≠ E := by forward_using lemma_betweennotequal
            have : Col A B E := by conclude_def Col
            have : Col E B A := by perm_close
            have : Col E F C := by perm_close
            have : Col E B C := by conclude cn_equalitysub
            have : E ≠ B := by conclude lemma_inequalitysymmetric
            have : Col B A C := by conclude lemma_collinear4
            have : Col A C B := by perm_close
            have : nCol A C B := by forward_using lemma_parallelNC
            contradict
        close
      · have : nCol A C B := by forward_using lemma_parallelNC
        have : nCol A C F := by conclude cn_equalitysub
        have : nCol C F A := by perm_close
        have : Col C F E := by conclude_def Col
        have : C = C := by conclude cn_equalityreflexive
        have : Col C F C := by conclude_def Col
        have : C ≠ E := by forward_using lemma_betweennotequal
        have : nCol C E A := by conclude lemma_NChelper
        have : nCol A E C := by perm_close
        obtain ⟨M, _, _⟩ : ∃ M, (BetS A M F ∧ BetS C M B) := by conclude postulate_Pasch_inner
        have : BetS A M D := by conclude cn_equalitysub
        have : BetS B M C := by conclude axiom_betweennesssymmetry
        have : CR A D B C := by conclude_def CR
        close
      · have : ¬ ¬ CR A D B C := by
            intro h
            have : nCol D B C := by perm_close
            have : D = D := by conclude cn_equalityreflexive
            have : Col D B D := by conclude_def Col
            have : Col D B F := by perm_close
            have : D ≠ F := by forward_using lemma_betweennotequal
            have : nCol D F C := by conclude lemma_NChelper
            have : nCol C F D := by perm_close
            have : Col C F E := by conclude_def Col
            have : C = C := by conclude cn_equalityreflexive
            have : Col C F C := by conclude_def Col
            have : C ≠ E := by forward_using lemma_betweennotequal
            have : nCol C E D := by conclude lemma_NChelper
            have : nCol E C D := by perm_close
            have : BetS E F C := by conclude axiom_betweennesssymmetry
            obtain ⟨M, _, _⟩ : ∃ M, (BetS D M C ∧ BetS E B M) := by conclude postulate_Pasch_outer
            have : BetS C M D := by conclude axiom_betweennesssymmetry
            have : BetS M B E := by conclude axiom_betweennesssymmetry
            have : Col A B E := by conclude_def Col
            have : Col E B M := by conclude_def Col
            have : Col E B A := by perm_close
            have : B ≠ E := by forward_using lemma_betweennotequal
            have : E ≠ B := by conclude lemma_inequalitysymmetric
            have : Col B M A := by conclude lemma_collinear4
            have : Col A B M := by perm_close
            have : Par C A B D := by forward_using lemma_parallelflip
            have : ¬ Meet C A B D := by conclude_def Par
            have : A = A := by conclude cn_equalityreflexive
            have : Col C A A := by conclude_def Col
            have : B = B := by conclude cn_equalityreflexive
            have : Col B B D := by conclude_def Col
            have : BetS A M B := by conclude lemma_collinearbetween
            have : CR A B C D := by conclude_def CR
            contradict
        close
      · have : nCol A C B := by forward_using lemma_parallelNC
        have : A = A := by conclude cn_equalityreflexive
        have : Col A B A := by conclude_def Col
        have : Col A B E := by conclude_def Col
        have : A ≠ E := by forward_using lemma_betweennotequal
        have : nCol A B C := by perm_close
        have : nCol A E C := by conclude lemma_NChelper
        have : Col A E B := by perm_close
        have : E = E := by conclude cn_equalityreflexive
        have : Col A E E := by conclude_def Col
        have : B ≠ E := by forward_using lemma_betweennotequal
        have : nCol B E C := by conclude lemma_NChelper
        have : nCol C E B := by perm_close
        obtain ⟨J, _, _⟩ : ∃ J, (BetS B J E ∧ BetS C D J) := by conclude postulate_Pasch_outer
        have : BetS A J E := by conclude lemma_3_5b
        have : nCol A C B := by forward_using lemma_parallelNC
        have : nCol A B C := by perm_close
        have : Col A J E := by conclude_def Col
        have : Col E A B := by perm_close
        have : Col E A J := by perm_close
        have : A ≠ E := by forward_using lemma_betweennotequal
        have : E ≠ A := by conclude lemma_inequalitysymmetric
        have : Col A B J := by conclude lemma_collinear4
        have : A ≠ J := by forward_using lemma_betweennotequal
        have : nCol A J C := by conclude lemma_NChelper
        have : BetS A B J := by conclude axiom_innertransitivity
        obtain ⟨M, _, _⟩ : ∃ M, (BetS A M D ∧ BetS C M B) := by conclude postulate_Pasch_inner
        have : BetS B M C := by conclude axiom_betweennesssymmetry
        have : CR A D B C := by conclude_def CR
        close
      · have : BetS D F B := by conclude axiom_betweennesssymmetry
        have : BetS E B A := by conclude axiom_betweennesssymmetry
        have : nCol A B D := by forward_using lemma_parallelNC
        have : Col A B E := by conclude_def Col
        have : A = A := by conclude cn_equalityreflexive
        have : Col A B A := by conclude_def Col
        have : A ≠ E := by forward_using lemma_betweennotequal
        have : nCol A E D := by conclude lemma_NChelper
        have : nCol E A D := by perm_close
        obtain ⟨Q, _, _⟩ : ∃ Q, (BetS D Q A ∧ BetS E F Q) := by conclude postulate_Pasch_outer
        have : BetS E F C := by conclude axiom_betweennesssymmetry
        have : Col E F Q := by conclude_def Col
        have : Col E F C := by conclude_def Col
        have : F ≠ E := by forward_using lemma_betweennotequal
        have : E ≠ F := by conclude lemma_inequalitysymmetric
        have : Col F Q C := by conclude lemma_collinear4
        have : Col F C Q := by perm_close
        have : BetS A Q D := by conclude axiom_betweennesssymmetry
        have : Col B F D := by conclude_def Col
        have : Col B D F := by perm_close
        have : F ≠ D := by forward_using lemma_betweennotequal
        have : Par A C F D := by conclude lemma_collinearparallel
        have : ¬ Meet A C F D := by conclude_def Par
        have : C = C := by conclude cn_equalityreflexive
        have : F = F := by conclude cn_equalityreflexive
        have : Col A C C := by conclude_def Col
        have : Col F F D := by conclude_def Col
        have : Col C F Q := by perm_close
        have : BetS C Q F := by conclude lemma_collinearbetween
        have : nCol A C B := by forward_using lemma_parallelNC
        have : nCol A B C := by perm_close
        have : Col A B A := by conclude_def Col
        have : Col A B E := by conclude_def Col
        have : A ≠ E := by forward_using lemma_betweennotequal
        have : nCol A E C := by conclude lemma_NChelper
        have : BetS C Q E := by conclude lemma_3_6b
        obtain ⟨M, _, _⟩ : ∃ M, (BetS A M Q ∧ BetS C M B) := by conclude postulate_Pasch_inner
        have : BetS A M D := by conclude lemma_3_6b
        have : BetS B M C := by conclude axiom_betweennesssymmetry
        have : CR A D B C := by conclude_def CR
        close
  close

end GeocoqTranslate.Elements
