/- Transpiled from ../theories/Elements/OriginalProofs/lemma_squareflip.v :: lemma_squareflip
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_squareflip :
    ∀ (A B C D : Point), SQ A B C D → SQ B A D C := by
  intro A B C D h1
  have : (Cong A B C D ∧ Cong A B B C ∧ Cong A B D A ∧ Per D A B ∧ Per A B C ∧ Per B C D ∧ Per C D A) := by conclude_def SQ
  have : Cong B A D C := by forward_using lemma_congruenceflip
  have : Cong B A A D := by forward_using lemma_congruenceflip
  have : Cong B A C B := by forward_using lemma_congruenceflip
  have : Per C B A := by conclude lemma_8_2
  have : Per B A D := by conclude lemma_8_2
  have : Per A D C := by conclude lemma_8_2
  have : Per D C B := by conclude lemma_8_2
  have : SQ B A D C := by conclude_def SQ
  close

end GeocoqTranslate.Elements
