/- Transpiled from ../theories/Elements/OriginalProofs/lemma_crossimpliesopposite.v :: lemma_crossimpliesopposite
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_crossimpliesopposite :
    ∀ (A B C D : Point), CR A B C D → nCol A C D → TS A C D B ∧ TS A D C B ∧ TS B C D A ∧ TS B D C A := by
  intro A B C D h1 h2
  obtain ⟨M, _, _⟩ : ∃ M, (BetS A M B ∧ BetS C M D) := by conclude_def CR
  have : Col C M D := by conclude_def Col
  have : Col C D M := by forward_using lemma_collinearorder
  have : nCol C D A := by forward_using lemma_NCorder
  have : nCol D C A := by forward_using lemma_NCorder
  have : TS A C D B := by conclude_def TS
  have : Col D C M := by forward_using lemma_collinearorder
  have : TS A D C B := by conclude_def TS
  have : TS B C D A := by conclude lemma_oppositesidesymmetric
  have : TS B D C A := by conclude lemma_oppositesidesymmetric
  close

end GeocoqTranslate.Elements
