/- Transpiled from ../theories/Elements/OriginalProofs/lemma_extensionunique.v :: lemma_extensionunique
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

theorem lemma_extensionunique :
    ∀ (A B E F : Point), BetS A B E → BetS A B F → Cong B E B F → E = F := by
  intro A B E F h1 h2 h3
  have : Cong B E B E := by conclude cn_congruencereflexive
  have : Cong B F B E := by conclude lemma_congruencesymmetric
  have : Cong A E A E := by conclude cn_congruencereflexive
  have : Cong A B A B := by conclude cn_congruencereflexive
  have : Cong B E B F := by conclude lemma_congruencesymmetric
  have : Cong E E E F := by conclude axiom_5_line
  have : Cong E F E E := by conclude lemma_congruencesymmetric
  have : ¬ E ≠ F := by
      intro h
      have : E ≠ E := by conclude axiom_nocollapse
      have : E = E := by conclude cn_equalityreflexive
      contradict
  close

end GeocoqTranslate.Elements
