/- Transpiled from ../theories/Elements/OriginalProofs/lemma_parallelPasch.v :: lemma_parallelPasch
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelsymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_paralleldef2B
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_planeseparation
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearbetween
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_samesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_parallelNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_parallelPasch :
    ∀ (A B C D E : Point), PG A B C D → BetS A D E → ∃ X, BetS B X E ∧ BetS C X D := by
  intro A B C D E h1 h2
  have : Par A B C D := by conclude_def PG
  have : Par A D B C := by conclude_def PG
  have : Par C D A B := by conclude lemma_parallelsymmetric
  have : TP C D A B := by conclude lemma_paralleldef2B
  have : OS A B C D := by conclude_def TP
  have : OS B A C D := by forward_using lemma_samesidesymmetric
  have : D = D := by conclude cn_equalityreflexive
  have : A ≠ D := by forward_using lemma_betweennotequal
  have : Col A D D := by conclude_def Col
  have : Col A D E := by conclude_def Col
  have : Col D D E := by conclude lemma_collinear4
  have : Col E D D := by forward_using lemma_collinearorder
  have : Col C D D := by conclude_def Col
  have : nCol A C D := by forward_using lemma_parallelNC
  have : nCol C D A := by forward_using lemma_NCorder
  have : TS A C D E := by conclude_def TS
  have : TS B C D E := by conclude lemma_planeseparation
  obtain ⟨H, _, _, _⟩ : ∃ H, (BetS B H E ∧ Col C D H ∧ nCol C D B) := by conclude_def TS
  have : BetS E H B := by conclude axiom_betweennesssymmetry
  have : Col D C H := by forward_using lemma_collinearorder
  have : A ≠ D := by conclude_def Par
  have : ¬ Meet A D B C := by conclude_def Par
  have : ¬ Meet E D C B := by
      intro h
      obtain ⟨p, _, _, _, _⟩ : ∃ p, (E ≠ D ∧ C ≠ B ∧ Col E D p ∧ Col C B p) := by conclude_def Meet
      have : B ≠ C := by conclude lemma_inequalitysymmetric
      have : Col B C p := by forward_using lemma_collinearorder
      have : Col E D A := by forward_using lemma_collinearorder
      have : Col D A p := by conclude lemma_collinear4
      have : Col A D p := by forward_using lemma_collinearorder
      have : Meet A D B C := by conclude_def Meet
      contradict
  have : C = C := by conclude cn_equalityreflexive
  have : D ≠ E := by forward_using lemma_betweennotequal
  have : E ≠ D := by conclude lemma_inequalitysymmetric
  have : B ≠ C := by conclude_def Par
  have : C ≠ B := by conclude lemma_inequalitysymmetric
  have : Col C C B := by conclude_def Col
  have : BetS D H C := by conclude lemma_collinearbetween
  have : BetS C H D := by conclude axiom_betweennesssymmetry
  close

end GeocoqTranslate.Elements
