/- Transpiled from ../theories/Elements/OriginalProofs/lemma_squareparallelogram.v :: lemma_squareparallelogram
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rightangleNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NChelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesideflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_righttogether
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoffunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_Euclid4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsbisect
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennesspreserved
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

theorem lemma_squareparallelogram :
    ∀ (A B C D : Point), SQ A B C D → PG A B C D := by
  intro A B C D h1
  have : (Cong A B C D ∧ Cong A B B C ∧ Cong A B D A ∧ Per D A B ∧ Per A B C ∧ Per B C D ∧ Per C D A) := by conclude_def SQ
  have : nCol D A B := by conclude lemma_rightangleNC
  have : D ≠ A := by forward_using lemma_NCdistinct
  obtain ⟨R, _, _⟩ : ∃ R, (BetS D A R ∧ Cong A R D A) := by conclude lemma_extension
  have : BetS R A D := by conclude axiom_betweennesssymmetry
  have : A ≠ B := by forward_using lemma_NCdistinct
  have : Col D A R := by conclude_def Col
  have : A = A := by conclude cn_equalityreflexive
  have : Col D A A := by conclude_def Col
  have : R ≠ A := by forward_using lemma_betweennotequal
  have : nCol R A B := by conclude lemma_NChelper
  have : nCol A B R := by forward_using lemma_NCorder
  obtain ⟨c, E, _, _, _⟩ : ∃ c E, (SQ A B c E ∧ TS E A B R ∧ PG A B c E) := by conclude proposition_46
  have : (Cong A B c E ∧ Cong A B B c ∧ Cong A B E A ∧ Per E A B ∧ Per A B c ∧ Per B c E ∧ Per c E A) := by conclude_def SQ
  have : Col R A D := by conclude_def Col
  have : Col D A R := by forward_using lemma_collinearorder
  have : Per R A B := by conclude lemma_collinearright
  have : Per B A R := by conclude lemma_8_2
  have : TS E B A R := by conclude lemma_oppositesideflip
  have : BetS E A R := by conclude lemma_righttogether
  have : BetS R A E := by conclude axiom_betweennesssymmetry
  have : Out A D E := by conclude_def Out
  have : Cong A B E A := by conclude_def SQ
  have : Cong E A A B := by conclude lemma_congruencesymmetric
  have : Cong E A D A := by conclude lemma_congruencetransitive
  have : Cong A E A D := by forward_using lemma_congruenceflip
  have : A ≠ D := by forward_using lemma_betweennotequal
  have : D = D := by conclude cn_equalityreflexive
  have : Out A D D := by conclude lemma_ray4
  have : E = D := by conclude lemma_layoffunique
  have : PG A B c D := by conclude cn_equalitysub
  have : Cong A B C D := by conclude_def SQ
  have : SQ A B c D := by conclude cn_equalitysub
  have : Cong A B c D := by conclude_def SQ
  have : Cong c D A B := by conclude lemma_congruencesymmetric
  have : Cong c D C D := by conclude lemma_congruencetransitive
  have : Cong A B B C := by conclude_def SQ
  have : Cong A B B c := by conclude_def SQ
  have : Cong B c A B := by conclude lemma_congruencesymmetric
  have : Cong B c B C := by conclude lemma_congruencetransitive
  have : Cong c B C B := by forward_using lemma_congruenceflip
  have : Per B C D := by conclude_def SQ
  have : Per B c D := by conclude_def SQ
  have : CongA B c D B C D := by conclude lemma_Euclid4
  have : (Cong B D B D ∧ CongA c B D C B D ∧ CongA c D B C D B) := by conclude proposition_04
  obtain ⟨m, _, _⟩ : ∃ m, (Midpoint A m c ∧ Midpoint B m D) := by conclude lemma_diagonalsbisect
  have : (BetS A m c ∧ Cong A m m c) := by conclude_def Midpoint
  have : (BetS B m D ∧ Cong B m m D) := by conclude_def Midpoint
  have : CongA C D B c D B := by conclude lemma_equalanglessymmetric
  have : Cong D m D m := by conclude cn_congruencereflexive
  have : Cong D c D C := by forward_using lemma_congruenceflip
  have : nCol C D A := by conclude lemma_rightangleNC
  have : Per c D A := by conclude cn_equalitysub
  have : nCol c D A := by conclude lemma_rightangleNC
  have : nCol A c D := by forward_using lemma_NCorder
  have : c = c := by conclude cn_equalityreflexive
  have : Col A c c := by conclude_def Col
  have : Col A m c := by conclude_def Col
  have : Col A c m := by forward_using lemma_collinearorder
  have : m ≠ c := by forward_using lemma_betweennotequal
  have : nCol m c D := by conclude lemma_NChelper
  have : nCol c D m := by forward_using lemma_NCorder
  have : ¬ Col C D m := by
      intro h
      have : Col B m D := by conclude_def Col
      have : Col m D B := by forward_using lemma_collinearorder
      have : Col m D C := by forward_using lemma_collinearorder
      have : m ≠ D := by forward_using lemma_betweennotequal
      have : Col D B C := by conclude lemma_collinear4
      have : Col B C D := by forward_using lemma_collinearorder
      have : nCol B C D := by conclude lemma_rightangleNC
      contradict
  have : CongA c D B C D B := by conclude lemma_equalanglessymmetric
  have : BetS D m B := by conclude axiom_betweennesssymmetry
  have : D ≠ B := by forward_using lemma_betweennotequal
  have : Out D B m := by conclude lemma_ray4
  have : C = C := by conclude cn_equalityreflexive
  have : D ≠ C := by forward_using lemma_NCdistinct
  have : Out D C C := by conclude lemma_ray4
  have : CongA c D B C D m := by conclude lemma_equalangleshelper
  have : CongA C D m c D B := by conclude lemma_equalanglessymmetric
  have : c = c := by conclude cn_equalityreflexive
  have : D ≠ c := by forward_using lemma_NCdistinct
  have : Out D c c := by conclude lemma_ray4
  have : CongA C D m c D m := by conclude lemma_equalangleshelper
  have : CongA c D m C D m := by conclude lemma_equalanglessymmetric
  have : Cong c m C m := by conclude proposition_04
  have : Cong m c m C := by forward_using lemma_congruenceflip
  have : Cong A m A m := by conclude cn_congruencereflexive
  have : Cong D A D A := by conclude cn_congruencereflexive
  have : Per c D A := by conclude cn_equalitysub
  have : Per A D c := by conclude lemma_8_2
  have : Per A D C := by conclude lemma_8_2
  have : CongA A D C A D c := by conclude lemma_Euclid4
  have : Cong D C D c := by conclude lemma_congruencesymmetric
  have : Cong A C A c := by conclude proposition_04
  have : Cong A c A C := by conclude lemma_congruencesymmetric
  have : BetS A m C := by conclude lemma_betweennesspreserved
  have : A ≠ m := by forward_using lemma_betweennotequal
  have : Out A m c := by conclude lemma_ray4
  have : Out A m C := by conclude lemma_ray4
  have : c = C := by conclude lemma_layoffunique
  have : PG A B C D := by conclude cn_equalitysub
  close

end GeocoqTranslate.Elements
