/- Transpiled from ../theories/Elements/OriginalProofs/lemma_righttogether.v :: lemma_righttogether
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_8_2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearright
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_Euclid4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_oppositesidesymmetric
import GeocoqTranslate.Elements.OriginalProofs.proposition_14
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_righttogether :
    ∀ (A B C G : Point), Per G A B → Per B A C → TS G B A C → RT G A B B A C ∧ BetS G A C := by
  intro A B C G h1 h2 h3
  have : Per B A G := by conclude lemma_8_2
  have : A ≠ G := by conclude_def Per
  have : G ≠ A := by conclude lemma_inequalitysymmetric
  obtain ⟨D, _, _⟩ : ∃ D, (BetS G A D ∧ Cong A D G A) := by conclude lemma_extension
  have : B = B := by conclude cn_equalityreflexive
  have : A ≠ B := by conclude_def Per
  have : Out A B B := by conclude lemma_ray4
  have : Supp G A B B D := by conclude_def Supp
  have : nCol B A G := by conclude_def TS
  have : nCol G A B := by forward_using lemma_NCorder
  have : CongA G A B G A B := by conclude lemma_equalanglesreflexive
  have : Col G A D := by conclude_def Col
  have : A ≠ D := by forward_using lemma_betweennotequal
  have : D ≠ A := by conclude lemma_inequalitysymmetric
  have : Per D A B := by conclude lemma_collinearright
  have : Per B A D := by conclude lemma_8_2
  have : CongA B A C B A D := by conclude lemma_Euclid4
  have : RT G A B B A C := by conclude_def RT
  have : TS C B A G := by conclude lemma_oppositesidesymmetric
  have : BetS G A C := by conclude proposition_14
  close

end GeocoqTranslate.Elements
