/- Transpiled from ../theories/Elements/OriginalProofs/lemma_twolines.v :: lemma_twolines
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_twolines :
    ∀ (A B C D E F : Point), Cut A B C D E → Cut A B C D F → nCol B C D → E = F := by
  intro A B C D E F h1 h2 h3
  have : (BetS A E B ∧ BetS C E D ∧ nCol A B C ∧ nCol A B D) := by conclude_def Cut
  have : (BetS A F B ∧ BetS C F D ∧ nCol A B C ∧ nCol A B D) := by conclude_def Cut
  have : Col A E B := by conclude_def Col
  have : Col A B E := by forward_using lemma_collinearorder
  have : Col A F B := by conclude_def Col
  have : Col A B F := by forward_using lemma_collinearorder
  have : A ≠ B := by forward_using lemma_betweennotequal
  have : Col B E F := by conclude lemma_collinear4
  have : Col E F B := by forward_using lemma_collinearorder
  have : Col C E D := by conclude_def Col
  have : Col C F D := by conclude_def Col
  have : Col C D F := by forward_using lemma_collinearorder
  have : Col C D E := by forward_using lemma_collinearorder
  have : C ≠ D := by forward_using lemma_betweennotequal
  have : Col D E F := by conclude lemma_collinear4
  have : Col E F D := by forward_using lemma_collinearorder
  have : Col D C E := by conclude lemma_collinear1
  have : Col D C F := by conclude lemma_collinear1
  have : BetS D E C := by conclude axiom_betweennesssymmetry
  have : D ≠ C := by forward_using lemma_betweennotequal
  have : Col C E F := by conclude lemma_collinear4
  have : Col E F C := by forward_using lemma_collinearorder
  have : ¬ E ≠ F := by
      intro h
      have : Col F B C := by conclude lemma_collinear4
      have : Col F B D := by conclude lemma_collinear4
      have : ¬ F = B := by
          intro h
          have : Col F C D := by conclude_def Col
          have : Col B C D := by conclude cn_equalitysub
          contradict
      have : Col B C D := by conclude lemma_collinear4
      contradict
  close

end GeocoqTranslate.Elements
