/- Transpiled from ../theories/Elements/OriginalProofs/lemma_3_6a.v :: lemma_3_6a
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

set_option maxHeartbeats 800000 in
theorem lemma_3_6a :
    ∀ (A B C D : Point), BetS A B C → BetS A C D → BetS B C D := by
  intro A B C D h1 h2
  have : BetS C B A := by conclude axiom_betweennesssymmetry
  have : BetS D C A := by conclude axiom_betweennesssymmetry
  have : BetS D C B := by conclude axiom_innertransitivity
  have : BetS B C D := by conclude axiom_betweennesssymmetry
  close

end GeocoqTranslate.Elements
