/- Transpiled from ../theories/Elements/OriginalProofs/lemma_NChelper.v :: lemma_NChelper
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_NChelper :
    ∀ (A B C P Q : Point), nCol A B C → Col A B P → Col A B Q → P ≠ Q → nCol P Q C := by
  intro A B C P Q h1 h2 h3 h4
  have : ¬ A = B := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : Col B P Q := by conclude lemma_collinear4
  have : B ≠ A := by conclude lemma_inequalitysymmetric
  have : Col B A P := by forward_using lemma_collinearorder
  have : Col B A Q := by forward_using lemma_collinearorder
  have : Col A P Q := by conclude lemma_collinear4
  have : Col P Q A := by forward_using lemma_collinearorder
  have : Col P Q B := by forward_using lemma_collinearorder
  have : ¬ Col P Q C := by
      intro h
      have : Col A B C := by conclude lemma_collinear5
      contradict
  close

end GeocoqTranslate.Elements
