/- Transpiled from ../theories/Elements/OriginalProofs/lemma_NCorder.v :: lemma_NCorder
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral Point]

set_option maxHeartbeats 800000 in
theorem lemma_NCorder :
    ∀ (A B C : Point), nCol A B C → nCol B A C ∧ nCol B C A ∧ nCol C A B ∧ nCol A C B ∧ nCol C B A := by
  intro A B C h1
  have : ¬ Col B A C := by
      intro h
      have : Col A B C := by perm_close
      contradict
  have : ¬ Col B C A := by
      intro h
      have : Col A B C := by perm_close
      contradict
  have : ¬ Col C A B := by
      intro h
      have : Col A B C := by perm_close
      contradict
  have : ¬ Col A C B := by
      intro h
      have : Col A B C := by perm_close
      contradict
  have : ¬ Col C B A := by
      intro h
      have : Col A B C := by perm_close
      contradict
  close

end GeocoqTranslate.Elements
