/- Transpiled from ../theories/Elements/OriginalProofs/lemma_squareunique.v :: lemma_squareunique
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_squareparallelogram
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_diagonalsbisect
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rightangleNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_Euclid4
import GeocoqTranslate.Elements.OriginalProofs.proposition_04
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoff
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennesspreserved
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoffunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_NCorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass euclidean_euclidean
variable {Point : Type} [euclidean_euclidean Point]

set_option maxHeartbeats 800000 in
theorem lemma_squareunique :
    ∀ (A B C D E : Point), SQ A B C D → SQ A B C E → E = D := by
  intro A B C D E h1 h2
  have : PG A B C D := by conclude lemma_squareparallelogram
  obtain ⟨M, _, _⟩ : ∃ M, (Midpoint A M C ∧ Midpoint B M D) := by conclude lemma_diagonalsbisect
  have : BetS B M D := by conclude_def Midpoint
  have : BetS A M C := by conclude_def Midpoint
  have : Per D A B := by conclude_def SQ
  have : Per E A B := by conclude_def SQ
  have : nCol D A B := by conclude lemma_rightangleNC
  have : nCol E A B := by conclude lemma_rightangleNC
  have : Cong A B A B := by conclude cn_congruencereflexive
  have : Cong A B D A := by conclude_def SQ
  have : Cong A B E A := by conclude_def SQ
  have : Cong E A A B := by conclude lemma_congruencesymmetric
  have : Cong E A D A := by conclude lemma_congruencetransitive
  have : Cong A E A D := by forward_using lemma_congruenceflip
  have : CongA E A B D A B := by conclude lemma_Euclid4
  have : (Cong E B D B ∧ CongA A E B A D B ∧ CongA A B E A B D) := by conclude proposition_04
  have : CongA A B D A B E := by conclude lemma_equalanglessymmetric
  have : B ≠ E := by forward_using lemma_NCdistinct
  have : B ≠ M := by forward_using lemma_betweennotequal
  obtain ⟨N, _, _⟩ : ∃ N, (Out B E N ∧ Cong B N B M) := by conclude lemma_layoff
  have : Cong B M B N := by conclude lemma_congruencesymmetric
  have : A = A := by conclude cn_equalityreflexive
  have : B ≠ A := by forward_using lemma_NCdistinct
  have : Out B A A := by conclude lemma_ray4
  have : Out B M D := by conclude lemma_ray4
  have : Out B D M := by conclude lemma_ray5
  have : nCol A B D := by perm_close
  have : CongA A B D A B D := by conclude lemma_equalanglesreflexive
  have : CongA A B D A B M := by conclude lemma_equalangleshelper
  have : CongA A B M A B D := by conclude lemma_equalanglessymmetric
  have : CongA A B M A B E := by conclude lemma_equalanglestransitive
  have : nCol A B E := by perm_close
  have : CongA A B E A B E := by conclude lemma_equalanglesreflexive
  have : CongA A B E A B N := by conclude lemma_equalangleshelper
  have : CongA A B M A B N := by conclude lemma_equalanglestransitive
  have : Cong B A B A := by conclude cn_congruencereflexive
  have : Cong A M A N := by conclude proposition_04
  have : Per B C D := by conclude_def SQ
  have : Per B C E := by conclude_def SQ
  have : CongA B C E B C D := by conclude lemma_Euclid4
  have : Cong A B C D := by conclude_def SQ
  have : Cong A B C E := by conclude_def SQ
  have : Cong C E A B := by conclude lemma_congruencesymmetric
  have : Cong C E C D := by conclude lemma_congruencetransitive
  have : nCol B C E := by conclude lemma_rightangleNC
  have : nCol B C D := by conclude lemma_rightangleNC
  have : Cong C B C B := by conclude cn_congruencereflexive
  have : (Cong B E B D ∧ CongA C B E C B D ∧ CongA C E B C D B) := by conclude proposition_04
  have : B ≠ C := by forward_using lemma_NCdistinct
  have : C = C := by conclude cn_equalityreflexive
  have : Out B C C := by conclude lemma_ray4
  have : nCol B C D := by conclude lemma_rightangleNC
  have : nCol C B D := by perm_close
  have : CongA C B D C B D := by conclude lemma_equalanglesreflexive
  have : CongA C B D C B M := by conclude lemma_equalangleshelper
  have : nCol C B E := by perm_close
  have : CongA C B E C B E := by conclude lemma_equalanglesreflexive
  have : CongA C B E C B N := by conclude lemma_equalangleshelper
  have : CongA C B E C B D := by conclude lemma_equalanglestransitive
  have : CongA C B D C B E := by conclude lemma_equalanglessymmetric
  have : CongA C B M C B D := by conclude lemma_equalanglessymmetric
  have : CongA C B M C B E := by conclude lemma_equalanglestransitive
  have : CongA C B M C B N := by conclude lemma_equalanglestransitive
  have : CongA M B C N B C := by conclude lemma_equalanglesflip
  have : Cong B C B C := by conclude cn_congruencereflexive
  have : Cong M C N C := by conclude (proposition_04 B M C B N C)
  have : Cong A C A C := by conclude cn_congruencereflexive
  have : BetS A N C := by conclude lemma_betweennesspreserved
  have : A ≠ M := by forward_using lemma_betweennotequal
  have : Out A M C := by conclude lemma_ray4
  have : A ≠ N := by forward_using lemma_betweennotequal
  have : Out A N C := by conclude lemma_ray4
  have : Out A C N := by conclude lemma_ray5
  have : Out A C M := by conclude lemma_ray5
  have : M = N := by conclude lemma_layoffunique
  have : Out B N E := by conclude lemma_ray5
  have : Out B M D := by conclude lemma_ray5
  have : Out B M E := by conclude cn_equalitysub
  have : E = D := by conclude lemma_layoffunique
  close

end GeocoqTranslate.Elements
