/- Transpiled from ../theories/Elements/OriginalProofs/lemma_ABCequalsCBA.v :: lemma_ABCequalsCBA
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

theorem lemma_ABCequalsCBA :
    ∀ (A B C : Point), nCol A B C → CongA A B C C B A := by
  intro A B C h1
  have : ¬ B = A := by
      intro h
      have : A = B := by conclude lemma_equalitysymmetric
      have : Col A B C := by conclude_def Col
      contradict
  have : ¬ C = B := by
      intro h
      have : Col C B A := by conclude_def Col
      have : Col A B C := by forward_using lemma_collinearorder
      contradict
  obtain ⟨E, _, _⟩ : ∃ E, (BetS B A E ∧ Cong A E C B) := by conclude lemma_extension
  have : ¬ B = C := by
      intro h
      have : Col A B C := by conclude_def Col
      contradict
  have : A ≠ B := by conclude lemma_inequalitysymmetric
  obtain ⟨F, _, _⟩ : ∃ F, (BetS B C F ∧ Cong C F A B) := by conclude lemma_extension
  have : Cong B A F C := by forward_using lemma_doublereverse
  have : BetS F C B := by conclude axiom_betweennesssymmetry
  have : Cong B E F B := by conclude cn_sumofparts
  have : Cong F B B F := by conclude cn_equalityreverse
  have : Cong B E B F := by conclude lemma_congruencetransitive
  have : Cong B F B E := by conclude lemma_congruencesymmetric
  have : Cong E F F E := by conclude cn_equalityreverse
  have : Out B A E := by conclude lemma_ray4
  have : Out B C F := by conclude lemma_ray4
  have : CongA A B C C B A := by conclude_def CongA
  close

end GeocoqTranslate.Elements
