/- Transpiled from ../theories/Elements/OriginalProofs/lemma_lessthantransitive.v :: lemma_lessthantransitive
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoff
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_layoffunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_lessthantransitive :
    ∀ (A B C D E F : Point), Lt A B C D → Lt C D E F → Lt A B E F := by
  intro A B C D E F h1 h2
  obtain ⟨G, _, _⟩ : ∃ G, (BetS C G D ∧ Cong C G A B) := by conclude_def Lt
  obtain ⟨H, _, _⟩ : ∃ H, (BetS E H F ∧ Cong E H C D) := by conclude_def Lt
  have : E ≠ H := by forward_using lemma_betweennotequal
  have : C ≠ G := by forward_using lemma_betweennotequal
  obtain ⟨K, _, _⟩ : ∃ K, (Out E H K ∧ Cong E K C G) := by conclude lemma_layoff
  have : Cong E K A B := by conclude lemma_congruencetransitive
  have : (BetS E K H ∨ H = K ∨ BetS E H K) := by conclude lemma_ray1
  have : BetS E K H := by
      rcases (show BetS E K H ∨ H = K ∨ BetS E H K by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · close
      · have : Cong C G E K := by conclude lemma_congruencesymmetric
        have : Cong C G E H := by conclude cn_equalitysub
        have : Cong C G C D := by conclude lemma_congruencetransitive
        have : Out C G D := by conclude lemma_ray4
        have : G = G := by conclude cn_equalityreflexive
        have : Out C G G := by conclude lemma_ray4
        have : ¬ ¬ BetS E K H := by
            intro h
            have : G = D := by conclude lemma_layoffunique
            have : G ≠ D := by forward_using lemma_betweennotequal
            contradict
        close
      · have : Cong C D E H := by conclude lemma_congruencesymmetric
        have : Cong C G E K := by conclude lemma_congruencesymmetric
        have : C ≠ D := by forward_using lemma_betweennotequal
        have : H ≠ K := by forward_using lemma_betweennotequal
        obtain ⟨J, _, _⟩ : ∃ J, (BetS C D J ∧ Cong D J H K) := by conclude lemma_extension
        have : Out C D J := by conclude lemma_ray4
        have : Out C D G := by conclude lemma_ray4
        have : Cong C J E K := by conclude cn_sumofparts
        have : Cong C J C G := by conclude lemma_congruencetransitive
        have : J = G := by conclude lemma_layoffunique
        have : BetS G D J := by conclude lemma_3_6a
        have : ¬ ¬ BetS E K H := by
            intro h
            have : G ≠ J := by forward_using lemma_betweennotequal
            have : J ≠ G := by conclude lemma_inequalitysymmetric
            contradict
        close
  have : BetS E K F := by conclude lemma_3_6b
  have : Lt A B E F := by conclude_def Lt
  close

end GeocoqTranslate.Elements
