/- Transpiled from ../theories/Elements/OriginalProofs/lemma_3_5b.v :: lemma_3_5b
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7a

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_3_5b :
    ∀ (A B C D : Point), BetS A B D → BetS B C D → BetS A C D := by
  intro A B C D h1 h2
  have : BetS A B C := by conclude axiom_innertransitivity
  have : BetS A C D := by conclude lemma_3_7a
  close

end GeocoqTranslate.Elements
