/- Transpiled from ../theories/Elements/OriginalProofs/lemma_supplementinequality.v :: lemma_supplementinequality
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesNC
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray1
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_7b
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_raystrict
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglessymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_supplements
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesreflexive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray5
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglesflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ray3
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalanglestransitive
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_angleorderrespectscongruence2
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_supplementinequality :
    ∀ (A B C D F a b c d f : Point), Supp A B C D F → Supp a b c d f → LtA a b c A B C → LtA D B F d b f := by
  intro A B C D F a b c d f h1 h2 h3
  obtain ⟨P, Q, R, _, _, _, _⟩ : ∃ P Q R, (BetS P R Q ∧ Out B A P ∧ Out B C Q ∧ CongA a b c A B R) := by conclude_def LtA
  have : nCol A B R := by conclude lemma_equalanglesNC
  have : (Out B C D ∧ BetS A B F) := by conclude_def Supp
  have : BetS Q R P := by conclude axiom_betweennesssymmetry
  have : BetS F B A := by conclude axiom_betweennesssymmetry
  have : (BetS B P A ∨ A = P ∨ BetS B A P) := by conclude lemma_ray1
  have : BetS F B P := by
      rcases (show BetS B P A ∨ A = P ∨ BetS B A P by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3
      · have : BetS F B P := by conclude axiom_innertransitivity
        close
      · have : BetS F B P := by conclude cn_equalitysub
        close
      · have : BetS F B P := by conclude lemma_3_7b
        close
  have : ¬ Col F P Q := by
      intro h
      have : Col B A P := by conclude lemma_rayimpliescollinear
      have : Col A B F := by conclude_def Col
      have : A ≠ B := by forward_using lemma_betweennotequal
      have : Col A B P := by forward_using lemma_collinearorder
      have : Col B F P := by conclude lemma_collinear4
      have : Col F P B := by forward_using lemma_collinearorder
      have : F ≠ P := by forward_using lemma_betweennotequal
      have : Col P Q B := by conclude lemma_collinear4
      have : Col P B Q := by forward_using lemma_collinearorder
      have : Col P B A := by forward_using lemma_collinearorder
      have : B ≠ P := by forward_using lemma_betweennotequal
      have : P ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B Q A := by conclude lemma_collinear4
      have : Col P R Q := by conclude_def Col
      have : Col P Q R := by forward_using lemma_collinearorder
      have : Col P Q B := by forward_using lemma_collinearorder
      have : P ≠ Q := by forward_using lemma_betweennotequal
      have : Col Q R B := by conclude lemma_collinear4
      have : Col Q B R := by forward_using lemma_collinearorder
      have : Col Q B A := by forward_using lemma_collinearorder
      have : B ≠ Q := by conclude lemma_raystrict
      have : Q ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B R A := by conclude lemma_collinear4
      have : Col A B R := by forward_using lemma_collinearorder
      contradict
  obtain ⟨M, _, _⟩ : ∃ M, (BetS F M R ∧ BetS Q M B) := by conclude postulate_Pasch_inner
  have : R = R := by conclude cn_equalityreflexive
  have : ¬ B = R := by
      intro h
      have : Col A B R := by conclude_def Col
      contradict
  have : Out B R R := by conclude lemma_ray4
  have : Supp A B R R F := by conclude_def Supp
  have : CongA A B R a b c := by conclude lemma_equalanglessymmetric
  have : CongA R B F d b f := by conclude lemma_supplements
  have : B ≠ F := by forward_using lemma_betweennotequal
  have : F = F := by conclude cn_equalityreflexive
  have : Out B F F := by conclude lemma_ray4
  have : CongA d b f R B F := by conclude lemma_equalanglessymmetric
  have : nCol R B F := by conclude lemma_equalanglesNC
  have : ¬ Col F B Q := by
      intro h
      have : Col Q B F := by forward_using lemma_collinearorder
      have : Col Q M B := by conclude_def Col
      have : Col Q B M := by forward_using lemma_collinearorder
      have : Q ≠ B := by forward_using lemma_betweennotequal
      have : Col B F M := by conclude lemma_collinear4
      have : Col F M R := by conclude_def Col
      have : Col M F B := by forward_using lemma_collinearorder
      have : Col M F R := by forward_using lemma_collinearorder
      have : F ≠ M := by forward_using lemma_betweennotequal
      have : M ≠ F := by conclude lemma_inequalitysymmetric
      have : Col F B R := by conclude lemma_collinear4
      have : Col R B F := by forward_using lemma_collinearorder
      contradict
  have : CongA F B Q F B Q := by conclude lemma_equalanglesreflexive
  have : BetS B M Q := by conclude axiom_betweennesssymmetry
  have : B ≠ M := by forward_using lemma_betweennotequal
  have : Out B M Q := by conclude lemma_ray4
  have : Out B Q M := by conclude lemma_ray5
  have : CongA F B Q F B M := by conclude lemma_equalangleshelper
  have : BetS R M F := by conclude axiom_betweennesssymmetry
  have : LtA F B Q F B R := by conclude_def LtA
  have : CongA f b d F B R := by conclude lemma_equalanglesflip
  have : CongA F B R f b d := by conclude lemma_equalanglessymmetric
  have : LtA F B Q f b d := by conclude lemma_angleorderrespectscongruence
  have : Out B Q D := by conclude lemma_ray3
  have : CongA F B Q F B D := by conclude lemma_equalangleshelper
  have : ¬ Col F B D := by
      intro h
      have : Col B Q D := by conclude lemma_rayimpliescollinear
      have : Col D B Q := by forward_using lemma_collinearorder
      have : Col D B F := by forward_using lemma_collinearorder
      have : B ≠ D := by conclude lemma_raystrict
      have : D ≠ B := by conclude lemma_inequalitysymmetric
      have : Col B Q F := by conclude lemma_collinear4
      have : Col F B Q := by forward_using lemma_collinearorder
      contradict
  have : CongA F B D D B F := by conclude lemma_ABCequalsCBA
  have : CongA F B Q D B F := by conclude lemma_equalanglestransitive
  have : CongA D B F F B Q := by conclude lemma_equalanglessymmetric
  have : LtA D B F f b d := by conclude lemma_angleorderrespectscongruence2
  have : nCol f b d := by conclude lemma_equalanglesNC
  have : ¬ Col d b f := by
      intro h
      have : Col f b d := by forward_using lemma_collinearorder
      contradict
  have : CongA d b f f b d := by conclude lemma_ABCequalsCBA
  have : LtA D B F d b f := by conclude lemma_angleorderrespectscongruence
  close

end GeocoqTranslate.Elements
