/- Transpiled from ../theories/Elements/OriginalProofs/lemma_3_7a.v :: lemma_3_7a
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_localextension
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_3_6a
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_extensionunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_3_7a :
    ∀ (A B C D : Point), BetS A B C → BetS B C D → BetS A C D := by
  intro A B C D h1 h2
  have : A ≠ C := by forward_using lemma_betweennotequal
  have : C ≠ D := by forward_using lemma_betweennotequal
  obtain ⟨E, _, _⟩ : ∃ E, (BetS A C E ∧ Cong C E C D) := by conclude lemma_localextension
  have : Cong C D C E := by conclude lemma_congruencesymmetric
  have : BetS B C E := by conclude lemma_3_6a
  have : D = E := by conclude lemma_extensionunique
  have : BetS A C D := by conclude cn_equalitysub
  close

end GeocoqTranslate.Elements
