/- Transpiled from ../theories/Elements/OriginalProofs/lemma_collinearparallel.v :: lemma_collinearparallel
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_collinearparallel :
    ∀ (A B C c d : Point), Par A B c d → Col c d C → C ≠ d → Par A B C d := by
  intro A B C c d h1 h2 h3
  obtain ⟨R, a, b, p, q, _, _, _, _, _, _, _, _, _, _, _⟩ : ∃ R a b p q, (A ≠ B ∧ c ≠ d ∧ Col A B a ∧ Col A B b ∧ a ≠ b ∧ Col c d p ∧ Col c d q ∧ p ≠ q ∧ ¬ Meet A B c d ∧ BetS a R q ∧ BetS p R b) := by conclude_def Par
  have : d ≠ C := by conclude lemma_inequalitysymmetric
  have : Col d C p := by conclude lemma_collinear4
  have : Col C d p := by forward_using lemma_collinearorder
  have : Col d C q := by conclude lemma_collinear4
  have : Col C d q := by forward_using lemma_collinearorder
  have : ¬ Meet A B C d := by
      intro h
      obtain ⟨E, _, _, _, _⟩ : ∃ E, (A ≠ B ∧ C ≠ d ∧ Col A B E ∧ Col C d E) := by conclude_def Meet
      have : Col C d c := by forward_using lemma_collinearorder
      have : Col d E c := by conclude lemma_collinear4
      have : Col c d E := by forward_using lemma_collinearorder
      have : Meet A B c d := by conclude_def Meet
      contradict
  have : Par A B C d := by conclude_def Par
  close

end GeocoqTranslate.Elements
