/- Transpiled from ../theories/Elements/OriginalProofs/lemma_rightangleNC.v :: lemma_rightangleNC
   Structure-preserving; generated by geolean_transpile. -/
import GeocoqTranslate.Elements.OriginalProofs.euclidean_tactics
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_midpointunique
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_equalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_partnotequalwhole
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinear4
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_doublereverse
import GeocoqTranslate.Elements.OriginalProofs.Lemmas.lemma_collinearorder

namespace GeocoqTranslate.Elements
open euclidean_neutral_basis euclidean_neutral euclidean_neutral_ruler_compass
variable {Point : Type} [euclidean_neutral_ruler_compass Point]

set_option maxHeartbeats 800000 in
theorem lemma_rightangleNC :
    ∀ (A B C : Point), Per A B C → nCol A B C := by
  intro A B C h1
  obtain ⟨D, _, _, _, _⟩ : ∃ D, (BetS A B D ∧ Cong A B D B ∧ Cong A C D C ∧ B ≠ C) := by conclude_def Per
  have : Cong A B B D := by forward_using lemma_congruenceflip
  have : Midpoint A B D := by conclude_def Midpoint
  have : ¬ BetS A C D := by
      intro h
      have : Cong A C C D := by forward_using lemma_congruenceflip
      have : Midpoint A C D := by conclude_def Midpoint
      have : B = C := by conclude lemma_midpointunique
      contradict
  have : A ≠ B := by forward_using lemma_betweennotequal
  have : ¬ C = A := by
      intro h
      have : Cong C C D C := by conclude cn_equalitysub
      have : Cong D C C C := by conclude lemma_congruencesymmetric
      have : ¬ D ≠ C := by
          intro h
          have : C ≠ C := by conclude axiom_nocollapse
          have : C = C := by conclude cn_equalityreflexive
          contradict
      have : A = C := by conclude lemma_equalitysymmetric
      have : D = A := by conclude cn_equalitytransitive
      have : A = D := by conclude lemma_equalitysymmetric
      have : A ≠ D := by forward_using lemma_betweennotequal
      contradict
  have : ¬ C = D := by
      intro h
      have : Cong A C D D := by conclude cn_equalitysub
      have : ¬ A ≠ C := by
          intro h
          have : D ≠ D := by conclude axiom_nocollapse
          have : D = D := by conclude cn_equalityreflexive
          contradict
      have : C = A := by conclude lemma_equalitysymmetric
      contradict
  have : ¬ BetS C A D := by
      intro h
      have : Cong C A C D := by forward_using lemma_congruenceflip
      have : ¬ Cong C A C D := by conclude lemma_partnotequalwhole
      contradict
  have : ¬ BetS A D C := by
      intro h
      have : BetS C D A := by conclude axiom_betweennesssymmetry
      have : Cong C D C A := by forward_using lemma_doublereverse
      have : ¬ Cong C D C A := by conclude lemma_partnotequalwhole
      contradict
  have : ¬ Col A B C := by
      intro h
      have : Col A B D := by conclude_def Col
      have : Col B A C := by forward_using lemma_collinearorder
      have : Col B A D := by forward_using lemma_collinearorder
      have : B ≠ A := by conclude lemma_inequalitysymmetric
      have : Col A C D := by conclude lemma_collinear4
      have : (A = C ∨ A = D ∨ C = D ∨ BetS C A D ∨ BetS A C D ∨ BetS A D C) := by conclude_def Col
      have : nCol A B C := by
          rcases (show A = C ∨ A = D ∨ C = D ∨ BetS C A D ∨ BetS A C D ∨ BetS A D C by first | assumption | exact nCol_or_Col _ _ _ | exact Col_or_nCol _ _ _ | exact Classical.em _ | tauto | aesop) with c1 | c2 | c3 | c4 | c5 | c6
          · have : ¬ Col A B C := by
                intro h
                have : A ≠ C := by conclude lemma_inequalitysymmetric
                contradict
            close
          · have : ¬ Col A B C := by
                intro h
                have : A ≠ D := by forward_using lemma_betweennotequal
                contradict
            close
          · have : ¬ Col A B C := by
                intro h
                contradict
            close
          · have : ¬ Col A B C := by
                intro h
                contradict
            close
          · have : ¬ Col A B C := by
                intro h
                contradict
            close
          · have : ¬ Col A B C := by
                intro h
                contradict
            close
      contradict
  close

end GeocoqTranslate.Elements
