-- This module serves as the root of the `GeocoqTranslate` library.
-- Import modules here that should be built as part of the library.
import «GeocoqTranslate».Basic
import «GeocoqTranslate».Tarski.Axioms
import «GeocoqTranslate».Tarski.Definitions
import «GeocoqTranslate».Euclidean.Axioms
import «GeocoqTranslate».Hilbert.Axioms
import «GeocoqTranslate».Tarski_dev.Ch02_cong
import «GeocoqTranslate».Tarski_dev.Ch03_bet
import «GeocoqTranslate».Tarski_dev.Ch04_col
import «GeocoqTranslate».Tarski_dev.Ch04_cong_bet
import «GeocoqTranslate».Tarski_dev.Ch05_bet_le
import «GeocoqTranslate».Tarski_dev.Ch06_out_lines
import «GeocoqTranslate».Tarski_dev.Ch07_midpoint
import «GeocoqTranslate».Tarski_dev.Ch08_orthogonality
import «GeocoqTranslate».Tarski_dev.Ch09_plane
import «GeocoqTranslate».Tarski_dev.Ch10_line_reflexivity
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_congruencesymmetric
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_congruencetransitive
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_congruenceflip
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_inequalitysymmetric
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_localextension
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_3_6a
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_betweennotequal
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_extensionunique
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_3_7a
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_3_7b
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_3_5b
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_3_6b
import «GeocoqTranslate».Elements.OriginalProofs.euclidean_defs
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_partnotequalwhole
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_doublereverse
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_NCdistinct
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_differenceofparts
import «GeocoqTranslate».Elements.OriginalProofs.proposition_01
import «GeocoqTranslate».Elements.OriginalProofs.proposition_02
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_extension
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_betweennesspreserved
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_lessthancongruence
import «GeocoqTranslate».Elements.OriginalProofs.proposition_03
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_layoff
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_trichotomy2
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_TGsymmetric
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_ray4
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_ray2
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_ETreflexive
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_TGflip
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_TTflip2
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_TTorder
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_collinearparallel
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_interior5
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_lessthannotequal
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_ray3
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_rectanglerotate
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_rightreverse
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_samesidereflexive
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_supplementsymmetric
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_together
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_trichotomy1
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_ABCequalsCBA
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_NCorder
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_Pasch_outer2
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_TTflip
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_crossbar
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_equalangleshelper
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_parallelNC
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_paralleldef2A
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_parallelflip
import «GeocoqTranslate».Elements.OriginalProofs.Lemmas.lemma_rayimpliescollinear
import «GeocoqTranslate».Elements.OriginalProofs.proposition_08
import «GeocoqTranslate».Elements.OriginalProofs.proposition_11
